// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuddingPlatform.Data;

#nullable disable

namespace PuddingPlatform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    partial class PlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .IsUnique();

                    b.ToTable("AppRoles", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "可管理所属 Workspace 的配置、成员和 Agent 模板",
                            IsSystemRole = true,
                            Name = "Workspace 管理员",
                            PermissionsJson = "[\"workspace:manage\",\"workspace:write\",\"workspace:read\",\"agent:manage\",\"template:manage\"]",
                            RoleId = "workspace-admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "可在 Workspace 内创建/使用 Session 和 Agent",
                            IsSystemRole = true,
                            Name = "Workspace 编辑",
                            PermissionsJson = "[\"workspace:write\",\"workspace:read\",\"agent:run\",\"template:read\"]",
                            RoleId = "workspace-editor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "只读访问 Workspace 内容",
                            IsSystemRole = true,
                            Name = "Workspace 查看者",
                            PermissionsJson = "[\"workspace:read\",\"template:read\"]",
                            RoleId = "workspace-viewer",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "可管理 LLM 资源池（服务商/模型/配额）",
                            IsSystemRole = true,
                            Name = "LLM 资源管理员",
                            PermissionsJson = "[\"llm:manage\",\"llm:read\"]",
                            RoleId = "llm-admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AppUsers", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppUserRoleEntity", b =>
                {
                    b.Property<int>("UserEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleEntityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserEntityId", "RoleEntityId");

                    b.HasIndex("RoleEntityId");

                    b.ToTable("AppUserRoles", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.CapabilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapabilityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("RequiresFileWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresNetworkAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresShellExecution")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ToolDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolParametersJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId")
                        .IsUnique();

                    b.ToTable("Capabilities", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapabilityId = "cap-bash",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "允许 Agent 在隔离容器中执行 bash 命令。",
                            IsEnabled = true,
                            Name = "Bash 命令执行",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = true,
                            SortOrder = 10,
                            ToolDescription = "Execute a bash shell command inside the agent sandbox container.",
                            ToolName = "bash",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"command\":{\"type\":\"string\",\"description\":\"Shell command to execute\"}},\"required\":[\"command\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CapabilityId = "cap-python",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "允许 Agent 在隔离容器中执行 Python 3 代码。",
                            IsEnabled = true,
                            Name = "Python 代码执行",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = true,
                            SortOrder = 20,
                            ToolDescription = "Execute Python 3 code inside the agent sandbox container.",
                            ToolName = "python",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"code\":{\"type\":\"string\",\"description\":\"Python 3 code to execute\"}},\"required\":[\"code\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CapabilityId = "cap-read-file",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "允许 Agent 读取沙箱容器内的文件内容。",
                            IsEnabled = true,
                            Name = "读取文件",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = true,
                            SortOrder = 30,
                            ToolDescription = "Read the content of a file from the agent's container filesystem.",
                            ToolName = "read_file",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"Absolute or relative file path inside the container\"}},\"required\":[\"path\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CapabilityId = "cap-write-file",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "允许 Agent 在沙箱容器内创建或覆写文件。",
                            IsEnabled = true,
                            Name = "写入文件",
                            RequiresFileWrite = true,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = true,
                            SortOrder = 40,
                            ToolDescription = "Create or overwrite a file in the agent's container filesystem.",
                            ToolName = "write_file",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"path\":{\"type\":\"string\",\"description\":\"File path to write\"},\"content\":{\"type\":\"string\",\"description\":\"Text content to write to the file\"}},\"required\":[\"path\",\"content\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CapabilityId = "cap-http-fetch",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "允许 Agent 发起 HTTP GET/POST 请求，访问外部 API 或网页。",
                            IsEnabled = true,
                            Name = "HTTP 请求",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = true,
                            RequiresShellExecution = false,
                            SortOrder = 50,
                            ToolDescription = "Make an HTTP GET or POST request to a URL and return the response body.",
                            ToolName = "http_fetch",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"url\":{\"type\":\"string\",\"description\":\"The full HTTP/HTTPS URL to request\"},\"method\":{\"type\":\"string\",\"description\":\"HTTP method: GET or POST (default: GET)\"},\"body\":{\"type\":\"string\",\"description\":\"Request body for POST requests (optional)\"}},\"required\":[\"url\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            CapabilityId = "cap-spawn-sub-agent",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "派生子代理执行独立任务。子代理拥有独立上下文窗口。",
                            IsEnabled = true,
                            Name = "派生子代理",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 60,
                            ToolDescription = "Spawn a sub-agent to execute a task independently with its own context window.",
                            ToolName = "spawn_sub_agent",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"task\":{\"type\":\"string\",\"description\":\"子代理要执行的任务描述\"},\"agent_template\":{\"type\":\"string\",\"description\":\"Agent 模板ID\"},\"sync\":{\"type\":\"boolean\",\"description\":\"同步等待(默认)或异步执行\"}},\"required\":[\"task\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            CapabilityId = "cap-memory-library",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "查询记忆图书馆，召回与当前上下文相关的记忆片段。",
                            IsEnabled = true,
                            Name = "记忆图书馆",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 70,
                            ToolDescription = "Query the memory library to recall relevant past context.",
                            ToolName = "memory_library",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\",\"description\":\"自然语言查询\"},\"book\":{\"type\":\"string\",\"description\":\"可选：限定记忆本名称\"}},\"required\":[\"query\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            CapabilityId = "cap-save-memory",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "将当前对话中的重要信息保存到记忆图书馆供未来召回。",
                            IsEnabled = true,
                            Name = "保存记忆",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 80,
                            ToolDescription = "Save important information from the current conversation to the memory library.",
                            ToolName = "save_memory",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"memory_content\":{\"type\":\"string\",\"description\":\"要保存的记忆内容\"},\"memory_type\":{\"type\":\"string\",\"description\":\"记忆类型：short / long\"}},\"required\":[\"memory_content\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            CapabilityId = "cap-manage-memory",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "管理记忆条目：浏览、搜索、标记重要度、清理过期记忆。",
                            IsEnabled = true,
                            Name = "记忆管理",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 85,
                            ToolDescription = "Manage memory entries: browse, search, mark importance, clean stale memories.",
                            ToolName = "manage_memory",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"action\":{\"type\":\"string\",\"description\":\"操作: list/search/mark/clean\"},\"keyword\":{\"type\":\"string\",\"description\":\"搜索或标记关键词\"}},\"required\":[\"action\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            CapabilityId = "cap-grep-memory",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "全文搜索记忆库，快速定位包含关键词的记忆条目。",
                            IsEnabled = true,
                            Name = "记忆搜索",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 90,
                            ToolDescription = "Full-text search the memory store for entries containing specific keywords.",
                            ToolName = "grep_memory",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"keyword\":{\"type\":\"string\",\"description\":\"搜索关键词\"}},\"required\":[\"keyword\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            CapabilityId = "cap-query-sessions",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "查询历史会话的完整对话记录。支持分页和时间游标。",
                            IsEnabled = true,
                            Name = "查询会话记录",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 95,
                            ToolDescription = "Query complete conversation records from historical sessions with pagination.",
                            ToolName = "query_sessions",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"action\":{\"type\":\"string\",\"description\":\"messages 或 recent\"},\"session_id\":{\"type\":\"string\"},\"limit\":{\"type\":\"number\"}},\"required\":[\"action\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            CapabilityId = "cap-search-files",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "在沙箱容器文件系统中按名称或内容搜索文件。",
                            IsEnabled = true,
                            Name = "文件搜索",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 100,
                            ToolDescription = "Search for files by name or content within the sandbox container filesystem.",
                            ToolName = "search_files",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"pattern\":{\"type\":\"string\",\"description\":\"文件名或内容模式\"},\"path\":{\"type\":\"string\",\"description\":\"搜索起始目录\"}},\"required\":[\"pattern\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            CapabilityId = "cap-search-codebase",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "在代码库中语义搜索相关代码片段、函数和类定义。",
                            IsEnabled = true,
                            Name = "代码库搜索",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 105,
                            ToolDescription = "Semantically search the codebase for relevant code snippets, functions, and class definitions.",
                            ToolName = "search_codebase",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\",\"description\":\"代码语义搜索查询\"},\"language\":{\"type\":\"string\"}},\"required\":[\"query\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            CapabilityId = "cap-task-manager",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "管理 Agent 内部任务列表：创建、更新状态、列出、删除。",
                            IsEnabled = true,
                            Name = "任务管理",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 110,
                            ToolDescription = "Manage the agent's internal task list: create, update status, list, delete.",
                            ToolName = "manage_tasks",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"operation\":{\"type\":\"string\",\"description\":\"操作: create/update_status/list/delete\"},\"title\":{\"type\":\"string\"},\"status\":{\"type\":\"string\"}},\"required\":[\"operation\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 15,
                            CapabilityId = "cap-event-subscribe",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "管理 Agent 事件订阅：订阅/取消订阅事件类型，列出当前订阅。",
                            IsEnabled = true,
                            Name = "事件订阅管理",
                            RequiresFileWrite = false,
                            RequiresNetworkAccess = false,
                            RequiresShellExecution = false,
                            SortOrder = 115,
                            ToolDescription = "Manage agent event subscriptions: subscribe/unsubscribe event types, list active subscriptions.",
                            ToolName = "event_subscribe",
                            ToolParametersJson = "{\"type\":\"object\",\"properties\":{\"operation\":{\"type\":\"string\",\"description\":\"subscribe/unsubscribe/list\"},\"event_types\":{\"type\":\"string\",\"description\":\"逗号分隔的事件类型\"}},\"required\":[\"operation\"]}",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.ChatMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThinkingJson")
                        .HasColumnType("text");

                    b.Property<string>("UsageJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("ChatMessages", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.GlobalAgentTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowFileWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowNetworkAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowShellExecution")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedToolNamesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxReplyTokens")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryLlmApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MemoryLlmEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MemoryLlmModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreferredModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreferredProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SelectedCapabilityIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedSkillPackageIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPromptTemplate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.ToTable("GlobalAgentTemplates", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowFileWrite = false,
                            AllowNetworkAccess = false,
                            AllowShellExecution = false,
                            AllowedToolNamesJson = "[]",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "通用型对话助手，适合日常问答、文案写作等场景。",
                            IsBuiltIn = true,
                            IsEnabled = true,
                            MaxContextTokens = 32768,
                            MaxReplyTokens = 2048,
                            Name = "通用助手",
                            PreferredModelId = "gpt-4o-mini",
                            PreferredProviderId = "openai",
                            Role = "Service",
                            SelectedCapabilityIdsJson = "[]",
                            SelectedSkillPackageIdsJson = "[]",
                            SortOrder = 10,
                            SystemPrompt = "你是一个专业、友好的 AI 助手。请直接、准确地回答用户的问题。",
                            TemplateId = "general-assistant",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.KnowledgeBaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KbId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KbType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KbId")
                        .IsUnique();

                    b.HasIndex("WorkspaceEntityId");

                    b.ToTable("KnowledgeBases", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmModelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CapabilityTagsJson")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("InputPricePer1MTokens")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OutputPricePer1MTokens")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ModelId")
                        .IsUnique();

                    b.ToTable("LlmModels", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapabilityTagsJson = "[\"text\",\"vision\",\"function-calling\",\"json-mode\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "轻量级多模态模型，适合一般对话和任务，性价比高。",
                            InputPricePer1MTokens = 0.15m,
                            IsDefault = true,
                            IsDeprecated = false,
                            MaxContextTokens = 128000,
                            MaxOutputTokens = 4096,
                            ModelId = "gpt-4o-mini",
                            Name = "GPT-4o Mini",
                            OutputPricePer1MTokens = 0.60m,
                            ProviderId = 1,
                            SortOrder = 10,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CapabilityTagsJson = "[\"text\",\"vision\",\"function-calling\",\"json-mode\"]",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "高性能多模态旗舰模型，支持视觉、函数调用与结构化输出。",
                            InputPricePer1MTokens = 5.00m,
                            IsDefault = false,
                            IsDeprecated = false,
                            MaxContextTokens = 128000,
                            MaxOutputTokens = 4096,
                            ModelId = "gpt-4o",
                            Name = "GPT-4o",
                            OutputPricePer1MTokens = 15.00m,
                            ProviderId = 1,
                            SortOrder = 20,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmProviderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("LlmProviders", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.openai.com/v1",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "OpenAI 官方 API",
                            IsEnabled = true,
                            Name = "OpenAI",
                            Protocol = "openai",
                            ProviderId = "openai",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmProviderQuotaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DailyResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DailyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<long>("DailyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MonthlyResetAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MonthlyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique();

                    b.ToTable("LlmProviderQuotas", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.SkillPackageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SkillPackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("SkillPackageId")
                        .IsUnique();

                    b.ToTable("SkillPackages", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("Teams", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "平台默认团队",
                            IsEnabled = true,
                            Name = "平台团队",
                            TeamId = "platform-team",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.TeamMemberEntity", b =>
                {
                    b.Property<int>("TeamEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("UserEntityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("TeamEntityId", "UserEntityId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("TeamMembers", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkflowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefinitionJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.HasIndex("WorkspaceEntityId");

                    b.ToTable("Workflows", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceAgentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredModelId")
                        .HasColumnType("text");

                    b.Property<string>("PreferredProviderId")
                        .HasColumnType("text");

                    b.Property<string>("SourceTemplateId")
                        .HasColumnType("text");

                    b.Property<string>("SystemPromptOverride")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.HasIndex("WorkspaceEntityId");

                    b.ToTable("WorkspaceAgents", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceAgentTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowFileWrite")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowNetworkAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowShellExecution")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedToolNamesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseGlobalTemplateId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContainerImage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MemoryLlmApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MemoryLlmEndpoint")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("MemoryLlmModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("MaxContextTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxReplyTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreferredModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PreferredProviderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SelectedCapabilityIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserPromptTemplate")
                        .HasColumnType("text");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "TemplateId")
                        .IsUnique();

                    b.ToTable("WorkspaceAgentTemplates", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceChannelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultAgentId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("WorkspaceEntityId");

                    b.ToTable("WorkspaceChannels", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyAccessPolicy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TeamAccessPolicy")
                        .HasColumnType("integer");

                    b.Property<int>("TeamEntityId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.HasIndex("TeamEntityId", "Slug")
                        .IsUnique();

                    b.ToTable("Workspaces", "platform");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyAccessPolicy = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "平台内置默认工作空间",
                            IsEnabled = true,
                            IsFrozen = false,
                            Name = "默认工作空间",
                            Slug = "default",
                            TeamAccessPolicy = 2,
                            TeamEntityId = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceId = "default"
                        });
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserEntityId");

                    b.HasIndex("WorkspaceEntityId", "UserEntityId")
                        .IsUnique();

                    b.ToTable("WorkspaceMembers", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceSkillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.HasIndex("WorkspaceEntityId");

                    b.ToTable("WorkspaceSkills", "platform");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppUserRoleEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.AppRoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuddingPlatform.Data.Entities.AppUserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.KnowledgeBaseEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmModelEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.LlmProviderEntity", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmProviderQuotaEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.LlmProviderEntity", "Provider")
                        .WithOne("Quota")
                        .HasForeignKey("PuddingPlatform.Data.Entities.LlmProviderQuotaEntity", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.TeamMemberEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.TeamEntity", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuddingPlatform.Data.Entities.AppUserEntity", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkflowEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceAgentEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceChannelEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.TeamEntity", "Team")
                        .WithMany("Workspaces")
                        .HasForeignKey("TeamEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceMemberEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.AppUserEntity", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceSkillEntity", b =>
                {
                    b.HasOne("PuddingPlatform.Data.Entities.WorkspaceEntity", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppRoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.AppUserEntity", b =>
                {
                    b.Navigation("TeamMemberships");

                    b.Navigation("UserRoles");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.LlmProviderEntity", b =>
                {
                    b.Navigation("Models");

                    b.Navigation("Quota");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.TeamEntity", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("PuddingPlatform.Data.Entities.WorkspaceEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
