import { createStyles } from 'antd-style';

export const useHomeStyles = createStyles(() => ({
  page: {
    width: 'min(1380px, 100%)',
    margin: '0 auto',
    padding: '8px 8px 32px',
    color: 'var(--pudding-chat-text)',
    animation: 'pageEnterRuntime 180ms ease-out',
  },
  hero: {
    position: 'relative',
    overflow: 'hidden',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.6fr) minmax(260px, 0.7fr)',
    gap: 28,
    padding: '32px 34px',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 16,
    background:
      'linear-gradient(132deg, color-mix(in srgb, var(--pudding-chat-accent) 11%, var(--pudding-chat-surface)) 0%, var(--pudding-chat-surface) 54%, color-mix(in srgb, #0ea5e9 7%, var(--pudding-chat-surface)) 100%)',
    boxShadow: '0 14px 38px rgba(28, 24, 18, 0.08)',
    '&::after': {
      content: '""',
      position: 'absolute',
      width: 260,
      height: 260,
      right: -110,
      top: -150,
      borderRadius: '50%',
      background:
        'color-mix(in srgb, var(--pudding-chat-accent) 12%, transparent)',
      filter: 'blur(2px)',
      pointerEvents: 'none',
    },
    '@media (max-width: 860px)': {
      gridTemplateColumns: '1fr',
      padding: 24,
    },
  },
  eyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    color: 'var(--pudding-chat-accent)',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  heroTitle: {
    margin: 0,
    color: 'var(--pudding-chat-text)',
    fontSize: 'clamp(28px, 4vw, 42px)',
    lineHeight: 1.15,
    fontWeight: 720,
    letterSpacing: '-0.035em',
  },
  heroDescription: {
    maxWidth: 650,
    margin: '14px 0 0',
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 15,
    lineHeight: 1.75,
  },
  heroActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 24,
  },
  statusPanel: {
    position: 'relative',
    zIndex: 1,
    alignSelf: 'stretch',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 24,
    padding: 20,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border-strong) 72%, transparent)',
    borderRadius: 12,
    background:
      'color-mix(in srgb, var(--pudding-chat-surface) 78%, transparent)',
    backdropFilter: 'blur(18px)',
  },
  statusLine: {
    display: 'flex',
    alignItems: 'center',
    gap: 9,
    fontSize: 13,
    fontWeight: 650,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--pudding-chat-success)',
    boxShadow:
      '0 0 0 4px color-mix(in srgb, var(--pudding-chat-success) 14%, transparent)',
  },
  statusCaption: {
    marginTop: 8,
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
    lineHeight: 1.6,
  },
  statusMetric: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 16,
  },
  statusMetricValue: {
    fontSize: 32,
    lineHeight: 1,
    fontWeight: 720,
  },
  statusMetricLabel: {
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: 12,
    marginTop: 14,
    '@media (max-width: 900px)': {
      gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    },
    '@media (max-width: 520px)': { gridTemplateColumns: '1fr' },
  },
  statCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    minHeight: 92,
    padding: '17px 18px',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 12,
    background: 'var(--pudding-chat-surface)',
  },
  statIcon: {
    display: 'grid',
    placeItems: 'center',
    flex: '0 0 auto',
    width: 38,
    height: 38,
    borderRadius: 10,
    color: 'var(--pudding-chat-accent)',
    background: 'var(--pudding-chat-accent-soft)',
    fontSize: 17,
  },
  statValue: { fontSize: 22, lineHeight: 1.1, fontWeight: 700 },
  statLabel: {
    marginTop: 5,
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.25fr) minmax(300px, 0.75fr)',
    gap: 14,
    marginTop: 14,
    '@media (max-width: 980px)': { gridTemplateColumns: '1fr' },
  },
  section: {
    minWidth: 0,
    padding: 22,
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 14,
    background: 'var(--pudding-chat-surface)',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 16,
  },
  sectionTitle: { margin: 0, fontSize: 16, lineHeight: 1.35, fontWeight: 680 },
  sectionDescription: {
    margin: '4px 0 0',
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
  },
  workspaceList: { display: 'grid', gap: 9 },
  workspaceRow: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: 16,
    padding: '13px 14px',
    color: 'inherit',
    textAlign: 'left',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 10,
    background: 'var(--pudding-chat-surface-muted)',
    cursor: 'pointer',
    transition:
      'border-color 150ms ease, transform 150ms ease, background 150ms ease',
    '&:hover': {
      borderColor:
        'color-mix(in srgb, var(--pudding-chat-accent) 38%, var(--pudding-chat-border))',
      background:
        'color-mix(in srgb, var(--pudding-chat-accent) 5%, var(--pudding-chat-surface-muted))',
      transform: 'translateY(-1px)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-chat-accent)',
      outlineOffset: 2,
    },
  },
  workspaceTitleLine: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  workspaceTitle: { fontSize: 14, fontWeight: 650 },
  workspaceMeta: {
    marginTop: 5,
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
  },
  workspaceArrow: { color: 'var(--pudding-chat-text-subtle)', fontSize: 14 },
  quickGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 9,
  },
  quickEntry: {
    minHeight: 116,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    padding: 15,
    color: 'inherit',
    textAlign: 'left',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 10,
    background: 'var(--pudding-chat-surface-muted)',
    cursor: 'pointer',
    transition: 'border-color 150ms ease, background 150ms ease',
    '&:hover': {
      borderColor:
        'color-mix(in srgb, var(--pudding-chat-accent) 38%, var(--pudding-chat-border))',
      background:
        'color-mix(in srgb, var(--pudding-chat-accent) 5%, var(--pudding-chat-surface-muted))',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-chat-accent)',
      outlineOffset: 2,
    },
  },
  quickIcon: { color: 'var(--pudding-chat-accent)', fontSize: 18 },
  quickTitle: { display: 'block', fontSize: 13, fontWeight: 650 },
  quickDescription: {
    display: 'block',
    marginTop: 4,
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 11,
    lineHeight: 1.55,
  },
  emptyState: {
    padding: '28px 18px',
    textAlign: 'center',
    color: 'var(--pudding-chat-text-subtle)',
    border: '1px dashed var(--pudding-chat-border-strong)',
    borderRadius: 10,
  },
}));
