using PuddingCode.Abstractions;
using PuddingCode.Platform;

namespace PuddingRuntime.Services.Skills;

/// <summary>Adapts self-evolution writes to the same filesystem/index service consumed by SkillEnforcer.</summary>
public sealed class AgentSkillEvolutionStore(AgentSkillFileService skillFileService)
    : IAgentSkillEvolutionStore
{
    public async Task<AgentSkillEvolutionDocument?> GetAsync(
        string agentInstanceId,
        string skillId,
        CancellationToken ct = default)
    {
        try
        {
            var record = await skillFileService.GetAsync(agentInstanceId, skillId, ct);
            return await ToDocumentAsync(agentInstanceId, record, ct);
        }
        catch (DirectoryNotFoundException)
        {
            return null;
        }
    }

    public async Task<IReadOnlyList<AgentSkillEvolutionDocument>> ListAutoGeneratedAsync(
        string agentInstanceId,
        CancellationToken ct = default)
    {
        var records = await skillFileService.ListAsync(agentInstanceId, ct);
        var documents = new List<AgentSkillEvolutionDocument>();
        foreach (var record in records.Where(record =>
                     record.Manifest.Tags.Contains("auto-generated", StringComparer.OrdinalIgnoreCase)))
        {
            documents.Add(await ToDocumentAsync(agentInstanceId, record, ct));
        }

        return documents;
    }

    public async Task<AgentSkillEvolutionDocument> CreateAsync(
        string agentInstanceId,
        AgentSkillEvolutionWriteRequest request,
        CancellationToken ct = default)
    {
        var record = await skillFileService.CreateAsync(agentInstanceId, new AgentSkillCreateRequest
        {
            SkillId = request.SkillId,
            Name = request.Name,
            Version = request.Version,
            Description = request.Description,
            Tags = request.Tags,
            Keywords = request.Keywords,
            SkillMarkdown = request.Markdown,
        }, ct);
        return await ToDocumentAsync(agentInstanceId, record, ct);
    }

    public async Task<AgentSkillEvolutionDocument> UpdateAsync(
        string agentInstanceId,
        string skillId,
        AgentSkillEvolutionWriteRequest request,
        CancellationToken ct = default)
    {
        var record = await skillFileService.UpdateAsync(agentInstanceId, skillId, new AgentSkillUpdateRequest
        {
            Name = request.Name,
            Version = request.Version,
            Description = request.Description,
            Tags = request.Tags,
            Keywords = request.Keywords,
            SkillMarkdown = request.Markdown,
        }, ct);
        return await ToDocumentAsync(agentInstanceId, record, ct);
    }

    private async Task<AgentSkillEvolutionDocument> ToDocumentAsync(
        string agentInstanceId,
        AgentSkillRecord record,
        CancellationToken ct)
    {
        var markdown = await skillFileService.ReadFileAsync(
            agentInstanceId,
            record.Manifest.SkillId,
            relativePath: null,
            ct);
        return new AgentSkillEvolutionDocument
        {
            SkillId = record.Manifest.SkillId,
            Name = record.Manifest.Name,
            Version = record.Manifest.Version,
            Description = record.Manifest.Description,
            Tags = record.Manifest.Tags,
            Keywords = record.Manifest.Keywords,
            Markdown = markdown.Content,
        };
    }
}
