namespace PuddingCode.Abstractions;

/// <summary>
/// Business-level image generation entrypoint. Generated bytes are persisted as
/// workspace-scoped vision artifacts before the result is returned.
/// </summary>
public interface IImageGenerationService
{
    Task<ImageGenerationResult> GenerateAsync(
        ImageGenerationRequest request,
        CancellationToken ct = default);
}

/// <summary>Provider adapter for one vendor image generation protocol.</summary>
public interface IImageGenerationProvider
{
    bool CanHandle(string providerId);

    Task<ImageGenerationProviderResult> GenerateAsync(
        ImageGenerationProviderRequest request,
        CancellationToken ct = default);
}

public sealed record ImageGenerationRequest
{
    public required string WorkspaceId { get; init; }
    public required string Prompt { get; init; }
    public string? ProviderId { get; init; }
    public string? ModelId { get; init; }
    /// <summary>
    /// Provider-neutral routing hint: default, precision, or sequence.
    /// Explicit provider/model selection takes precedence.
    /// </summary>
    public string Mode { get; init; } = "default";
    public string Size { get; init; } = "2K";
    public bool Watermark { get; init; } = true;
    public string OutputFormat { get; init; } = "png";
    public string OptimizePromptMode { get; init; } = "standard";
    public bool EnableWebSearch { get; init; }
    public int ImageCount { get; init; } = 1;
    public IReadOnlyList<string> ReferenceArtifactIds { get; init; } = [];
    /// <summary>
    /// Optional stable operation key used by terminal reply hooks. Ordinary
    /// Agent tool calls intentionally omit it and create a fresh artifact.
    /// </summary>
    public string? IdempotencyKey { get; init; }
}

public sealed record ImageGenerationProviderRequest
{
    public required string Endpoint { get; init; }
    public required string ApiKey { get; init; }
    public required string ModelId { get; init; }
    public required string Prompt { get; init; }
    public required string Size { get; init; }
    public bool Watermark { get; init; }
    public string OutputFormat { get; init; } = "png";
    public string OptimizePromptMode { get; init; } = "standard";
    public bool EnableWebSearch { get; init; }
    public int ImageCount { get; init; } = 1;
    public IReadOnlyList<string> InputImages { get; init; } = [];
}

public sealed record ImageGenerationProviderImage
{
    public required byte[] Content { get; init; }
    public required string MimeType { get; init; }
    public int? Width { get; init; }
    public int? Height { get; init; }
}

public sealed record ImageGenerationProviderResult
{
    public required IReadOnlyList<ImageGenerationProviderImage> Images { get; init; }
}

public sealed record ImageGenerationArtifact
{
    public required string ArtifactId { get; init; }
    public required string MimeType { get; init; }
    public int? Width { get; init; }
    public int? Height { get; init; }
}

public sealed record ImageGenerationResult
{
    public required IReadOnlyList<ImageGenerationArtifact> Artifacts { get; init; }
    public required string ProviderId { get; init; }
    public required string ModelId { get; init; }

    public string ArtifactId => Artifacts[0].ArtifactId;
    public string MimeType => Artifacts[0].MimeType;
    public int? Width => Artifacts[0].Width;
    public int? Height => Artifacts[0].Height;
}
