using PuddingCode.Platform;

namespace PuddingCode.Abstractions;

/// <summary>Provides successful, workspace- and agent-scoped tool trajectories for Skill extraction.</summary>
public interface ISkillEvolutionTrajectorySource
{
    Task<IReadOnlyList<SkillEvolutionTrajectory>> GetRecentSuccessfulAsync(
        string workspaceId,
        string agentInstanceId,
        int limit,
        CancellationToken ct = default);
}

/// <summary>Persists self-evolved skills through the runtime Agent Skill storage contract.</summary>
public interface IAgentSkillEvolutionStore
{
    Task<AgentSkillEvolutionDocument?> GetAsync(
        string agentInstanceId,
        string skillId,
        CancellationToken ct = default);

    Task<IReadOnlyList<AgentSkillEvolutionDocument>> ListAutoGeneratedAsync(
        string agentInstanceId,
        CancellationToken ct = default);

    Task<AgentSkillEvolutionDocument> CreateAsync(
        string agentInstanceId,
        AgentSkillEvolutionWriteRequest request,
        CancellationToken ct = default);

    Task<AgentSkillEvolutionDocument> UpdateAsync(
        string agentInstanceId,
        string skillId,
        AgentSkillEvolutionWriteRequest request,
        CancellationToken ct = default);
}

