using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using PuddingCode.Configuration;
using PuddingCode.Platform;
using PuddingPlatform.Data;
using PuddingPlatform.Data.Entities;
using PuddingRuntime.Services.Skills;

namespace PuddingRuntimeTests.Services;

[TestClass]
public sealed class SkillEvolutionServicesTests
{
    [TestMethod]
    public async Task EvolutionStore_CreateAndUpdate_ShouldFeedSkillEnforcerThroughRuntimeIndex()
    {
        using var temp = new TempDataRoot();
        var files = new AgentSkillFileService(temp.Paths);
        var store = new AgentSkillEvolutionStore(files);
        var enforcer = new SkillEnforcerService(files, NullLogger<SkillEnforcerService>.Instance);

        await store.CreateAsync("agent-1", new AgentSkillEvolutionWriteRequest
        {
            SkillId = "create-github-pr",
            Name = "Create GitHub PR",
            Version = "1.0.0",
            Description = "Create and verify a GitHub pull request.",
            Tags = ["auto-generated", "self-evolution"],
            Keywords = ["create github pr", "github_create_pr"],
            Markdown = "# Create GitHub PR\n\n1. Create the PR.\n2. Verify it.",
        });

        var injected = await enforcer.EnforceAsync("agent-1", "Please create GitHub PR for this branch");
        Assert.IsNotNull(injected);
        Assert.AreEqual("create-github-pr", injected.Single().SkillId);

        var skill = (await store.ListAutoGeneratedAsync("agent-1")).Single();
        StringAssert.Contains(skill.Markdown, "Verify it");

        await store.UpdateAsync("agent-1", skill.SkillId, new AgentSkillEvolutionWriteRequest
        {
            SkillId = skill.SkillId,
            Name = skill.Name,
            Version = "1.0.1",
            Description = skill.Description,
            Tags = skill.Tags,
            Keywords = skill.Keywords,
            Markdown = skill.Markdown + "\n3. Report the PR URL.",
        });

        var updated = await store.GetAsync("agent-1", skill.SkillId);
        Assert.IsNotNull(updated);
        Assert.AreEqual("1.0.1", updated.Version);
        StringAssert.Contains(updated.Markdown, "Report the PR URL");

        var disabled = await store.SetEnabledAsync("agent-1", skill.SkillId, enabled: false);
        Assert.IsFalse(disabled.Enabled);
        Assert.IsNull(await enforcer.EnforceAsync(
            "agent-1",
            "Please create GitHub PR for this branch"));
    }

    [TestMethod]
    public async Task TrajectorySource_ShouldReturnOnlyVerifiedWorkspaceAndAgentScopedToolChains()
    {
        await using var scope = await PlatformScope.CreateAsync();
        await using (var db = scope.Factory.CreateDbContext())
        {
            db.ChatMessages.Add(new ChatMessageEntity
            {
                MessageId = "message-1",
                SessionId = "session-1",
                WorkspaceId = "workspace-1",
                AgentInstanceId = "agent-1",
                Role = "user",
                Content = "Create a GitHub PR",
                CreatedAt = 1,
            });
            db.ChatExecutionCommands.AddRange(
                Command("command-1", "batch-1", "workspace-1", "session-1", "turn-1", "agent-1", "message-1"),
                Command("command-2", "batch-2", "workspace-1", "session-2", "turn-2", "agent-2", "message-2"),
                Command("command-3", "batch-3", "workspace-1", "session-3", "turn-3", "agent-1", "message-3"));
            db.ConversationEvents.AddRange(
                Event(1, "command-1", "session-1", "turn-1", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"github_list_branches\",\"arguments\":\"{}\"}"),
                Event(2, "command-1", "session-1", "turn-1", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"github_list_branches\",\"exitCode\":0,\"output\":\"main\",\"error\":null}"),
                Event(3, "command-1", "session-1", "turn-1", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"github_create_pr\",\"arguments\":\"{\\\"base\\\":\\\"main\\\"}\"}"),
                Event(4, "command-1", "session-1", "turn-1", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"github_create_pr\",\"exitCode\":0,\"output\":\"PR #123\",\"error\":null}"),
                Event(5, "command-3", "session-3", "turn-3", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"github_list_branches\",\"arguments\":\"{}\"}"),
                Event(6, "command-3", "session-3", "turn-3", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"github_list_branches\",\"output\":\"main\",\"error\":null}"),
                Event(7, "command-3", "session-3", "turn-3", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"github_create_pr\",\"arguments\":\"{}\"}"),
                Event(8, "command-3", "session-3", "turn-3", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"github_create_pr\",\"output\":\"PR #999\",\"error\":null}"));
            await db.SaveChangesAsync();
        }

        var source = new ConversationSkillEvolutionTrajectorySource(
            scope.Factory,
            NullLogger<ConversationSkillEvolutionTrajectorySource>.Instance);

        var result = await source.GetRecentSuccessfulAsync("workspace-1", "agent-1", 5);

        Assert.AreEqual(1, result.Count);
        Assert.AreEqual("Create a GitHub PR", result[0].Goal);
        CollectionAssert.AreEqual(
            new[] { "github_list_branches", "github_create_pr" },
            result[0].Steps.Select(step => step.ToolName).ToArray());
        Assert.AreEqual(0, (await source.GetRecentSuccessfulAsync("workspace-1", "agent-2", 5)).Count);
    }

    [TestMethod]
    public async Task TrajectorySource_ShouldScanPastRecentCommandsWithoutReusableToolChains()
    {
        await using var scope = await PlatformScope.CreateAsync();
        await using (var db = scope.Factory.CreateDbContext())
        {
            db.ChatMessages.Add(new ChatMessageEntity
            {
                MessageId = "message-reusable",
                SessionId = "session-reusable",
                WorkspaceId = "workspace-1",
                AgentInstanceId = "agent-1",
                Role = "user",
                Content = "Run the reusable workflow",
                CreatedAt = 1,
            });

            var reusable = Command(
                "command-reusable",
                "batch-reusable",
                "workspace-1",
                "session-reusable",
                "turn-reusable",
                "agent-1",
                "message-reusable");
            reusable.CreatedAt = 1;
            reusable.CompletedAt = 2;
            db.ChatExecutionCommands.Add(reusable);

            for (var i = 0; i < 5; i++)
            {
                var recent = Command(
                    $"command-recent-{i}",
                    $"batch-recent-{i}",
                    "workspace-1",
                    $"session-recent-{i}",
                    $"turn-recent-{i}",
                    "agent-1",
                    $"message-recent-{i}");
                recent.CreatedAt = 100 + i;
                recent.CompletedAt = 200 + i;
                db.ChatExecutionCommands.Add(recent);
            }

            db.ConversationEvents.AddRange(
                Event(1, "command-reusable", "session-reusable", "turn-reusable", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"step_one\",\"arguments\":\"{}\"}"),
                Event(2, "command-reusable", "session-reusable", "turn-reusable", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"step_one\",\"exitCode\":0,\"output\":\"ok\",\"error\":null}"),
                Event(3, "command-reusable", "session-reusable", "turn-reusable", ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"step_two\",\"arguments\":\"{}\"}"),
                Event(4, "command-reusable", "session-reusable", "turn-reusable", ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"step_two\",\"exitCode\":0,\"output\":\"ok\",\"error\":null}"));
            await db.SaveChangesAsync();
        }

        var source = new ConversationSkillEvolutionTrajectorySource(
            scope.Factory,
            NullLogger<ConversationSkillEvolutionTrajectorySource>.Instance);

        var result = await source.GetRecentSuccessfulAsync("workspace-1", "agent-1", 1);

        Assert.AreEqual(1, result.Count);
        Assert.AreEqual("turn-reusable", result[0].TurnId);
        CollectionAssert.AreEqual(
            new[] { "step_one", "step_two" },
            result[0].Steps.Select(step => step.ToolName).ToArray());
    }

    [TestMethod]
    public async Task TrajectorySource_ShouldExcludeBenchmarkRunsFromLearning()
    {
        await using var scope = await PlatformScope.CreateAsync();
        await using (var db = scope.Factory.CreateDbContext())
        {
            db.ChatMessages.Add(new ChatMessageEntity
            {
                MessageId = "message-benchmark",
                SessionId = "session-benchmark",
                WorkspaceId = "workspace-1",
                AgentInstanceId = "agent-1",
                Role = "user",
                Content = "Generate the benchmark artifact",
                CreatedAt = 1,
            });
            var command = Command(
                "command-benchmark",
                "batch-benchmark",
                "workspace-1",
                "session-benchmark",
                "turn-benchmark",
                "agent-1",
                "message-benchmark");
            command.MetadataJson = "{\"source\":\"benchmark_runner\",\"excludeFromLearning\":\"true\"}";
            db.ChatExecutionCommands.Add(command);
            db.ConversationEvents.AddRange(
                Event(1, command.CommandId, command.SessionId, command.TurnId, ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"step_one\",\"arguments\":\"{}\"}"),
                Event(2, command.CommandId, command.SessionId, command.TurnId, ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"step_one\",\"exitCode\":0,\"output\":\"ok\",\"error\":null}"),
                Event(3, command.CommandId, command.SessionId, command.TurnId, ConversationEventTypes.ToolCallRequested,
                    "{\"name\":\"step_two\",\"arguments\":\"{}\"}"),
                Event(4, command.CommandId, command.SessionId, command.TurnId, ConversationEventTypes.ToolCallCompleted,
                    "{\"name\":\"step_two\",\"exitCode\":0,\"output\":\"ok\",\"error\":null}"));
            await db.SaveChangesAsync();
        }

        var source = new ConversationSkillEvolutionTrajectorySource(
            scope.Factory,
            NullLogger<ConversationSkillEvolutionTrajectorySource>.Instance);

        var result = await source.GetRecentSuccessfulAsync("workspace-1", "agent-1", 5);

        Assert.AreEqual(0, result.Count);
    }

    private static ChatExecutionCommandEntity Command(
        string commandId,
        string batchId,
        string workspaceId,
        string sessionId,
        string turnId,
        string agentInstanceId,
        string userMessageId) => new()
    {
        CommandId = commandId,
        BatchId = batchId,
        WorkspaceId = workspaceId,
        SessionId = sessionId,
        TurnId = turnId,
        AgentInstanceId = agentInstanceId,
        UserMessageId = userMessageId,
        Status = "succeeded",
        CreatedAt = 1,
        CompletedAt = 2,
    };

    private static ConversationEventEntity Event(
        long sequence,
        string commandId,
        string conversationId,
        string turnId,
        string type,
        string payload) => new()
    {
        ConversationId = conversationId,
        Sequence = sequence,
        EventId = $"event-{sequence}",
        WorkspaceId = "workspace-1",
        TurnId = turnId,
        CommandId = commandId,
        Type = type,
        Payload = payload,
        OccurredAt = DateTimeOffset.UtcNow.ToString("O"),
        CommittedAt = DateTimeOffset.UtcNow.ToString("O"),
    };

    private sealed class TempDataRoot : IDisposable
    {
        public TempDataRoot()
        {
            Root = Path.Combine(Path.GetTempPath(), "pudding-skill-evolution-tests", Guid.NewGuid().ToString("N"));
            Paths = PuddingDataPaths.FromRoot(Root);
        }

        public string Root { get; }
        public PuddingDataPaths Paths { get; }

        public void Dispose()
        {
            if (Directory.Exists(Root))
                Directory.Delete(Root, recursive: true);
        }
    }

    private sealed class PlatformScope(
        SqliteConnection connection,
        IDbContextFactory<PlatformDbContext> factory) : IAsyncDisposable
    {
        public IDbContextFactory<PlatformDbContext> Factory { get; } = factory;

        public static async Task<PlatformScope> CreateAsync()
        {
            var connection = new SqliteConnection("DataSource=:memory:");
            await connection.OpenAsync();
            var options = new DbContextOptionsBuilder<PlatformDbContext>()
                .UseSqlite(connection)
                .Options;
            var factory = new TestPlatformDbContextFactory(options);
            await using var db = factory.CreateDbContext();
            await db.Database.EnsureCreatedAsync();
            return new PlatformScope(connection, factory);
        }

        public ValueTask DisposeAsync() => connection.DisposeAsync();
    }

    private sealed class TestPlatformDbContextFactory(DbContextOptions<PlatformDbContext> options)
        : IDbContextFactory<PlatformDbContext>
    {
        public PlatformDbContext CreateDbContext() => new(options);
    }
}
