// ── composer styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const useComposerStyles = createStyles(({ token }) => ({
  composerSurface: {
    position: 'sticky' as const,
    bottom: 0,
    background: 'var(--pudding-chat-surface)',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 22,
    padding: '10px 12px',
    boxShadow: '0 12px 34px rgba(92, 74, 58, 0.08)',
    zIndex: 10,
    margin: '0 8px 8px',
    overflow: 'visible' as const,
    transition:
      'background 180ms ease, border-color 180ms ease, box-shadow 180ms ease',
    /* ink-line */
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      bottom: -1,
      left: '20%',
      width: '36%',
      height: 2,
      borderRadius: 1,
      background:
        'color-mix(in srgb, var(--accent-purple, #8b5cf6) 24%, transparent)',
      opacity: 0,
      transform: 'translateX(-10px)',
      transition: 'opacity 220ms ease, transform 220ms ease',
      pointerEvents: 'none' as const,
    },
    '&[data-active="true"]': {
      borderColor:
        'color-mix(in srgb, var(--pudding-chat-accent) 30%, var(--pudding-chat-border-strong))',
      boxShadow: '0 14px 38px rgba(92, 74, 58, 0.1)',
    },
    '&[data-active="true"]::after': {
      opacity: 1,
      transform: 'translateX(0)',
    },
    '&[data-error="true"]': {
      borderColor: 'color-mix(in srgb, #c4944c 40%, transparent)',
      boxShadow: '0 2px 10px rgba(196, 148, 76, 0.06)',
    },
    '&[data-active="true"][data-error="true"]::after': {
      opacity: 0,
    },
    /* prefers-reduced-motion: 禁用 ink-line 动画，只保留颜色 */
    '@media (prefers-reduced-motion: reduce)': {
      '&::after': {
        transition: 'none',
        opacity: 0,
      },
    },
  },
  composerStatusLine: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minHeight: 18,
    marginBottom: 4,
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
  },
  composerQueue: {
    margin: '4px 0 8px',
    padding: 6,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border) 76%, transparent)',
    borderRadius: 7,
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 62%, transparent)',
  },
  composerQueueHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 20,
    marginBottom: 5,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--pudding-chat-text)',
  },
  composerQueueList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 5,
    maxHeight: 'min(24vh, 128px)',
    overflowY: 'auto' as const,
    scrollbarGutter: 'stable',
  },
  composerQueueItem: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 6,
    alignItems: 'start',
    padding: 5,
    borderRadius: 6,
    background: 'var(--pudding-chat-surface)',
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border) 62%, transparent)',
    '&[data-status="steering_pending"]': {
      borderColor:
        'color-mix(in srgb, #c8943d 48%, var(--pudding-chat-border))',
      background:
        'color-mix(in srgb, #fff7e6 54%, var(--pudding-chat-surface))',
    },
    '&[data-status="steering_injected"]': {
      borderColor:
        'color-mix(in srgb, #4f8f64 52%, var(--pudding-chat-border))',
      background:
        'color-mix(in srgb, #edf8f0 62%, var(--pudding-chat-surface))',
    },
    '&[data-status="steering_failed"]': {
      borderColor:
        'color-mix(in srgb, #b85656 52%, var(--pudding-chat-border))',
      background:
        'color-mix(in srgb, #fff1f1 58%, var(--pudding-chat-surface))',
    },
  },
  composerQueueInput: {
    fontSize: 12,
    lineHeight: 1.5,
    resize: 'none' as const,
  },
  composerQueuePreview: {
    minHeight: 30,
    maxHeight: 42,
    padding: '5px 8px',
    borderRadius: 6,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border) 58%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 72%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 12,
    lineHeight: 1.45,
    overflow: 'hidden',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical' as const,
    WebkitLineClamp: 2,
    wordBreak: 'break-word' as const,
  },
  composerQueueActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 2,
    minHeight: 28,
  },
  composerQueueStatus: {
    maxWidth: 118,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
    '&[data-status="steering_pending"]': {
      color: '#8b651e',
      fontWeight: 600,
    },
    '&[data-status="steering_injected"]': {
      color: '#2f7650',
      fontWeight: 700,
    },
    '&[data-status="steering_failed"]': {
      color: '#a64242',
      fontWeight: 700,
    },
  },
  composerQueueMeta: {
    gridColumn: '1 / -1',
    minHeight: 15,
    fontSize: 11,
    lineHeight: 1.35,
    color: 'var(--pudding-chat-text-muted)',
  },
  composerQueueError: {
    gridColumn: '1 / -1',
    fontSize: 11,
    color: '#a64242',
  },
  composerStatusDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerCapsuleBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    minHeight: 58,
  },
  composerRecording: {
    borderColor: '#8b5cf6 !important' as any,
    boxShadow:
      '0 0 16px rgba(124,58,237,0.3), 0 0 40px rgba(124,58,237,0.1) !important' as any,
    animation: 'puddingComposerRecording 1.2s ease-in-out infinite',
  },
  composerToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    minHeight: 34,
  },
  composerToolbarLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  composerToolbarRight: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    flexShrink: 0,
  },
  composerToolbarButton: {
    width: 34,
    minWidth: 34,
    height: 34,
    minHeight: 34,
    padding: 0,
    border: 'none',
    borderRadius: '50%',
    background: 'transparent',
    color: 'var(--pudding-chat-text-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    lineHeight: 1,
    cursor: 'pointer' as const,
    transition: 'background 140ms ease, color 140ms ease, opacity 140ms ease',
    '&:hover:not(:disabled)': {
      color: 'var(--pudding-chat-text)',
      background: 'color-mix(in srgb, var(--earth-brown) 7%, transparent)',
    },
    '&:disabled': {
      cursor: 'not-allowed' as const,
      opacity: 0.38,
    },
    '&:focus-visible': {
      outline:
        '2px solid color-mix(in srgb, var(--pudding-chat-accent) 50%, transparent)',
      outlineOffset: 2,
    },
  },
  composerToolbarStatus: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
    flexWrap: 'wrap' as const,
  },
  composerUiTestButton: {
    appearance: 'none' as const,
    minHeight: 22,
    padding: '0 7px',
    borderRadius: 11,
    border: '1px solid color-mix(in srgb, var(--earth-brown) 8%, transparent)',
    background: 'transparent',
    color: 'var(--earth-brown)',
    opacity: 0.42,
    fontSize: 11,
    lineHeight: '20px',
    fontFamily: 'inherit',
    cursor: 'pointer' as const,
    transition: 'opacity 140ms ease, background 140ms ease',
    '&:hover': {
      opacity: 0.62,
      background: 'color-mix(in srgb, var(--earth-brown) 5%, transparent)',
    },
  },
  composerPreferenceButton: {
    minWidth: 58,
    height: 34,
    padding: '0 9px',
    border: 'none',
    borderRadius: 17,
    background: 'transparent',
    color: 'var(--pudding-chat-text-muted)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    fontSize: 13,
    cursor: 'pointer' as const,
    transition: 'background 140ms ease, color 140ms ease',
    '&:hover': {
      color: 'var(--pudding-chat-text)',
      background: 'color-mix(in srgb, var(--earth-brown) 7%, transparent)',
    },
  },
  composerPreferenceMenu: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    minWidth: 112,
    padding: 4,
  },
  composerPreferenceItem: {
    height: 32,
    padding: '0 10px',
    border: 'none',
    borderRadius: 7,
    background: 'transparent',
    color: 'var(--pudding-chat-text)',
    fontSize: 13,
    textAlign: 'left' as const,
    cursor: 'pointer' as const,
    '&:hover': {
      background: 'color-mix(in srgb, var(--earth-brown) 7%, transparent)',
    },
    '&[data-active="true"]': {
      background:
        'color-mix(in srgb, var(--pudding-chat-accent) 12%, transparent)',
      color: 'var(--pudding-chat-accent)',
      fontWeight: 600,
    },
  },
  composerSendButton: {
    width: 34,
    minWidth: 34,
    height: 34,
    minHeight: 34,
    padding: 0,
    border: 'none',
    borderRadius: '50%',
    background: 'var(--pudding-chat-accent)',
    color: '#fff',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    lineHeight: 1,
    cursor: 'pointer' as const,
    transition:
      'opacity 140ms ease, background 140ms ease, transform 140ms ease',
    '&:hover:not(:disabled)': {
      transform: 'translateY(-1px)',
      background: 'color-mix(in srgb, var(--pudding-chat-accent) 88%, #1d1b24)',
    },
    '&:disabled': {
      cursor: 'not-allowed' as const,
      opacity: 0.36,
      transform: 'none',
    },
    '&[data-loading="true"]': {
      background:
        'color-mix(in srgb, var(--pudding-warning, #c4944c) 84%, #1d1b24)',
      opacity: 1,
    },
    '&:focus-visible': {
      outline:
        '2px solid color-mix(in srgb, var(--pudding-chat-accent) 45%, transparent)',
      outlineOffset: 2,
    },
  },
  composerVoiceMode: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 10,
  },
  composerVoiceHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 34,
  },
  composerVoiceTitle: {
    fontSize: 13,
    color: 'var(--pudding-chat-text-muted)',
    fontWeight: 600,
  },
  composerModeSwitch: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    minHeight: 28,
    padding: 2,
    margin: '2px 0 8px',
    borderRadius: 7,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border) 78%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 64%, transparent)',
  },
  composerModeButton: {
    minWidth: 70,
    height: 24,
    padding: '0 10px',
    border: 'none',
    borderRadius: 5,
    background: 'transparent',
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 12,
    lineHeight: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    cursor: 'pointer' as const,
    transition: 'background 140ms ease, color 140ms ease',
    '&:hover': {
      color: 'var(--pudding-chat-text)',
      background:
        'color-mix(in srgb, var(--pudding-chat-text) 5%, transparent)',
    },
    '&[data-active="true"]': {
      color: 'var(--pudding-chat-text)',
      background: 'var(--pudding-chat-surface)',
      boxShadow: '0 1px 3px rgba(92, 64, 42, 0.07)',
    },
  },
  composerRow: {
    display: 'grid',
    gridTemplateColumns: '124px minmax(0, 1fr) 36px',
    columnGap: 6,
    alignItems: 'end',
    minHeight: 32,
    overflow: 'visible' as const,
  },
  composerToolArea: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    alignSelf: 'end',
    width: 124,
    minWidth: 124,
    overflow: 'visible' as const,
  },
  composerActionArea: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    alignSelf: 'end',
    width: 36,
    minWidth: 36,
    minHeight: 32,
    overflow: 'visible' as const,
  },
  composerIconButton: {
    width: 32,
    minWidth: 32,
    height: 32,
    minHeight: 32,
    padding: 0,
    opacity: 0.58,
    border: 'none',
    background: 'transparent',
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
    borderRadius: 8,
  },
  composerTextarea: {
    display: 'block',
    width: '100%',
    border: 'none',
    background: 'transparent',
    color: 'var(--pudding-chat-text)',
    boxShadow: 'none',
    resize: 'none' as const,
    fontSize: 14,
    lineHeight: 1.55,
    padding: '4px 8px 0',
    outline: 'none',
    minWidth: 0,
    minHeight: 30,
    maxHeight: 132,
    overflowY: 'auto' as const,
    '&:focus': {
      boxShadow: 'none',
    },
    '&::placeholder': {
      color: 'var(--pudding-chat-text-subtle)',
    },
  },
  composerMenu: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    padding: '4px 0',
    minWidth: 220,
  },
  composerMenuSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 1,
    padding: '4px 0',
  },
  composerMenuSectionTitle: {
    padding: '4px 12px 6px',
    fontSize: 11,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontWeight: 500,
    opacity: 0.6,
    userSelect: 'none' as const,
  },
  composerMenuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    height: 36,
    padding: '0 12px',
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--pudding-text, #1d1b24)',
    fontSize: 13,
    cursor: 'pointer' as const,
    transition: 'background 0.15s',
    textAlign: 'left' as const,
    '&:hover:not(:disabled)': {
      background:
        'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: -2,
    },
    '& .anticon': {
      fontSize: 14,
      flexShrink: 0,
    },
  },
  composerMenuItemDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed' as const,
  },
  composerMenuComingSoon: {
    marginLeft: 'auto',
    fontSize: 10,
    color: 'var(--pudding-text-muted, #756b5f)',
    opacity: 0.5,
  },
  composerMenuValue: {
    marginLeft: 'auto',
    fontSize: 12,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontVariantNumeric: 'tabular-nums' as const,
  },
  composerFeedbackStrip: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    gap: 4,
    minHeight: 22,
    padding: 0,
    cursor: 'pointer' as const,
    userSelect: 'none' as const,
    '&:hover .composerFeedbackLabel': {
      opacity: 0.8,
    },
  },
  composerFeedbackSep: {
    display: 'none',
  },
  composerFeedbackItem: {
    position: 'relative' as const,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    minHeight: 22,
    padding: '0 7px',
    borderRadius: 11,
    border: '1px solid color-mix(in srgb, var(--earth-brown) 7%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 68%, transparent)',
    overflow: 'hidden',
    transition: 'background 0.15s, border-color 0.2s, box-shadow 0.2s',
    '&:hover': {
      background:
        'color-mix(in srgb, var(--earth-brown, #5c4a3a) 5%, transparent)',
    },
    '&[data-active="true"]': {
      borderColor: 'color-mix(in srgb, var(--earth-brown) 12%, transparent)',
    },
  },
  composerFeedbackProgress: {
    position: 'absolute' as const,
    left: 0,
    top: 0,
    bottom: 0,
    minWidth: 2,
    borderRadius: 'inherit',
    backgroundImage: 'var(--composer-feedback-fill)',
    boxShadow: 'inset -1px 0 0 rgba(255,255,255,0.34)',
    pointerEvents: 'none' as const,
    transition: 'width 0.45s ease, background 0.2s ease',
    zIndex: 0,
  },
  composerFeedbackDot: {
    position: 'relative' as const,
    zIndex: 1,
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerFeedbackLabel: {
    position: 'relative' as const,
    zIndex: 1,
    fontSize: 11,
    color: 'var(--earth-brown, #5c4a3a)',
    opacity: 0.42,
    whiteSpace: 'nowrap' as const,
    transition: 'opacity 0.15s',
    '&[data-active="true"]': {
      opacity: 0.7,
    },
  },
  composerStatusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    cursor: 'pointer' as const,
    minHeight: 22,
    borderRadius: 11,
    border: '1px solid color-mix(in srgb, var(--earth-brown) 12%, transparent)',
    padding: '0 7px',
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
    transition: 'background 0.15s',
    '&:hover': {
      background:
        'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: 1,
    },
  },
  composerStatusDetails: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    padding: '4px 0',
    minWidth: 220,
    maxWidth: 280,
  },
  composerStatusDetailsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 12px 8px',
    borderBottom:
      '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 10%, transparent)',
    marginBottom: 4,
  },
  composerStatusDetailsDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerStatusDetailsTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--pudding-text, #1d1b24)',
  },
  composerStatusDetailsGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    padding: '0 12px',
  },
  composerStatusDetailsGroupTitle: {
    fontSize: 10,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontWeight: 500,
    opacity: 0.5,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: 2,
  },
  composerStatusDetailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    minHeight: 22,
  },
  composerStatusDetailLabel: {
    fontSize: 12,
    color: 'var(--pudding-text-muted, #756b5f)',
    flexShrink: 0,
  },
  composerStatusDetailValue: {
    fontSize: 12,
    color: 'var(--pudding-text, #1d1b24)',
    fontVariantNumeric: 'tabular-nums' as const,
    textAlign: 'right' as const,
  },
  composerStatusDetailsDevEntry: {
    borderTop:
      '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 10%, transparent)',
    padding: '6px 12px 2px',
    marginTop: 4,
  },
  composerStatusDetailsDevButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    height: 32,
    padding: '0 8px',
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--pudding-text-muted, #756b5f)',
    fontSize: 12,
    cursor: 'pointer' as const,
    transition: 'background 0.15s',
    textAlign: 'left' as const,
    '&:hover': {
      background:
        'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
      color: 'var(--pudding-text, #1d1b24)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: -2,
    },
    '& .anticon': {
      fontSize: 12,
    },
  },
}));
