// ── message styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const useMessageStyles = createStyles(({ token }) => ({
  timelineRegion: {
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  turnContainer: {
    position: 'relative' as const,
    display: 'flex',
    gap: 12,
    width: '100%',
  },
  turnTimeline: {
    width: 2,
    borderRadius: 2,
    background: token.colorBorderSecondary,
    marginTop: 4,
    marginBottom: 4,
    flexShrink: 0,
  },
  turnBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    width: '100%',
  },
  messageContent: {
    maxWidth: '74%',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    position: 'relative' as const,
    fontSize: 14,
    color: 'var(--text-primary)',
    '&:hover .message-actions': {
      opacity: 1,
      transform: 'translateY(0)',
      pointerEvents: 'auto' as const,
    },
  },
  messageActions: {
    opacity: 0,
    transform: 'translateY(3px)',
    pointerEvents: 'none' as const,
    transition: 'opacity 200ms ease-in-out, transform 200ms ease-in-out',
    '& .ant-btn-text': { color: 'var(--earth-brown)' },
    '& .ant-btn-text:hover': { color: 'var(--accent-purple)' },
    '& .ant-btn-dangerous': { color: 'var(--earth-brown)' },
    '& .ant-btn-dangerous:hover': { color: token.colorError },
  },
  messageMeta: { display: 'flex', alignItems: 'center', gap: 8, minHeight: 20 },
  timeText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  timeDivider: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '2px 0',
    color: 'var(--earth-brown)',
    opacity: 0.7,
    fontSize: 12,
    '&::before, &::after': {
      content: '""',
      flex: 1,
      height: 1,
      background: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    },
  },
  groupContent: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  userGroupContent: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end' as const,
  },
  systemRow: { justifyContent: 'center' },

  // ── 开发者模式面板 ───────────────────────────────────────────
  messageRow: {
    display: 'flex',
    width: '100%',
    marginBottom: 2,
    padding: '8px 0',
    contain: 'layout paint style',
    contentVisibility: 'auto' as const,
    containIntrinsicSize: '120px',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAgent: {
    justifyContent: 'flex-start',
  },
  messageRowGrouped: {
    marginTop: -4,
  },
  messageRowHeartbeat: {
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  agentMessageContainer: {
    position: 'relative' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    maxWidth: '82%',
    minWidth: 0,
    // P0-2: 为气泡外绝对定位的操作按钮预留落点，长气泡/贴底场景防裁切
    paddingBottom: 8,
  },
  userMessageContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end',
    maxWidth: '70%',
    minWidth: 0,
  },
  messageModalityBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    height: 18,
    padding: '0 6px',
    borderRadius: 5,
    border: '1px solid var(--pudding-chat-border)',
    color: 'var(--pudding-chat-text-muted)',
    background:
      'color-mix(in srgb, var(--pudding-chat-accent) 8%, transparent)',
    fontSize: 11,
    lineHeight: '16px',
  },
  messageActionsNew: {
    position: 'absolute' as const,
    left: 4,
    bottom: -26,
    zIndex: 3,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 4px',
    borderRadius: 6,
    background: 'color-mix(in srgb, var(--soft-white) 90%, transparent)',
    boxShadow: '0 4px 12px rgba(30, 22, 12, 0.08)',
    opacity: 0,
    pointerEvents: 'none' as const,
    transform: 'translateY(-2px)',
    transition: 'opacity 180ms ease',
  },
  messageActionsVisible: {
    // P0-2: hover 中操作按钮全亮（原 0.6 半透明）
    opacity: 1,
    pointerEvents: 'auto' as const,
    // P0-2: 键盘 Tab 聚焦到任一按钮时保持整组可见（focus-within）
    '&:focus-within': {
      opacity: 1,
      pointerEvents: 'auto' as const,
    },
  },
  messageActionBtn: {
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: 'transparent',
    borderRadius: 4,
    cursor: 'pointer' as const,
    color: 'var(--earth-brown)',
    opacity: 1,
    fontSize: 13,
    transition: 'opacity 120ms ease, background 120ms ease',
    '&:hover': {
      opacity: 1,
      background: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    },
    // P0-2: 键盘焦点显影（对齐 focusViewRowHeader 的 focus-visible 写法）
    '&:focus-visible': {
      outline:
        '2px solid color-mix(in srgb, var(--accent-purple) 45%, transparent)',
      outlineOffset: 1,
    },
  },
  messageActionBtnDanger: {
    '&:hover': {
      color: '#ef4444',
      opacity: 1,
    },
  },
  // ── P1-4 用户消息操作按钮 + 失败态 ───────────────────────────
  userMessageActionsHost: {
    position: 'relative' as const,
  },
  userMessageActions: {
    position: 'absolute' as const,
    right: 4,
    top: 'calc(100% + 2px)',
    zIndex: 3,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 4px',
    borderRadius: 6,
    background: 'color-mix(in srgb, var(--soft-white) 90%, transparent)',
    boxShadow: '0 4px 12px rgba(30, 22, 12, 0.08)',
    opacity: 0,
    pointerEvents: 'none' as const,
    transform: 'translateY(-2px)',
    transition: 'opacity 180ms ease, transform 180ms ease',
    '&:focus-within': {
      opacity: 1,
      pointerEvents: 'auto' as const,
    },
  },
  userMessageActionsVisible: {
    opacity: 1,
    pointerEvents: 'auto' as const,
    transform: 'translateY(0)',
  },
  userErrorText: {
    fontSize: 11,
    lineHeight: '16px',
    color: 'var(--pudding-status-error)',
    marginTop: 2,
    paddingRight: 4,
    opacity: 0.9,
  },
  timeline: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    position: 'relative' as const,
    paddingLeft: 16,
    animation: 'fadeIn 200ms ease-out',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 4,
      top: 0,
      bottom: 0,
      width: 2,
      background: 'var(--earth-brown, rgba(120,100,80,0.10))',
      borderRadius: 1,
    },
  },
  timelineUserMsg: {
    fontSize: 14,
    color: 'var(--text-primary)',
    padding: '4px 0 8px',
    position: 'relative' as const,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 6,
      height: 6,
      borderRadius: '50%',
      background: 'var(--accent-purple, #7c3aed)',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  timelineUserLabel: {
    display: 'inline-block',
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.6,
    marginBottom: 2,
    marginRight: 8,
  },
  timelineNode: {
    position: 'relative' as const,
    padding: '6px 0 6px 12px',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 8,
      height: 8,
      borderRadius: '50%',
      border: '2px solid var(--neural-line, rgba(124,58,237,0.18))',
      background: 'var(--warm-beige)',
      zIndex: 1,
    },
  },
  timelineNodeThinking: {
    opacity: 0.65,
    fontStyle: 'italic',
    fontSize: 12,
    borderLeft: '2px solid var(--memory-glow, #A78BFA)',
  },
  timelineNodeTool: {
    borderLeft: '2px solid var(--tool-signal, #22D3EE)',
  },
  timelineNodeToolRunning: {
    borderLeft: '2px solid var(--earth-brown)',
    '&::before': {
      animation: 'signalFlow 2s linear infinite',
      background: 'var(--earth-brown)',
      boxShadow:
        '0 0 6px color-mix(in srgb, var(--misty-blue) 40%, transparent)',
      backgroundSize: '200% 100%',
    },
  },
  timelineNodeToolDone: {
    borderLeftColor: 'var(--success-signal, #22C55E)',
  },
  timelineNodeToolFailed: {
    borderLeftColor: 'var(--error-signal, #EF4444)',
  },
  timelineNodeAnswer: {
    borderLeft: 'none',
    padding: '8px 0 8px 0',
    marginLeft: -12,
  },
  timelineAnswerBlock: {
    background: 'var(--soft-white)',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 12,
    padding: '14px 18px',
    fontSize: 15,
    lineHeight: 1.7,
    color: 'var(--text-primary)',
  },
  timelineNodeAppear: {
    animation: 'nodeAppear 300ms ease-out',
  },
  messageViewportControls: {
    position: 'fixed' as const,
    right: 24,
    bottom: 112,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    pointerEvents: 'none' as const,
    zIndex: 30,
    '@media (max-width: 768px)': {
      right: 16,
      bottom: 96,
    },
  },
  messageViewportControlButton: {
    pointerEvents: 'auto' as const,
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  messageViewportScrollArea: {
    scrollbarGutter: 'stable' as const,
    overscrollBehavior: 'contain' as const,
    scrollbarWidth: 'thin' as const,
  },
}));

// ── P2#8 Focus view（单行折叠模式）──────────────────────────
// Focus view 把每个 turn 折叠成一行（隐藏工具调用 / thinking），点击展开查看完整内容。
// 对齐 Claude VS Code Focus view：运行中显示当前工具/活动。
export const useFocusViewStyles = createStyles(() => ({
  focusViewToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
    padding: '2px 16px 4px',
  },
  focusViewToggle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    minHeight: 22,
    padding: '2px 8px',
    borderRadius: 999,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-border) 70%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 22%, transparent)',
  },
  focusViewToggleLabel: {
    fontSize: 11,
    lineHeight: '18px',
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.8,
    whiteSpace: 'nowrap' as const,
    userSelect: 'none' as const,
  },
  focusViewRow: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
  },
  focusViewRowHeader: {
    appearance: 'none' as const,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    minHeight: 28,
    padding: '2px 8px',
    border: '1px solid transparent',
    borderRadius: 8,
    background: 'transparent',
    cursor: 'pointer' as const,
    textAlign: 'left' as const,
    fontFamily: 'inherit',
    transition: 'background 150ms ease, border-color 150ms ease',
    '&:hover': {
      background:
        'color-mix(in srgb, var(--pudding-chat-surface-muted) 42%, transparent)',
      borderColor:
        'color-mix(in srgb, var(--pudding-chat-accent) 12%, transparent)',
    },
    '&:focus-visible': {
      outline:
        '2px solid color-mix(in srgb, var(--accent-purple) 40%, transparent)',
      outlineOffset: 1,
    },
  },
  focusViewRowHeaderRunning: {
    background: 'color-mix(in srgb, var(--accent-purple) 5%, transparent)',
  },
  focusViewRowHeaderError: {
    background: 'color-mix(in srgb, #ef4444 5%, transparent)',
  },
  focusViewRowUserAvatar: {
    width: 22,
    height: 22,
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    background: 'var(--sky-soft)',
    color: 'var(--earth-brown)',
    fontSize: 10,
    fontWeight: 500,
  },
  focusViewRowName: {
    fontSize: 12,
    color: 'var(--pudding-chat-text)',
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  focusViewRowSummary: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    lineHeight: '18px',
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.78,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  focusViewRowSummaryRunning: {
    color: 'var(--accent-purple)',
    opacity: 0.92,
  },
  focusViewRowSummaryError: {
    color: '#ef4444',
    opacity: 0.92,
  },
  focusViewRowTime: {
    fontSize: 11,
    lineHeight: '18px',
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.55,
    whiteSpace: 'nowrap' as const,
    flexShrink: 0,
  },
  focusViewRowCaret: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: 10,
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.5,
    flexShrink: 0,
  },
  focusViewRowContent: {
    width: '100%',
    padding: '2px 0 4px 8px',
  },
}));
