// ── message styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const useMessageStyles = createStyles(({ token }) => ({
  timelineRegion: {
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
  },
  turnContainer: {
    position: 'relative' as const,
    display: 'flex',
    gap: 12,
    width: '100%',
  },
  turnTimeline: {
    width: 2,
    borderRadius: 2,
    background: token.colorBorderSecondary,
    marginTop: 4,
    marginBottom: 4,
    flexShrink: 0,
  },
  turnBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    width: '100%',
  },
  messageContent: {
    maxWidth: '74%',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    position: 'relative' as const,
    fontSize: 14,
    color: 'var(--text-primary)',
    '&:hover .message-actions': {
      opacity: 1,
      transform: 'translateY(0)',
      pointerEvents: 'auto' as const,
    },
  },
  messageActions: {
    opacity: 0,
    transform: 'translateY(3px)',
    pointerEvents: 'none' as const,
    transition: 'opacity 200ms ease-in-out, transform 200ms ease-in-out',
    '& .ant-btn-text': { color: 'var(--earth-brown)' },
    '& .ant-btn-text:hover': { color: 'var(--accent-purple)' },
    '& .ant-btn-dangerous': { color: 'var(--earth-brown)' },
    '& .ant-btn-dangerous:hover': { color: token.colorError },
  },
  messageMeta: { display: 'flex', alignItems: 'center', gap: 8, minHeight: 20 },
  timeText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  timeDivider: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    margin: '2px 0',
    color: 'var(--earth-brown)',
    opacity: 0.7,
    fontSize: 12,
    '&::before, &::after': {
      content: '""',
      flex: 1,
      height: 1,
      background: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    },
  },
  groupContent: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  userGroupContent: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end' as const,
  },
  systemRow: { justifyContent: 'center' },

  // ── 开发者模式面板 ───────────────────────────────────────────
  messageStream: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    padding: '8px 0',
  },
  messageRow: {
    display: 'flex',
    width: '100%',
    marginBottom: 2,
    contain: 'layout paint style',
    contentVisibility: 'auto' as const,
    containIntrinsicSize: '120px',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAgent: {
    justifyContent: 'flex-start',
  },
  messageRowGrouped: {
    marginTop: -4,
  },
  messageRowHeartbeat: {
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  agentMessageContainer: {
    position: 'relative' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    maxWidth: '82%',
    minWidth: 0,
  },
  userMessageContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end',
    maxWidth: '70%',
    minWidth: 0,
  },
  messageModalityBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    height: 18,
    padding: '0 6px',
    borderRadius: 5,
    border: '1px solid var(--pudding-chat-border)',
    color: 'var(--pudding-chat-text-muted)',
    background:
      'color-mix(in srgb, var(--pudding-chat-accent) 8%, transparent)',
    fontSize: 11,
    lineHeight: '16px',
  },
  messageActionsNew: {
    position: 'absolute' as const,
    left: 4,
    bottom: -26,
    zIndex: 3,
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 4px',
    borderRadius: 6,
    background: 'color-mix(in srgb, var(--soft-white) 90%, transparent)',
    boxShadow: '0 4px 12px rgba(30, 22, 12, 0.08)',
    opacity: 0,
    pointerEvents: 'none' as const,
    transform: 'translateY(-2px)',
    transition: 'opacity 180ms ease',
  },
  messageActionsVisible: {
    opacity: 0.6,
    pointerEvents: 'auto' as const,
  },
  messageActionBtn: {
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: 'transparent',
    borderRadius: 4,
    cursor: 'pointer' as const,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    fontSize: 13,
    transition: 'opacity 120ms ease, background 120ms ease',
    '&:hover': {
      opacity: 1,
      background: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    },
  },
  messageActionBtnDanger: {
    '&:hover': {
      color: '#ef4444',
      opacity: 1,
    },
  },
  timeline: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    position: 'relative' as const,
    paddingLeft: 16,
    animation: 'fadeIn 200ms ease-out',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 4,
      top: 0,
      bottom: 0,
      width: 2,
      background: 'var(--earth-brown, rgba(120,100,80,0.10))',
      borderRadius: 1,
    },
  },
  timelineUserMsg: {
    fontSize: 14,
    color: 'var(--text-primary)',
    padding: '4px 0 8px',
    position: 'relative' as const,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 6,
      height: 6,
      borderRadius: '50%',
      background: 'var(--accent-purple, #7c3aed)',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  timelineUserLabel: {
    display: 'inline-block',
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.6,
    marginBottom: 2,
    marginRight: 8,
  },
  timelineNode: {
    position: 'relative' as const,
    padding: '6px 0 6px 12px',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 8,
      height: 8,
      borderRadius: '50%',
      border: '2px solid var(--neural-line, rgba(124,58,237,0.18))',
      background: 'var(--warm-beige)',
      zIndex: 1,
    },
  },
  timelineNodeThinking: {
    opacity: 0.65,
    fontStyle: 'italic',
    fontSize: 12,
    borderLeft: '2px solid var(--memory-glow, #A78BFA)',
  },
  timelineNodeTool: {
    borderLeft: '2px solid var(--tool-signal, #22D3EE)',
  },
  timelineNodeToolRunning: {
    borderLeft: '2px solid var(--earth-brown)',
    '&::before': {
      animation: 'signalFlow 2s linear infinite',
      background: 'var(--earth-brown)',
      boxShadow:
        '0 0 6px color-mix(in srgb, var(--misty-blue) 40%, transparent)',
      backgroundSize: '200% 100%',
    },
  },
  timelineNodeToolDone: {
    borderLeftColor: 'var(--success-signal, #22C55E)',
  },
  timelineNodeToolFailed: {
    borderLeftColor: 'var(--error-signal, #EF4444)',
  },
  timelineNodeAnswer: {
    borderLeft: 'none',
    padding: '8px 0 8px 0',
    marginLeft: -12,
  },
  timelineAnswerBlock: {
    background: 'var(--soft-white)',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 12,
    padding: '14px 18px',
    fontSize: 15,
    lineHeight: 1.7,
    color: 'var(--text-primary)',
  },
  timelineNodeAppear: {
    animation: 'nodeAppear 300ms ease-out',
  },
  messageViewportControls: {
    position: 'fixed' as const,
    right: 24,
    bottom: 112,
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    pointerEvents: 'none' as const,
    zIndex: 30,
    '@media (max-width: 768px)': {
      right: 16,
      bottom: 96,
    },
  },
  messageViewportControlButton: {
    pointerEvents: 'auto' as const,
    width: 40,
    height: 40,
    borderRadius: 8,
  },
  messageViewportScrollArea: {
    scrollbarGutter: 'stable' as const,
    overscrollBehavior: 'contain' as const,
    scrollbarWidth: 'thin' as const,
  },
}));
