// ── panel styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const usePanelStyles = createStyles(() => ({
  indicatorWrapper: { position: 'relative' as const },
  indicatorRing: {
    cursor: 'pointer',
    width: 34,
    height: 34,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'all 0.2s',
    '&:hover': {
      background: 'rgba(139,92,246,0.12)',
      boxShadow: '0 0 12px rgba(139,92,246,0.2)',
    },
  },
  indicatorPulse: { animation: 'indicatorPulse 2s ease-in-out infinite' },
  indicatorSpin: { animation: 'indicatorSpin 3s linear infinite' },
  '@keyframes indicatorPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.9, transform: 'scale(1.3)' },
  },
  '@keyframes indicatorSpin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  indicatorPopup: {
    position: 'fixed',
    bottom: 100,
    right: 24,
    width: 270,
    background: 'rgba(30,30,40,0.96)',
    backdropFilter: 'blur(20px)',
    borderRadius: 12,
    padding: 16,
    color: '#e2e8f0',
    border: '1px solid rgba(139,92,246,0.3)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(139,92,246,0.15)',
    zIndex: 1000,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  popupHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  popupTitle: { fontWeight: 600, fontSize: 13 },
  popupStatus: { display: 'flex', alignItems: 'center', gap: 6, opacity: 0.8 },
  popupDot: { width: 6, height: 6, borderRadius: '50%' },
  popupBody: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  popupRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  popupValue: { fontFamily: 'monospace', fontSize: 11, opacity: 0.8 },
  popupProgress: {
    height: 3,
    borderRadius: 2,
    background: 'rgba(255,255,255,0.1)',
    margin: '4px 0',
  },
  popupProgressBar: {
    height: '100%',
    borderRadius: 2,
    transition: 'width 0.5s ease',
  },
  popupWarning: {
    color: '#f97316',
    fontSize: 11,
    marginTop: 4,
    padding: '6px 8px',
    background: 'rgba(249,115,22,0.1)',
    borderRadius: 6,
  },
  agentRunMonitor: {
    width: '100%',
    maxWidth: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  currentActivityPanel: {
    position: 'relative' as const,
    isolation: 'isolate' as const,
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
    boxSizing: 'border-box' as const,
    border: '1px solid',
    borderColor:
      'color-mix(in srgb, var(--accent-purple) 10%, var(--earth-brown) 5%)',
    borderLeft:
      '2px solid color-mix(in srgb, var(--accent-purple) 28%, var(--earth-brown) 8%)',
    borderRadius: 10,
    borderTopLeftRadius: 5,
    background:
      'linear-gradient(135deg, color-mix(in srgb, var(--accent-purple) 2%, var(--soft-white)), var(--soft-white) 54%)',
    boxShadow: '0 3px 12px rgba(63, 38, 95, 0.04), 0 1px 3px rgba(0,0,0,0.035)',
    padding: '11px 16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 7,
    contain: 'paint',
  },
  currentActivityToneRunning: {
    borderLeftColor:
      'color-mix(in srgb, var(--accent-purple) 38%, var(--earth-brown) 6%)',
  },
  currentActivityToneSuccess: {
    borderLeftColor: 'color-mix(in srgb, #6f8f72 58%, var(--earth-brown))',
  },
  currentActivityToneError: {
    borderLeftColor: 'color-mix(in srgb, #c15f45 62%, var(--earth-brown))',
  },
  currentActivityHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 20,
    flexWrap: 'wrap' as const,
  },
  currentActivityDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
  },
  currentActivityTitle: {
    minWidth: 0,
    color: 'var(--pudding-chat-text)',
    fontSize: 13,
    fontWeight: 500,
    lineHeight: '18px',
    wordBreak: 'break-word' as const,
  },
  currentActivityStatus: {
    minHeight: 18,
    padding: '0 6px',
    borderRadius: 5,
    background: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 11,
    lineHeight: '18px',
    whiteSpace: 'nowrap' as const,
  },
  currentActivityElapsed: {
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
    fontSize: 11,
    lineHeight: '18px',
    fontVariantNumeric: 'tabular-nums' as const,
    whiteSpace: 'nowrap' as const,
  },
  currentActivitySubject: {
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: 'break-word' as const,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
    cursor: 'default',
  },
  currentActivityPreview: {
    margin: 0,
    padding: '7px 9px',
    maxHeight: '9.6em',
    overflow: 'hidden' as const,
    overflowX: 'hidden' as const,
    borderRadius: 6,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 9%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 42%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontSize: 11,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    cursor: 'default',
  },
  inboundAgentCard: {
    margin: '0 0 12px 28px',
    maxWidth: '80%',
    border:
      '1.5px solid color-mix(in srgb, var(--accent-purple) 28%, transparent)',
    borderRadius: 10,
    background:
      'color-mix(in srgb, var(--accent-purple) 6%, var(--soft-white))',
    overflow: 'hidden',
    transition: 'background 200ms ease',
  },
  inboundAgentCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--accent-purple)',
    borderBottom:
      '1px solid color-mix(in srgb, var(--accent-purple) 12%, transparent)',
    background: 'color-mix(in srgb, var(--accent-purple) 4%, transparent)',
  },
  inboundAgentCardIcon: {
    fontSize: 14,
    lineHeight: 1,
  },
  inboundAgentCardLabel: {
    color: 'var(--text-muted)',
    fontWeight: 400,
  },
  inboundAgentCardBody: {
    padding: '10px 12px',
    fontSize: 13,
    lineHeight: 1.6,
    color: 'var(--text-primary)',
    wordBreak: 'break-word' as const,
    whiteSpace: 'pre-wrap' as const,
  },
  // ── 压缩卡（CompactionCard）──
  // 为什么单独一套形态：压缩既不是工具调用也不是模型思考，通用活动卡只给一行标题，
  // 用户既看不出它在做什么，也无法分辨「是不是真的在跑」（用户反馈 2026-09-19：
  // 压缩卡片显示效果乱）。这里只表达运行/完成/未完成三种有事实支撑的状态，
  // 用不定量扫描条表示「还在跑」，不伪造百分比进度，也不编造阶段名。
  compactionCard: {
    position: 'relative' as const,
    width: '100%',
    minWidth: 0,
    boxSizing: 'border-box' as const,
    border: '1px solid',
    borderColor:
      'color-mix(in srgb, var(--accent-purple) 12%, var(--earth-brown) 6%)',
    borderLeft:
      '2px solid color-mix(in srgb, var(--accent-purple) 34%, var(--earth-brown) 8%)',
    borderRadius: 10,
    borderTopLeftRadius: 5,
    background:
      'linear-gradient(135deg, color-mix(in srgb, var(--accent-purple) 3%, var(--soft-white)), var(--soft-white) 58%)',
    boxShadow: '0 3px 12px rgba(63, 38, 95, 0.045), 0 1px 3px rgba(0,0,0,0.035)',
    padding: '11px 14px 10px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    overflow: 'hidden' as const,
  },
  compactionCardSuccess: {
    borderLeftColor: 'color-mix(in srgb, #6f8f72 58%, var(--earth-brown))',
  },
  compactionCardInterrupted: {
    borderLeftColor: 'color-mix(in srgb, #c15f45 62%, var(--earth-brown))',
  },
  compactionCardSettle: {
    animation: 'compactionCardSettle 320ms ease-out both',
    '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
  },
  compactionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  /** 「收敛」字形：三根逐根塌缩的竖条，替代通用转圈，语义是「内容被压紧」。 */
  compactionGlyph: {
    display: 'inline-flex',
    alignItems: 'flex-end',
    gap: 2,
    height: 14,
    flexShrink: 0,
  },
  compactionGlyphBar: {
    width: 3,
    borderRadius: 1,
    background:
      'color-mix(in srgb, var(--accent-purple) 55%, var(--earth-brown))',
    transformOrigin: 'bottom' as const,
    animation: 'compactionGlyph 1.5s ease-in-out infinite',
    '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
  },
  compactionGlyphBarStatic: { animation: 'none' },
  compactionTitle: {
    minWidth: 0,
    flex: 1,
    color: 'var(--pudding-chat-text)',
    fontSize: 13,
    fontWeight: 600,
    lineHeight: '18px',
    wordBreak: 'break-word' as const,
  },
  compactionElapsed: {
    flexShrink: 0,
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.75,
    fontSize: 11,
    lineHeight: '18px',
    fontVariantNumeric: 'tabular-nums' as const,
    whiteSpace: 'nowrap' as const,
  },
  compactionRail: {
    position: 'relative' as const,
    height: 3,
    borderRadius: 2,
    overflow: 'hidden' as const,
    background: 'color-mix(in srgb, var(--earth-brown) 9%, transparent)',
  },
  compactionRailFill: {
    position: 'absolute' as const,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 2,
    background: 'color-mix(in srgb, #6f8f72 42%, transparent)',
    animation: 'compactionSettle 420ms ease-out both',
    '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
  },
  compactionRailSweep: {
    position: 'absolute' as const,
    top: 0,
    bottom: 0,
    left: 0,
    width: '38%',
    borderRadius: 2,
    background:
      'linear-gradient(90deg, transparent, color-mix(in srgb, var(--accent-purple) 46%, transparent) 45%, color-mix(in srgb, var(--accent-purple) 62%, transparent) 60%, transparent)',
    animation: 'compactionSweep 1.5s cubic-bezier(0.4, 0, 0.2, 1) infinite',
    '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
  },
  compactionHint: {
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 12,
    lineHeight: 1.55,
    wordBreak: 'break-word' as const,
  },
  compactionReason: {
    margin: 0,
    padding: '6px 9px',
    maxHeight: '6.4em',
    overflow: 'hidden' as const,
    borderRadius: 6,
    border:
      '1px solid color-mix(in srgb, #c15f45 18%, transparent)',
    background: 'color-mix(in srgb, #c15f45 6%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontSize: 11,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  /** 上下文面板「压缩」行的运行态呼吸点。 */
  compactionStatusDot: {
    display: 'inline-block',
    width: 6,
    height: 6,
    borderRadius: '50%',
    marginRight: 5,
    verticalAlign: 'middle',
    background: 'color-mix(in srgb, var(--accent-purple) 60%, transparent)',
    animation: 'compactionBreathe 1.8s ease-in-out infinite',
    '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
  },
  compactionStatusDotStatic: {
    display: 'inline-block',
    width: 6,
    height: 6,
    borderRadius: '50%',
    marginRight: 5,
    verticalAlign: 'middle',
    background: 'color-mix(in srgb, #6f8f72 55%, transparent)',
  },
  '@keyframes compactionSweep': {
    '0%': { transform: 'translateX(-100%)' },
    '100%': { transform: 'translateX(263%)' },
  },
  '@keyframes compactionGlyph': {
    '0%, 100%': { transform: 'scaleY(0.42)' },
    '50%': { transform: 'scaleY(1)' },
  },
  '@keyframes compactionBreathe': {
    '0%, 100%': { opacity: 0.45, transform: 'scale(0.9)' },
    '50%': { opacity: 1, transform: 'scale(1.15)' },
  },
  '@keyframes compactionSettle': {
    '0%': { opacity: 0, transform: 'scaleX(0.2)' },
    '100%': { opacity: 1, transform: 'scaleX(1)' },
  },
  '@keyframes compactionCardSettle': {
    '0%': { opacity: 0.4, transform: 'translateY(2px)' },
    '100%': { opacity: 1, transform: 'translateY(0)' },
  },
}));
