// ── panel styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const usePanelStyles = createStyles(({ token }) => ({
  indicatorWrapper: { position: 'relative' as const },
  indicatorRing: {
    cursor: 'pointer',
    width: 34,
    height: 34,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    transition: 'all 0.2s',
    '&:hover': {
      background: 'rgba(139,92,246,0.12)',
      boxShadow: '0 0 12px rgba(139,92,246,0.2)',
    },
  },
  indicatorPulse: { animation: 'indicatorPulse 2s ease-in-out infinite' },
  indicatorSpin: { animation: 'indicatorSpin 3s linear infinite' },
  '@keyframes indicatorPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.9, transform: 'scale(1.3)' },
  },
  '@keyframes indicatorSpin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  indicatorPopup: {
    position: 'fixed',
    bottom: 100,
    right: 24,
    width: 270,
    background: 'rgba(30,30,40,0.96)',
    backdropFilter: 'blur(20px)',
    borderRadius: 12,
    padding: 16,
    color: '#e2e8f0',
    border: '1px solid rgba(139,92,246,0.3)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(139,92,246,0.15)',
    zIndex: 1000,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  popupHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  popupTitle: { fontWeight: 600, fontSize: 13 },
  popupStatus: { display: 'flex', alignItems: 'center', gap: 6, opacity: 0.8 },
  popupDot: { width: 6, height: 6, borderRadius: '50%' },
  popupBody: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  popupRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  popupValue: { fontFamily: 'monospace', fontSize: 11, opacity: 0.8 },
  popupProgress: {
    height: 3,
    borderRadius: 2,
    background: 'rgba(255,255,255,0.1)',
    margin: '4px 0',
  },
  popupProgressBar: {
    height: '100%',
    borderRadius: 2,
    transition: 'width 0.5s ease',
  },
  popupWarning: {
    color: '#f97316',
    fontSize: 11,
    marginTop: 4,
    padding: '6px 8px',
    background: 'rgba(249,115,22,0.1)',
    borderRadius: 6,
  },
  currentActivityPanel: {
    width: '100%',
    minWidth: 'min(560px, calc(100vw - 128px))',
    maxWidth: 'min(720px, 100%)',
    boxSizing: 'border-box' as const,
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderLeft:
      '2px solid color-mix(in srgb, var(--accent-purple) 24%, var(--earth-brown))',
    borderRadius: 8,
    borderTopLeftRadius: 4,
    background: 'var(--soft-white)',
    padding: '10px 14px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 7,
    contain: 'paint',
    '@media (max-width: 720px)': {
      minWidth: 0,
    },
  },
  currentActivityToneRunning: {
    borderLeftColor:
      'color-mix(in srgb, var(--accent-purple) 28%, var(--earth-brown))',
  },
  currentActivityToneSuccess: {
    borderLeftColor: 'color-mix(in srgb, #6f8f72 58%, var(--earth-brown))',
  },
  currentActivityToneError: {
    borderLeftColor: 'color-mix(in srgb, #c15f45 62%, var(--earth-brown))',
  },
  currentActivityHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 20,
    flexWrap: 'wrap' as const,
  },
  currentActivityDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
  },
  currentActivityTitle: {
    minWidth: 0,
    color: 'var(--pudding-chat-text)',
    fontSize: 13,
    fontWeight: 500,
    lineHeight: '18px',
    wordBreak: 'break-word' as const,
  },
  currentActivityStatus: {
    minHeight: 18,
    padding: '0 6px',
    borderRadius: 5,
    background: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 11,
    lineHeight: '18px',
    whiteSpace: 'nowrap' as const,
  },
  currentActivityElapsed: {
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
    fontSize: 11,
    lineHeight: '18px',
    fontVariantNumeric: 'tabular-nums' as const,
    whiteSpace: 'nowrap' as const,
  },
  currentActivitySubject: {
    color: 'var(--pudding-chat-text-muted)',
    fontSize: 12,
    lineHeight: 1.5,
    wordBreak: 'break-word' as const,
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    overflow: 'hidden',
    cursor: 'default',
  },
  currentActivityPreview: {
    margin: 0,
    padding: '7px 9px',
    maxHeight: '9.6em',
    overflow: 'hidden' as const,
    overflowX: 'hidden' as const,
    borderRadius: 6,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 9%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 42%, transparent)',
    color: 'var(--pudding-chat-text-muted)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    fontSize: 11,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    cursor: 'default',
  },
  inboundAgentCard: {
    margin: '0 0 12px 28px',
    maxWidth: '80%',
    border:
      '1.5px solid color-mix(in srgb, var(--accent-purple) 28%, transparent)',
    borderRadius: 10,
    background:
      'color-mix(in srgb, var(--accent-purple) 6%, var(--soft-white))',
    overflow: 'hidden',
    transition: 'background 200ms ease',
  },
  inboundAgentCardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--accent-purple)',
    borderBottom:
      '1px solid color-mix(in srgb, var(--accent-purple) 12%, transparent)',
    background: 'color-mix(in srgb, var(--accent-purple) 4%, transparent)',
  },
  inboundAgentCardIcon: {
    fontSize: 14,
    lineHeight: 1,
  },
  inboundAgentCardLabel: {
    color: 'var(--text-muted)',
    fontWeight: 400,
  },
  inboundAgentCardBody: {
    padding: '10px 12px',
    fontSize: 13,
    lineHeight: 1.6,
    color: 'var(--text-primary)',
    wordBreak: 'break-word' as const,
    whiteSpace: 'pre-wrap' as const,
  },
}));
