// ── process styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const useProcessStyles = createStyles(({ token }) => ({
  thinkingStepCard: {
    background: 'color-mix(in srgb, var(--earth-brown) 8%, var(--soft-white))',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 20%, transparent)',
  },
  thinkingStepHeader: { cursor: 'pointer', userSelect: 'none' as const },
  thinkingStepMessage: {
    fontStyle: 'italic',
    color: token.colorTextSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 60%, transparent)',
    borderRadius: 6,
    padding: '6px 8px',
  },
  thinkingPulse: { animation: 'thinkingPulse 1500ms ease-in-out infinite' },
  processSummaryRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 4px 0',
    cursor: 'pointer' as const,
    userSelect: 'none' as const,
    transition: 'opacity 200ms ease',
    '&:hover': {
      opacity: 0.8,
    },
  },
  processSummaryDot: {
    width: 4,
    height: 4,
    borderRadius: '50%',
    background: 'var(--earth-brown)',
    opacity: 0.3,
    flexShrink: 0,
  },
  processSummaryText: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    lineHeight: '16px',
  },
  processSummaryLink: {
    appearance: 'none' as const,
    border: 'none',
    background: 'transparent',
    padding: 0,
    margin: 0,
    fontFamily: 'inherit',
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.42,
    cursor: 'pointer' as const,
    lineHeight: '16px',
    fontWeight: 400,
    '&:hover': {
      opacity: 0.62,
      textDecoration: 'underline',
    },
  },
  processThinkingLabel: {
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.6,
    fontStyle: 'italic',
    lineHeight: '16px',
  },
  processRetryBtn: {
    fontSize: 11,
    color: '#ef4444',
    cursor: 'pointer' as const,
    opacity: 0.7,
    lineHeight: '16px',
    background: 'none',
    border: 'none',
    padding: 0,
    '&:hover': {
      opacity: 1,
      textDecoration: 'underline',
    },
  },
  processExpandedArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    marginTop: 4,
    padding: '8px 0 0 12px',
    borderLeft: '2px solid',
    borderColor:
      'color-mix(in srgb, var(--pudding-chat-text-muted) 18%, transparent)',
    maxHeight: 'min(460px, 52vh)',
    overflowY: 'auto' as const,
    paddingRight: 4,
    scrollbarGutter: 'stable' as const,
  },
  processTraceSummary: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 6,
    padding: '0 0 2px',
  },
  processTraceChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    minHeight: 20,
    padding: '1px 6px',
    borderRadius: 4,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 10%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 32%, transparent)',
    fontSize: 11,
    lineHeight: '16px',
  },
  processTraceChipLabel: {
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
  },
  processTraceChipValue: {
    color: 'var(--pudding-chat-text)',
    fontVariantNumeric: 'tabular-nums' as const,
  },
  processRound: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    padding: '6px 0 8px',
  },
  processRoundHeader: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
    minHeight: 20,
  },
  processRoundTitle: {
    fontSize: 12,
    color: 'var(--pudding-chat-text)',
    fontWeight: 600,
    lineHeight: '18px',
  },
  processRoundMeta: {
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
    lineHeight: '16px',
  },
  processThinkingPreview: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    padding: '8px 10px',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface) 88%, var(--pudding-chat-bg))',
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 12%, var(--pudding-chat-border))',
    borderRadius: 6,
  },
  processThinkingPreviewText: {
    fontSize: 12,
    color: 'var(--pudding-chat-text)',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  processThinkingRaw: {
    fontSize: 12,
    color: 'var(--pudding-chat-text)',
    lineHeight: 1.6,
    padding: '8px 10px',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface) 86%, var(--pudding-chat-bg))',
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 12%, var(--pudding-chat-border))',
    borderLeft:
      '2px solid color-mix(in srgb, var(--pudding-chat-text-muted) 26%, transparent)',
    borderRadius: 6,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  processCollapseLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
    cursor: 'pointer' as const,
    padding: '2px 4px',
    userSelect: 'none' as const,
    '&:hover': {
      opacity: 1,
    },
  },
  processItem: {
    fontSize: 12,
    color: 'var(--pudding-chat-text-muted)',
    lineHeight: 1.5,
    padding: '6px 8px',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 34%, transparent)',
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 8%, transparent)',
    borderRadius: 6,
  },
  processToolItem: {
    borderLeft:
      '2px solid color-mix(in srgb, var(--pudding-chat-text-muted) 24%, transparent)',
  },
  processItemHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minHeight: 18,
  },
  processItemName: {
    fontWeight: 500,
    color: 'var(--pudding-chat-text)',
  },
  processItemStatus: {
    fontSize: 10,
    padding: '1px 6px',
    borderRadius: 999,
    background:
      'color-mix(in srgb, var(--pudding-chat-text-muted) 8%, transparent)',
  },
  processItemStatusRunning: {
    color: 'var(--accent-purple)',
  },
  processItemStatusSuccess: {
    color: '#22c55e',
  },
  processItemStatusError: {
    color: '#ef4444',
  },
  processItemDetail: {
    fontSize: 11,
    color: 'var(--pudding-chat-text-muted)',
    marginTop: 6,
    padding: '5px 7px',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 52%, transparent)',
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 9%, transparent)',
    borderRadius: 4,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  processToolDetailBlocks: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    marginTop: 6,
  },
  processToolDetailBlock: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 3,
  },
  processToolDetailLabel: {
    fontSize: 10,
    lineHeight: '14px',
    color: 'var(--pudding-chat-text-muted)',
    opacity: 0.72,
  },
  processToolDetailPre: {
    margin: 0,
    fontSize: 11,
    lineHeight: 1.5,
    color: 'var(--pudding-chat-text-muted)',
    padding: '5px 7px',
    borderRadius: 4,
    border:
      '1px solid color-mix(in srgb, var(--pudding-chat-text-muted) 9%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-chat-surface-muted) 52%, transparent)',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    maxHeight: 220,
    overflowY: 'auto' as const,
  },
  processItemToggle: {
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.5,
    cursor: 'pointer' as const,
    padding: '2px 4px',
    '&:hover': {
      opacity: 0.8,
    },
  },
  processItemToggleButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    width: 'fit-content',
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.72,
    cursor: 'pointer' as const,
    border: 'none',
    background: 'transparent',
    padding: '2px 0',
    '&:hover': {
      opacity: 1,
      textDecoration: 'underline',
    },
  },
  collapsedSummary: {
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.55,
    cursor: 'pointer',
    transition: 'opacity 150ms',
    '&:hover': { opacity: 0.85 },
  },
  thinkingSummaryText: {
    fontSize: 12,
    color: 'var(--text-muted)',
    fontStyle: 'italic',
    opacity: 0.65,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: '100%',
    cursor: 'pointer',
  },
  thinkingExpandedText: {
    fontSize: 12,
    color: 'var(--text-muted)',
    fontStyle: 'italic',
    lineHeight: 1.5,
    padding: '6px 8px',
    background: 'color-mix(in srgb, var(--memory-glow) 6%, transparent)',
    borderRadius: 6,
    marginTop: 4,
    maxHeight: 200,
    overflowY: 'auto' as const,
  },
  toolSummaryRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
  },
  toolSummaryName: {
    fontWeight: 600,
    color: 'var(--tool-signal, #22D3EE)',
  },
  toolSummaryStatus: {
    fontSize: 11,
    opacity: 0.7,
  },
  toolSummaryDuration: {
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.6,
    marginLeft: 'auto',
  },
  toolSummaryResult: {
    fontSize: 11,
    color: 'var(--success-signal, #22C55E)',
    opacity: 0.8,
  },
  toolRetryBtn: {
    fontSize: 11,
    color: 'var(--error-signal, #EF4444)',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    ':hover': { textDecoration: 'underline' },
  },
  mainStatusLine: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '6px 12px',
    fontSize: 13,
    color: 'var(--earth-brown)',
    opacity: 0.7,
  },
  mainStatusDot: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    background: 'var(--accent-purple)',
    opacity: 0.5,
  },
  mainStatusDotActive: {
    animation: 'pulseDotActive 1.5s ease-in-out infinite',
  },
  '@keyframes pulseDotActive': {
    '0%, 100%': { opacity: 0.3 },
    '50%': { opacity: 0.8 },
  },
  completionSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 12px',
    fontSize: 12,
    color: 'var(--earth-brown)',
    opacity: 0.5,
  },
  viewProcessLink: {
    cursor: 'pointer',
    color: 'var(--accent-purple)',
    fontSize: 12,
    userSelect: 'none' as const,
    '&:hover': { opacity: 0.8 },
  },
  collapseProcessLink: {
    cursor: 'pointer',
    color: 'var(--accent-purple)',
    fontSize: 12,
    userSelect: 'none' as const,
    padding: '0 0 4px 0',
    '&:hover': { opacity: 0.8 },
  },
}));
