// ── reasoning styles ─────────────────────────────────
import { createStyles } from 'antd-style';

export const useReasoningStyles = createStyles(({ token }) => ({
  reasoningPanel: {
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(16px)',
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 8,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  reasoningHeader: {
    fontSize: 12,
    color: 'var(--earth-brown)',
    opacity: 0.7,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  reasoningBlock: {
    borderRadius: token.borderRadius,
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    padding: '6px 8px',
  },
  reasoningToggle: {
    color: token.colorPrimary,
    cursor: 'pointer',
    fontSize: 12,
    userSelect: 'none' as const,
  },
  reasoningText: {
    whiteSpace: 'pre-wrap' as const,
    color: token.colorTextSecondary,
    fontSize: 13,
    lineHeight: 1.6,
    marginTop: 6,
  },
  reasoningSummary: {
    fontSize: 12,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
    maxWidth: '100%',
  },
  reasoningStream: {
    whiteSpace: 'pre-wrap' as const,
    color:
      'color-mix(in srgb, var(--accent-purple) 60%, var(--text-secondary))',
    fontSize: 12,
    lineHeight: 1.5,
    padding: '8px 10px',
    maxHeight: 300,
    overflowY: 'auto' as const,
    fontStyle: 'italic',
    borderLeft: '2px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    marginTop: 4,
    animation: 'tokenStream 0.3s ease-out',
  },
  reasoningBlockTimeline: {
    marginBottom: 8,
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    borderLeft: '3px solid var(--accent-purple, #7c3aed)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  reasoningBlockContentTimeline: {
    padding: '8px 12px',
    fontSize: 12,
    fontStyle: 'italic',
    color: 'color-mix(in srgb, var(--accent-purple) 60%, #5c4a3a)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
  },
  reasoningFadeTimeline: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: 'linear-gradient(to bottom, transparent, #fafaf7)',
    pointerEvents: 'none' as const,
  },
  reasoningToggleTimeline: {
    padding: '4px 12px',
    fontSize: 11,
    color: 'var(--accent-purple)',
    cursor: 'pointer',
    borderTop: '1px solid rgba(124, 58, 237, 0.15)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
  },
  preAnswerThinkingText: {
    margin: '0 16px',
    padding: '8px 10px',
    borderLeft:
      '2px solid color-mix(in srgb, var(--accent-purple) 22%, transparent)',
    color: 'var(--text-muted)',
    background: 'color-mix(in srgb, var(--accent-purple) 3%, transparent)',
    borderRadius: 6,
    fontSize: 12,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    maxHeight: 88,
    overflowY: 'auto' as const,
    overflowX: 'hidden' as const,
    overscrollBehavior: 'contain',
    scrollBehavior: 'smooth',
    scrollbarWidth: 'thin' as const,
    scrollbarColor:
      'color-mix(in srgb, var(--accent-purple) 24%, transparent) transparent',
  },
}));
