// ── 侧边栏样式 ──────────────────────────────────────────────
import { createStyles } from 'antd-style';
import { SIDEBAR_WIDTH } from '../styles';

export const useSidebarStyles = createStyles(({ token }) => ({
  sidebar: {
    width: SIDEBAR_WIDTH,
    minWidth: SIDEBAR_WIDTH,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid',
    borderColor: 'var(--pudding-chat-border)',
    background: 'var(--pudding-chat-sidebar-bg)',
    backdropFilter: 'blur(12px)',
    transition:
      'width 0.2s ease, min-width 0.2s ease, border 0.2s ease, background 0.18s ease',
    overflow: 'hidden',
  },
  sidebarCollapsed: { width: 0, minWidth: 0, borderRight: 'none' },
  sidebarHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid',
    borderColor: 'var(--pudding-chat-border)',
  },
  sidebarTitleBlock: { minWidth: 0, flex: 1 },
  sidebarTitle: {
    fontSize: 14,
    fontWeight: 650,
    lineHeight: '18px',
    color: 'var(--pudding-chat-text)',
  },
  sidebarSubtitle: {
    marginTop: 1,
    fontSize: 11,
    lineHeight: '14px',
    color: 'var(--pudding-chat-text-subtle)',
  },
  sidebarIconBtn: {
    width: 28,
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--pudding-chat-text)',
  },
  sidebarNewBtn: {
    flex: 1,
    justifyContent: 'flex-start',
    fontSize: 13,
    fontWeight: 500,
  },
  sidebarSearch: {
    padding: '8px 12px 4px',
    '& .ant-input': {
      background: 'var(--pudding-chat-surface)',
      color: 'var(--pudding-chat-text)',
      backdropFilter: 'blur(12px)',
      borderRadius: 8,
      border: '1px solid',
      borderColor: 'var(--pudding-chat-border)',
    },
  },
  agentContactList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    padding: '8px',
    borderBottom: '1px solid var(--pudding-chat-border)',
  },
  agentContactItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    minHeight: 54,
    padding: '8px',
    border: 0,
    borderRadius: 8,
    background: 'transparent',
    color: 'var(--pudding-chat-text)',
    cursor: 'pointer' as const,
    textAlign: 'left' as const,
    transition: 'background 0.15s, opacity 0.15s',
    '&:hover:not(:disabled)': {
      background: 'var(--pudding-chat-surface-muted)',
    },
    '&:disabled': { cursor: 'not-allowed' as const, opacity: 0.55 },
  },
  agentContactItemActive: {
    background: 'var(--pudding-chat-accent-soft)',
  },
  agentContactAvatar: {
    flexShrink: 0,
    color: 'var(--pudding-chat-surface)',
    fontWeight: 650,
  },
  agentContactBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  agentContactName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
  },
  agentContactMeta: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 11,
    color: 'var(--pudding-chat-text-subtle)',
    lineHeight: '14px',
  },
  sidebarSecondaryLabel: {
    padding: '8px 4px 2px',
    fontSize: 11,
    lineHeight: '14px',
    fontWeight: 650,
    color: 'var(--pudding-chat-text-subtle)',
  },
  sidebarEmptyInline: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 32,
    padding: '6px 8px',
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
    lineHeight: '18px',
  },
  sessionDetailArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minHeight: 0,
  },
  sessionDetailHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 16px 4px',
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
    fontWeight: 600,
  },
  sessionList: { flex: 1, overflowY: 'auto' as const, padding: '4px 8px' },
  groupLabel: {
    padding: '16px 8px 4px',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--pudding-chat-text-subtle)',
    opacity: 0.8,
    textTransform: 'uppercase' as const,
  },
  sessionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 16px',
    borderRadius: token.borderRadius,
    cursor: 'pointer',
    fontSize: 13,
    color: token.colorTextSecondary,
    transition: 'background 0.15s',
    overflow: 'hidden',
    minHeight: 48,
    '&:hover': { background: token.colorFillQuaternary },
  },
  sessionItemActive: {
    background: 'var(--pudding-chat-accent-soft)',
    color: 'var(--pudding-chat-text)',
    fontWeight: 500,
    borderLeft: '3px solid var(--pudding-chat-accent)',
    paddingLeft: 13,
  },
  sessionItemArchived: { opacity: 0.5 },
  sessionTitle: {
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
  },
  avatarRuntimeRail: {
    flex: '0 0 188px',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: 12,
    minHeight: 0,
    overflow: 'hidden',
    '@media (max-width: 1023px)': {
      display: 'none',
    },
  },
}));
