// ── 聊天页样式（antd-style createStyles）─────────────────────
import { createStyles } from 'antd-style';

export const SIDEBAR_WIDTH = 260;

export const useChatStyles = createStyles(({ token }) => ({
  layout: { display: 'flex', height: '100vh', overflow: 'hidden', background: 'var(--warm-beige)' },
  sidebar: {
    width: SIDEBAR_WIDTH, minWidth: SIDEBAR_WIDTH, height: '100%',
    display: 'flex', flexDirection: 'column',
    borderRight: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(12px)',
    transition: 'width 0.2s ease, min-width 0.2s ease, border 0.2s ease',
    overflow: 'hidden',
  },
  sidebarCollapsed: { width: 0, minWidth: 0, borderRight: 'none' },
  sidebarHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 16px', borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' },
  sidebarNewBtn: { flex: 1, justifyContent: 'flex-start', fontSize: 13, fontWeight: 500 },
  sidebarSearch: { padding: '8px 12px 4px', '& .ant-input': { background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)', backdropFilter: 'blur(12px)', borderRadius: 8, border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' } },
  sessionList: { flex: 1, overflowY: 'auto' as const, padding: '4px 8px' },
  groupLabel: { padding: '16px 8px 4px', fontSize: 11, fontWeight: 600, color: 'var(--earth-brown)', opacity: 0.5, textTransform: 'uppercase' as const },
  sessionItem: {
    display: 'flex', alignItems: 'center', gap: 12, padding: '12px 16px', borderRadius: token.borderRadius,
    cursor: 'pointer', fontSize: 13, color: token.colorTextSecondary, transition: 'background 0.15s',
    overflow: 'hidden', minHeight: 48,
    '&:hover': { background: token.colorFillQuaternary },
  },
  sessionItemActive: { background: token.colorFillSecondary, color: token.colorText, fontWeight: 500, borderLeft: '3px solid var(--pale-yellow-sunlight)', paddingLeft: 13 },
  sessionItemArchived: { opacity: 0.5 },
  sessionTitle: { flex: 1, overflow: 'hidden', whiteSpace: 'nowrap' as const, textOverflow: 'ellipsis' },
  mainArea: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, overflow: 'hidden' },
  header: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px',
    borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(12px)',
    minHeight: 44, flexShrink: 0,
  },
  headerLogo: { width: 24, height: 24, objectFit: 'contain' as const },
  headerBrand: { fontSize: 14, fontWeight: 700, color: token.colorText, whiteSpace: 'nowrap' as const },
  headerSelect: { minWidth: 110, maxWidth: 180, fontSize: 12 },
  headerSpacer: { flex: 1 },
  devModeActive: { color: token.colorPrimary },
  chatBody: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, overflow: 'hidden', padding: '0 20px', background: 'var(--warm-beige)' },
  chatBodyWithDev: { display: 'flex', flexDirection: 'row' as const, gap: 12, minHeight: 0, height: '100%' },
  chatBodyMain: { display: 'flex', flexDirection: 'column' as const, flex: 1, minWidth: 0, minHeight: 0 },
  messageList: { flex: 1, overflowY: 'auto' as const, padding: '16px 0 8px', display: 'flex', flexDirection: 'column' as const, gap: 12 },
  historyLoading: { display: 'flex', justifyContent: 'center', padding: '8px 0' },
  messageRow: { display: 'flex' },
  turnContainer: { position: 'relative' as const, display: 'flex', gap: 12, width: '100%' },
  turnTimeline: { width: 2, borderRadius: 2, background: token.colorBorderSecondary, marginTop: 4, marginBottom: 4, flexShrink: 0 },
  turnBody: { display: 'flex', flexDirection: 'column' as const, gap: 8, width: '100%' },
  messageContent: {
    maxWidth: '74%', display: 'flex', flexDirection: 'column', gap: 4, position: 'relative' as const,
    fontSize: 14, color: 'var(--text-primary)',
    '&:hover .message-actions': { opacity: 1, transform: 'translateY(0)', pointerEvents: 'auto' as const },
  },
  userContent: { alignItems: 'flex-end' },
  agentContent: { alignItems: 'flex-start' },
  userRow: { justifyContent: 'flex-end' },
  agentRow: { justifyContent: 'flex-start' },
  bubble: { width: 'fit-content' as const, maxWidth: 'min(76%, 820px)', padding: '12px 16px', borderRadius: 8, lineHeight: 1.6, wordBreak: 'break-word' as const, whiteSpace: 'pre-wrap' as const, border: '1px solid transparent', background: 'transparent', transition: 'background 200ms ease-in-out, box-shadow 200ms ease-in-out', '&:hover': { background: 'color-mix(in srgb, var(--soft-white) 50%, transparent)', boxShadow: '0 1px 6px rgba(0,0,0,0.04)' } },
  userBubble: { maxWidth: 'min(68%, 680px)', background: 'color-mix(in srgb, var(--accent-purple) 18%, var(--soft-white))', color: 'var(--text-primary)', borderBottomRightRadius: 4, borderBottomLeftRadius: 8, border: '1px solid', borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)', '&:hover': { background: 'color-mix(in srgb, var(--accent-purple) 24%, var(--soft-white))' } },
  agentBubble: { maxWidth: 'min(76%, 820px)', background: 'transparent', color: 'var(--text-primary)', border: '1px solid', borderColor: token.colorBorderSecondary, borderRadius: 8, borderBottomLeftRadius: 4, '&:hover': { background: 'color-mix(in srgb, var(--soft-white) 50%, transparent)', backdropFilter: 'blur(12px)' } },
  assistantAnswer: {
    maxWidth: 'min(82%, 880px)',
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(16px)',
    color: 'var(--text-primary)',
    border: '1px solid', borderColor: token.colorBorderSecondary,
    borderRadius: 8,
    borderBottomLeftRadius: 4,
    padding: '12px 16px',
    fontSize: 14,
  },
  reasoningPanel: {
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(16px)',
    border: '1px solid', borderColor: token.colorBorderSecondary,
    borderRadius: 8,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  reasoningHeader: { fontSize: 12, color: 'var(--earth-brown)', opacity: 0.7, display: 'flex', alignItems: 'center', gap: 8 },
  reasoningBlock: {
    borderRadius: token.borderRadius,
    background: token.colorFillQuaternary,
    border: '1px solid', borderColor: token.colorBorderSecondary,
    padding: '6px 8px',
  },
  reasoningToggle: { color: token.colorPrimary, cursor: 'pointer', fontSize: 12, userSelect: 'none' as const },
  reasoningText: { whiteSpace: 'pre-wrap' as const, color: token.colorTextSecondary, fontSize: 13, lineHeight: 1.6, marginTop: 6 },
  reasoningSummary: { fontSize: 12, color: 'var(--earth-brown)', opacity: 0.5, overflow: 'hidden', whiteSpace: 'nowrap' as const, textOverflow: 'ellipsis', maxWidth: '100%' },
  stepCardList: { display: 'flex', flexDirection: 'column' as const, gap: 12, position: 'relative' as const, paddingLeft: 12 },
  stepCardLine: { position: 'absolute' as const, left: 5, top: 4, bottom: 4, width: 2, borderRadius: 2, background: token.colorBorderSecondary },
  stepCard: { position: 'relative' as const, background: token.colorFillQuaternary, borderRadius: token.borderRadius, border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)', borderLeftWidth: 4, padding: '8px 10px' },
  stepCardDot: { position: 'absolute' as const, left: -11, top: 14, width: 8, height: 8, borderRadius: '50%', background: token.colorBorder, border: `1px solid ${token.colorBgContainer}` },
  stepCardExecuting: { borderLeftColor: token.colorInfo },
  stepCardSuccess: { borderLeftColor: token.colorSuccess },
  stepCardError: { borderLeftColor: token.colorError },
  stepCardTitle: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4, fontSize: 13 },
  stepCardStatus: { color: token.colorTextSecondary, fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const },
  stepCardMessage: { color: token.colorText, fontSize: 13, lineHeight: 1.6, whiteSpace: 'pre-wrap' as const },
  stepCardTime: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },

  /* ── Tool output collapse (长输出折叠 + 滚动 + 模糊) ── */
  toolOutputCollapse: {
    marginTop: 4,
    borderRadius: 6,
    overflow: 'hidden',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
  },
  toolOutputContent: {
    padding: '8px 10px',
    fontSize: 12,
    color: token.colorTextSecondary,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
    fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace",
    background: token.colorFillQuaternary,
  },
  toolOutputFade: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: `linear-gradient(to bottom, transparent, ${token.colorFillQuaternary})`,
    pointerEvents: 'none' as const,
  },
  toolOutputToggle: {
    padding: '4px 10px',
    fontSize: 11,
    color: token.colorPrimary,
    cursor: 'pointer',
    borderTop: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
    background: token.colorFillQuaternary,
  },
  thinkingStepCard: {
    background: 'color-mix(in srgb, var(--earth-brown) 8%, var(--soft-white))',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 20%, transparent)',
  },
  thinkingStepHeader: { cursor: 'pointer', userSelect: 'none' as const },
  thinkingStepMessage: {
    fontStyle: 'italic',
    color: token.colorTextSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 60%, transparent)',
    borderRadius: 6,
    padding: '6px 8px',
  },
  assistantStatusMeta: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' as const, fontSize: 12 },
  assistantStatusTag: { fontSize: 12, borderRadius: 999, padding: '2px 8px', border: '1px solid', borderColor: token.colorBorderSecondary, background: token.colorFillSecondary, color: token.colorTextSecondary },
  errorBubble: { borderColor: token.colorError },
  messageActions: {
    opacity: 0, transform: 'translateY(3px)', pointerEvents: 'none' as const,
    transition: 'opacity 200ms ease-in-out, transform 200ms ease-in-out',
    '& .ant-btn-text': { color: 'var(--earth-brown)' },
    '& .ant-btn-text:hover': { color: 'var(--accent-purple)' },
    '& .ant-btn-dangerous': { color: 'var(--earth-brown)' },
    '& .ant-btn-dangerous:hover': { color: token.colorError },
  },
  messageMeta: { display: 'flex', alignItems: 'center', gap: 8, minHeight: 20 },
  timeText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  sendingText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  timeDivider: { display: 'flex', alignItems: 'center', gap: 8, margin: '2px 0', color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12, '&::before, &::after': { content: '""', flex: 1, height: 1, background: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' } },
  inputPanel: { padding: '8px 0 0', display: 'flex', flexDirection: 'column', gap: 6, background: 'color-mix(in srgb, var(--soft-white) 80%, transparent)', backdropFilter: 'blur(16px)', borderTop: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)', borderRadius: '8px 8px 0 0', marginTop: 4 },
  tokenIndicator: { display: 'flex', alignItems: 'center', gap: 8, padding: '0 2px' },
  tokenProgress: { flex: 1 },
  // 工具栏（输入框上方一行）
  toolbar: { display: 'flex', alignItems: 'center', gap: 4, padding: '0 6px' },
  toolbarSpacer: { flex: 1 },
  // 状态栏（窄条 IDE 风格：紧贴底部，单行图标透传状态）──
  statusBar: { display: 'flex', alignItems: 'center', gap: 6, padding: '1px 8px 2px', fontSize: 10, color: 'var(--earth-brown)', opacity: 0.65, flexWrap: 'wrap' as const, minHeight: 20, background: 'color-mix(in srgb, var(--earth-brown) 4%, transparent)', borderTop: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)' },
  statusText: { whiteSpace: 'nowrap' as const },
  statusDivider: { userSelect: 'none' as const, opacity: 0.3 },
  // 状态栏图标通用
  statusIcon: { display: 'inline-flex', alignItems: 'center', width: 16, height: 16, justifyContent: 'center', flexShrink: 0 },
  statusIconGroup: { display: 'inline-flex', alignItems: 'center', gap: 3, cursor: 'default', flexShrink: 0 },
  statusIconLabel: { fontSize: 10, whiteSpace: 'nowrap' as const, lineHeight: '14px' },
  statusIconThunder: { transition: 'color 0.3s ease, opacity 0.3s ease' },
  statusPulse: { animation: 'statusPulseAnim 2s ease-in-out infinite' },
  '@keyframes statusPulseAnim': { '0%, 100%': { opacity: 0.35 }, '50%': { opacity: 0.85 } },
  // 潜意识 LLM 发光动画
  subconsciousGlow: { animation: 'subconsciousGlowAnim 3s ease-in-out infinite', filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))' },
  '@keyframes subconsciousGlowAnim': { '0%, 100%': { filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))' }, '50%': { filter: 'drop-shadow(0 0 8px rgba(167,139,250,0.9))' } },
  // ── 语音区域 ──────────────────────────────────────────
  voiceArea: { display: 'flex', alignItems: 'center', gap: 4, flexShrink: 0 },
  voiceBtn: { fontSize: 14, opacity: 0.5, transition: 'opacity 0.2s, color 0.2s', '&:hover': { opacity: 0.8 } },
  voiceBtnRecording: { fontSize: 14, color: '#ef4444', animation: 'voicePulse 1.2s ease-in-out infinite' },
  '@keyframes voicePulse': { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0.5 } },
  voiceWaveform: { display: 'flex', alignItems: 'flex-end', gap: 3, height: 18, paddingRight: 4 },
  voiceBarRecording: { width: 3, borderRadius: 2, background: '#ef4444', animation: 'voiceBarAnim 0.6s ease-in-out infinite alternate' },
  voiceBarPlaying: { width: 3, borderRadius: 2, background: '#22c55e', animation: 'voiceBarAnim 0.5s ease-in-out infinite alternate' },
  '@keyframes voiceBarAnim': { '0%': { height: 4 }, '100%': { height: 18 } },
  // ── Token 统计浮窗 ────────────────────────────────────
  tokenStatsPopup: {
    position: 'absolute' as const, bottom: 28, right: 0,
    width: 640, maxHeight: 420, overflowY: 'auto' as const,
    background: 'color-mix(in srgb, var(--soft-white) 98%, transparent)',
    backdropFilter: 'blur(20px)',
    border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)',
    borderRadius: 10, padding: 12, boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    zIndex: 1050, fontSize: 11,
  },
  tokenStatsTitle: { fontWeight: 600, fontSize: 12, marginBottom: 6, color: 'var(--earth-brown)' },
  tokenStatsTable: {
    width: '100%', borderCollapse: 'collapse' as const,
    '& th': { padding: '3px 6px', textAlign: 'left' as const, fontSize: 10, color: 'var(--earth-brown)', opacity: 0.6, fontWeight: 500, borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' },
    '& td': { padding: '3px 6px', fontSize: 10, fontVariantNumeric: 'tabular-nums' as const },
  },
  inputArea: { display: 'flex', gap: 8, alignItems: 'center' },
  input: { flex: 1 },
  emptyState: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: token.colorTextQuaternary, fontSize: 15 },
  onboardingState: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, padding: '24px 0' },
  onboardingLogo: { width: 56, height: 56, objectFit: 'contain' as const, opacity: 0.7 },
  onboardingTitle: { margin: 0 },
  onboardingSubtitle: { color: token.colorTextSecondary, fontSize: 14, textAlign: 'center' as const },
  errorAlert: { margin: '8px 0' },
  sidebarEmpty: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: token.colorTextQuaternary, fontSize: 13, padding: '0 16px', textAlign: 'center' as const },
  markdownBody: {
    whiteSpace: 'normal' as const,
    '& p': { margin: '0 0 8px' }, '& p:last-child': { marginBottom: 0 },
    '& ul, & ol': { paddingLeft: 22, margin: '6px 0' },
    '& blockquote': { margin: '8px 0', paddingLeft: 12, borderLeft: '2px solid var(--pale-yellow-sunlight)', color: 'var(--earth-brown)', opacity: 0.8 },
    '& a': { color: 'var(--sky-soft)', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
    '& table': { borderCollapse: 'collapse' as const },
    '& th, & td': { border: `1px solid ${token.colorBorderSecondary}`, padding: '6px 10px', textAlign: 'left' as const },
    '& th': { background: token.colorFillQuaternary },
  },
  markdownTableScroll: { maxWidth: '100%', overflowX: 'auto' as const, margin: '8px 0' },
  inlineCode: { padding: '1px 5px', borderRadius: 4, background: 'color-mix(in srgb, var(--misty-blue) 30%, transparent)', fontSize: '0.92em', fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace" },
  codeBlockWrap: { position: 'relative' as const, margin: '10px 0', borderRadius: 8, overflow: 'hidden', background: 'color-mix(in srgb, var(--misty-blue) 30%, transparent)', '& pre': { margin: 0, padding: '14px 16px', overflowX: 'auto' as const, fontSize: 13, fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace" } },
  codeCopyButton: { position: 'absolute' as const, top: 8, right: 8, zIndex: 1 },
  streamingCursor: { display: 'inline-block', width: 8, marginLeft: 2, color: token.colorPrimary, animation: 'cursorBlink 1s steps(1) infinite' },
  '@keyframes cursorBlink': { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0 } },
  // ── 动画系统 ──────────────────────────────────────────────
  latestTurn: { animation: 'messageIn 300ms ease-out' },
  stepCardAnimated: { animation: 'stepIn 200ms ease-out', opacity: 0, animationFillMode: 'forwards' as const },
  thinkingPulse: { animation: 'thinkingPulse 1500ms ease-in-out infinite' },
  stepCardCompleteIcon: { transition: 'color 300ms ease-in-out', color: 'var(--desaturated-green)' },
  inputCursor: { display: 'inline-block', width: 2, height: 18, background: 'var(--accent-purple)', marginLeft: 1, animation: 'cursorBlink 1s steps(1) infinite', verticalAlign: 'middle' as const },
  // ── 头像系统 ──────────────────────────────────────────────
  avatarGroup: { display: 'flex', gap: 12, width: '100%', alignItems: 'flex-start' },
  userAvatarGroup: { display: 'flex', gap: 12, width: '100%', alignItems: 'flex-start', flexDirection: 'row-reverse' as const },
  avatarCol: { width: 32, flexShrink: 0 },
  avatarImg: { width: 32, height: 32, borderRadius: '50%', objectFit: 'cover' as const, flexShrink: 0 },
  avatarPlaceholder: {
    width: 32, height: 32, borderRadius: '50%',
    color: '#fff',
    fontSize: 14, fontWeight: 500,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0, userSelect: 'none' as const,
  },
  avatarNameRow: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4, minHeight: 20 },
  avatarName: { fontSize: 14, color: 'var(--earth-brown)', fontWeight: 500, lineHeight: '20px' },
  avatarUserIcon: {
    width: 32, height: 32, borderRadius: '50%',
    background: 'var(--sky-soft)',
    color: 'var(--earth-brown)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
    '& .anticon': { fontSize: 16 },
  },
  groupContent: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const },
  userGroupContent: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const, alignItems: 'flex-end' as const },
  systemRow: { justifyContent: 'center' },

  // ── 开发者模式面板 ───────────────────────────────────────────
  devPanel: {
    width: 400,
    minWidth: 360,
    maxWidth: 440,
    display: 'flex',
    flexDirection: 'column' as const,
    borderLeft: '1px solid',
    borderColor: token.colorBorderSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 78%, transparent)',
    backdropFilter: 'blur(12px)',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 12,
    marginBottom: 12,
  },
  devPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    borderBottom: '1px solid',
    borderColor: token.colorBorderSecondary,
    fontSize: 13,
    fontWeight: 600,
  },
  devPanelTabs: {
    flex: 1,
    minHeight: 0,
    padding: '8px 10px 10px',
    '& .ant-tabs-content-holder': {
      overflow: 'auto',
    },
  },
  devPanelSection: { display: 'flex', flexDirection: 'column' as const, gap: 8 },
  devPanelLoading: { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '16px 0' },
  devLine: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, fontSize: 12 },
  devLayerTitle: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' },
  devPreview: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '8px 10px',
    fontSize: 12,
    lineHeight: 1.5,
  },
  devList: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  devListItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    background: token.colorFillQuaternary,
    borderRadius: 6,
    padding: '6px 8px',
  },
  devErrorText: { margin: 0, color: token.colorError },
  devPanelHint: { margin: 0, fontSize: 12, color: token.colorTextSecondary },
  subconsciousTimeline: {
    padding: '4px 0 8px',
    '& .ant-timeline-item': { paddingBottom: 12 },
    '& .ant-timeline-item-content': { fontSize: 13 },
  },
  devEventList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    maxHeight: '56vh',
    overflowY: 'auto' as const,
  },
  devEventItem: {
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '6px 8px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  devEventTime: { fontSize: 11, color: token.colorTextSecondary },
  devEventPayload: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    fontSize: 12,
    lineHeight: 1.5,
  },
  /* ── Stateful Motion: thinking, searching, memory, tool, error, success ── */
  '@keyframes neuralPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.8, transform: 'scale(1.02)' },
  },
  '@keyframes particleFlow': {
    '0%': { backgroundPosition: '0% 50%' },
    '100%': { backgroundPosition: '200% 50%' },
  },
  '@keyframes tokenStream': {
    '0%': { opacity: 0, transform: 'translateY(4px)' },
    '100%': { opacity: 1, transform: 'translateY(0)' },
  },
  '@keyframes waveScan': {
    '0%': { backgroundPosition: '-200% 50%' },
    '100%': { backgroundPosition: '200% 50%' },
  },
  '@keyframes breathe': {
    '0%, 100%': { opacity: 0.6, transform: 'scale(0.98)' },
    '50%': { opacity: 1, transform: 'scale(1)' },
  },
  '@keyframes ambientFloat': {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-6px)' },
  },
  '@keyframes glitchShake': {
    '0%, 100%': { transform: 'translateX(0)' },
    '10%': { transform: 'translateX(-2px)' },
    '30%': { transform: 'translateX(2px)' },
    '50%': { transform: 'translateX(-1px)' },
    '70%': { transform: 'translateX(1px)' },
  },
  '@keyframes softDiffuse': {
    '0%': { boxShadow: '0 0 0 0 rgba(124,58,237,0)' },
    '50%': { boxShadow: '0 0 20px 4px rgba(124,58,237,0.12)' },
    '100%': { boxShadow: '0 0 0 0 rgba(124,58,237,0)' },
  },

  /* ── Ambient particles background ── */
  ambientLayer: {
    position: 'absolute' as const, inset: 0, pointerEvents: 'none' as const,
    background: 'radial-gradient(ellipse at 50% 0%, rgba(124,58,237,0.04) 0%, transparent 60%), radial-gradient(ellipse at 80% 100%, rgba(59,130,246,0.03) 0%, transparent 50%)',
    zIndex: 0,
  },

  /* ── Thinking state ── */
  agentThinking: {
    animation: 'neuralPulse 2.5s ease-in-out infinite',
    position: 'relative' as const,
    '&::before': {
      content: '""', position: 'absolute' as const, inset: -1, borderRadius: 10,
      background: 'linear-gradient(90deg, transparent, rgba(124,58,237,0.1), transparent)',
      backgroundSize: '200% 100%',
      animation: 'particleFlow 3s linear infinite',
    },
  },

  /* ── Token streaming ── */
  tokenStreaming: {
    animation: 'tokenStream 0.2s ease-out',
    opacity: 1,
  },

  /* ── Searching / Tool running ── */
  agentSearching: {
    position: 'relative' as const,
    '&::after': {
      content: '""', position: 'absolute' as const, bottom: 0, left: 0, height: 2, width: '100%',
      background: 'linear-gradient(90deg, transparent, rgba(59,130,246,0.4), transparent)',
      backgroundSize: '200% 100%',
      animation: 'waveScan 1.5s linear infinite',
    },
  },

  /* ── Memory recall ── */
  agentRecall: {
    animation: 'softDiffuse 2s ease-in-out infinite',
  },

  /* ── Error ── */
  agentError: {
    animation: 'glitchShake 0.4s ease-in-out',
    borderLeft: '3px solid #ff4d4f',
  },

  /* ── Success ── */
  agentSuccess: {
    animation: 'softDiffuse 1s ease-in-out 1',
  },

  /* ── Breathing message card ── */
  breathingCard: {
    animation: 'breathe 4s ease-in-out infinite',
    transition: 'all 0.3s ease',
  },

  /* ── Progressive disclosure ── */
  progressiveReveal: {
    overflow: 'hidden' as const,
    animation: 'revealDown 0.4s ease-out',
  },
  '@keyframes revealDown': {
    '0%': { maxHeight: 0, opacity: 0 },
    '100%': { maxHeight: 2000, opacity: 1 },
  },

  /* ── Reasoning stream (agent thinking chain) ── */
  reasoningStream: {
    whiteSpace: 'pre-wrap' as const,
    color: 'color-mix(in srgb, var(--accent-purple) 60%, var(--text-secondary))',
    fontSize: 12, lineHeight: 1.5, padding: '8px 10px',
    maxHeight: 300, overflowY: 'auto' as const,
    fontStyle: 'italic',
    borderLeft: '2px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    marginTop: 4,
    animation: 'tokenStream 0.3s ease-out',
  },

  /* ── Timeline reasoning block (统一时间线中的思维链条目) ── */
  reasoningBlockTimeline: {
    marginBottom: 8,
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    borderLeft: '3px solid var(--accent-purple, #7c3aed)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  reasoningBlockContentTimeline: {
    padding: '8px 12px',
    fontSize: 12,
    fontStyle: 'italic',
    color: 'color-mix(in srgb, var(--accent-purple) 60%, #5c4a3a)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
  },
  reasoningFadeTimeline: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: 'linear-gradient(to bottom, transparent, #fafaf7)',
    pointerEvents: 'none' as const,
  },
  reasoningToggleTimeline: {
    padding: '4px 12px',
    fontSize: 11,
    color: 'var(--accent-purple)',
    cursor: 'pointer',
    borderTop: '1px solid rgba(124, 58, 237, 0.15)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
  },

  /* ── ContextMemoryIndicator ── */
  indicatorWrapper: { position: 'relative' as const },
  indicatorRing: {
    cursor: 'pointer', width: 34, height: 34,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    borderRadius: '50%', transition: 'all 0.2s',
    '&:hover': { background: 'rgba(139,92,246,0.12)', boxShadow: '0 0 12px rgba(139,92,246,0.2)' },
  },
  indicatorPulse: { animation: 'indicatorPulse 2s ease-in-out infinite' },
  indicatorSpin: { animation: 'indicatorSpin 3s linear infinite' },
  '@keyframes indicatorPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.9, transform: 'scale(1.3)' },
  },
  '@keyframes indicatorSpin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  // 悬浮窗 — 向右弹出，确保在视口内
  indicatorPopup: {
    position: 'fixed',
    bottom: 100,
    right: 24,
    width: 270,
    background: 'rgba(30,30,40,0.96)',
    backdropFilter: 'blur(20px)',
    borderRadius: 12,
    padding: 16,
    color: '#e2e8f0',
    border: '1px solid rgba(139,92,246,0.3)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(139,92,246,0.15)',
    zIndex: 1000,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  popupHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  popupTitle: { fontWeight: 600, fontSize: 13 },
  popupStatus: { display: 'flex', alignItems: 'center', gap: 6, opacity: 0.8 },
  popupDot: { width: 6, height: 6, borderRadius: '50%' },
  popupBody: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  popupRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  popupValue: { fontFamily: 'monospace', fontSize: 11, opacity: 0.8 },
  popupProgress: { height: 3, borderRadius: 2, background: 'rgba(255,255,255,0.1)', margin: '4px 0' },
  popupProgressBar: { height: '100%', borderRadius: 2, transition: 'width 0.5s ease' },
  popupWarning: { color: '#f97316', fontSize: 11, marginTop: 4, padding: '6px 8px', background: 'rgba(249,115,22,0.1)', borderRadius: 6 },

  /* ── First-token loading ── */
  firstTokenLoading: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px',
    animation: 'breathe 2s ease-in-out infinite',
  },
  pulseDot: {
    width: 8, height: 8, borderRadius: '50%',
    background: 'var(--accent-purple)',
    animation: 'neuralPulse 1.5s ease-in-out infinite',
  },
  pulseLabel: {
    fontSize: 13, color: 'color-mix(in srgb, var(--accent-purple) 50%, var(--text-secondary))',
    fontStyle: 'italic',
  },
}));
