// ── 聊天页样式（antd-style createStyles）─────────────────────
import { createStyles } from 'antd-style';

export const SIDEBAR_WIDTH = 260;

export const useChatStyles = createStyles(({ token }) => ({
  layout: { display: 'flex', height: '100vh', overflow: 'hidden', background: 'var(--warm-beige)' },
  sidebar: {
    width: SIDEBAR_WIDTH, minWidth: SIDEBAR_WIDTH, height: '100%',
    display: 'flex', flexDirection: 'column',
    borderRight: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(12px)',
    transition: 'width 0.2s ease, min-width 0.2s ease, border 0.2s ease',
    overflow: 'hidden',
  },
  sidebarCollapsed: { width: 0, minWidth: 0, borderRight: 'none' },
  sidebarHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 16px', borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' },
  sidebarNewBtn: { flex: 1, justifyContent: 'flex-start', fontSize: 13, fontWeight: 500 },
  sidebarSearch: { padding: '8px 12px 4px', '& .ant-input': { background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)', backdropFilter: 'blur(12px)', borderRadius: 8, border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' } },
  sessionList: { flex: 1, overflowY: 'auto' as const, padding: '4px 8px' },
  groupLabel: { padding: '16px 8px 4px', fontSize: 11, fontWeight: 600, color: 'var(--earth-brown)', opacity: 0.5, textTransform: 'uppercase' as const },
  sessionItem: {
    display: 'flex', alignItems: 'center', gap: 12, padding: '12px 16px', borderRadius: token.borderRadius,
    cursor: 'pointer', fontSize: 13, color: token.colorTextSecondary, transition: 'background 0.15s',
    overflow: 'hidden', minHeight: 48,
    '&:hover': { background: token.colorFillQuaternary },
  },
  sessionItemActive: { background: token.colorFillSecondary, color: token.colorText, fontWeight: 500, borderLeft: '3px solid var(--pale-yellow-sunlight)', paddingLeft: 13 },
  sessionItemArchived: { opacity: 0.5 },
  sessionTitle: { flex: 1, overflow: 'hidden', whiteSpace: 'nowrap' as const, textOverflow: 'ellipsis' },
  mainArea: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0, overflow: 'hidden' },
  header: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px',
    borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(12px)',
    minHeight: 44, flexShrink: 0,
  },
  headerLogo: { width: 24, height: 24, objectFit: 'contain' as const },
  headerBrand: { fontSize: 14, fontWeight: 700, color: token.colorText, whiteSpace: 'nowrap' as const },
  headerSelect: { minWidth: 110, maxWidth: 180, fontSize: 12 },
  /** Select popup 下拉菜单，使用 --pudding-chat-* 语义 token 覆盖 AntD 默认背景 */
  headerSelectPopup: {
    background: 'var(--pudding-chat-surface) !important',
    border: '1px solid var(--pudding-chat-border)',
    borderRadius: 8,
    boxShadow: 'var(--pudding-chat-shadow)',
    padding: 4,
    '& .ant-select-item': {
      borderRadius: 6,
      padding: '5px 12px',
      fontSize: 13,
      color: 'var(--pudding-chat-text)',
      transition: 'background 0.15s, color 0.15s',
    },
    '& .ant-select-item-option-active': {
      background: 'var(--pudding-chat-surface-muted) !important',
    },
    '& .ant-select-item-option-selected': {
      background: 'var(--pudding-chat-accent-soft) !important',
      color: 'var(--pudding-chat-accent) !important',
      fontWeight: 500,
    },
    '& .ant-select-item-option-disabled': {
      color: 'var(--pudding-chat-text-subtle) !important',
      opacity: 0.5,
    },
    '& .ant-select-item-empty': {
      color: 'var(--pudding-chat-text-subtle)',
    },
    '& .ant-divider': {
      margin: '4px 0',
      borderColor: 'var(--pudding-chat-border)',
    },
    '& .ant-btn-link': {
      color: 'var(--pudding-chat-accent)',
      fontSize: 12,
      height: 32,
      width: '100%',
      borderRadius: 6,
      transition: 'background 0.15s',
      '&:hover': {
        background: 'var(--pudding-chat-accent-soft) !important',
      },
    },
  },
  headerSpacer: { flex: 1 },
  devModeActive: { color: token.colorPrimary },
  /** 全局操作区（主题/Help/语言/用户）适应 Chat Header 紧凑空间 */
  headerGlobalActions: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    flexShrink: 0,
    '& .ant-btn': { fontSize: 13, width: 28, height: 28 },
    '& .ant-select': { fontSize: 12 },
  },
  /** Session ID 文本，中屏以下隐藏 */
  sessionIdText: {
    cursor: 'pointer',
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.6,
    marginLeft: 8,
    fontFamily: 'monospace',
    userSelect: 'all' as const,
    '@media (max-width: 1023px)': { display: 'none' },
  },
  /** 移动端隐藏元素 */
  hideOnMobile: {
    '@media (max-width: 767px)': { display: 'none' },
  },
  /** 平板端隐藏元素 */
  hideOnTablet: {
    '@media (min-width: 768px) and (max-width: 1023px)': { display: 'none' },
  },
  chatBody: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, overflow: 'hidden', padding: '0 20px', background: 'var(--warm-beige)' },
  chatBodyWithDev: { display: 'flex', flexDirection: 'row' as const, gap: 12, minHeight: 0, height: '100%' },
  chatBodyMain: { display: 'flex', flexDirection: 'column' as const, flex: 1, minWidth: 0, minHeight: 0 },
  messageList: { flex: 1, overflowY: 'auto' as const, padding: '16px 0 8px', display: 'flex', flexDirection: 'column' as const, gap: 12 },
  historyLoading: { display: 'flex', justifyContent: 'center', padding: '8px 0' },
  messageRow: { display: 'flex' },
  turnContainer: { position: 'relative' as const, display: 'flex', gap: 12, width: '100%' },
  turnTimeline: { width: 2, borderRadius: 2, background: token.colorBorderSecondary, marginTop: 4, marginBottom: 4, flexShrink: 0 },
  turnBody: { display: 'flex', flexDirection: 'column' as const, gap: 8, width: '100%' },
  messageContent: {
    maxWidth: '74%', display: 'flex', flexDirection: 'column', gap: 4, position: 'relative' as const,
    fontSize: 14, color: 'var(--text-primary)',
    '&:hover .message-actions': { opacity: 1, transform: 'translateY(0)', pointerEvents: 'auto' as const },
  },
  userContent: { alignItems: 'flex-end' },
  agentContent: { alignItems: 'flex-start' },
  userRow: { justifyContent: 'flex-end' },
  agentRow: { justifyContent: 'flex-start' },
  bubble: { width: 'fit-content' as const, maxWidth: 'min(76%, 820px)', padding: '12px 16px', borderRadius: 8, lineHeight: 1.6, wordBreak: 'break-word' as const, whiteSpace: 'pre-wrap' as const, border: '1px solid transparent', background: 'transparent', transition: 'background 200ms ease-in-out, box-shadow 200ms ease-in-out', '&:hover': { background: 'color-mix(in srgb, var(--soft-white) 50%, transparent)', boxShadow: '0 1px 6px rgba(0,0,0,0.04)' } },
  userBubble: { maxWidth: 'min(68%, 680px)', background: 'color-mix(in srgb, var(--accent-purple) 10%, var(--soft-white))', color: 'var(--text-primary)', borderBottomRightRadius: 4, borderBottomLeftRadius: 8, border: '1px solid', borderColor: 'color-mix(in srgb, var(--accent-purple) 18%, transparent)', '&:hover': { background: 'color-mix(in srgb, var(--accent-purple) 14%, var(--soft-white))' } },
  agentBubble: { maxWidth: 'min(76%, 820px)', background: 'transparent', color: 'var(--text-primary)', border: '1px solid', borderColor: token.colorBorderSecondary, borderRadius: 8, borderBottomLeftRadius: 4, '&:hover': { background: 'color-mix(in srgb, var(--soft-white) 50%, transparent)' } },
  assistantAnswer: {
    maxWidth: 'min(82%, 880px)',
    background: 'var(--soft-white)',
    color: 'var(--text-primary)',
    border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 8,
    borderBottomLeftRadius: 4,
    padding: '12px 16px',
    fontSize: 14,
  },
  reasoningPanel: {
    background: 'color-mix(in srgb, var(--soft-white) 70%, transparent)',
    backdropFilter: 'blur(16px)',
    border: '1px solid', borderColor: token.colorBorderSecondary,
    borderRadius: 8,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  reasoningHeader: { fontSize: 12, color: 'var(--earth-brown)', opacity: 0.7, display: 'flex', alignItems: 'center', gap: 8 },
  reasoningBlock: {
    borderRadius: token.borderRadius,
    background: token.colorFillQuaternary,
    border: '1px solid', borderColor: token.colorBorderSecondary,
    padding: '6px 8px',
  },
  reasoningToggle: { color: token.colorPrimary, cursor: 'pointer', fontSize: 12, userSelect: 'none' as const },
  reasoningText: { whiteSpace: 'pre-wrap' as const, color: token.colorTextSecondary, fontSize: 13, lineHeight: 1.6, marginTop: 6 },
  reasoningSummary: { fontSize: 12, color: 'var(--earth-brown)', opacity: 0.5, overflow: 'hidden', whiteSpace: 'nowrap' as const, textOverflow: 'ellipsis', maxWidth: '100%' },
  stepCardList: { display: 'flex', flexDirection: 'column' as const, gap: 12, position: 'relative' as const, paddingLeft: 12 },
  stepCardLine: { position: 'absolute' as const, left: 5, top: 4, bottom: 4, width: 2, borderRadius: 2, background: token.colorBorderSecondary },
  stepCard: { position: 'relative' as const, background: token.colorFillQuaternary, borderRadius: token.borderRadius, border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)', borderLeftWidth: 4, padding: '8px 10px' },
  stepCardDot: { position: 'absolute' as const, left: -11, top: 14, width: 8, height: 8, borderRadius: '50%', background: token.colorBorder, border: `1px solid ${token.colorBgContainer}` },
  stepCardExecuting: { borderLeftColor: 'var(--earth-brown)' },
  stepCardSuccess: { borderLeftColor: 'color-mix(in srgb, var(--earth-brown) 40%, transparent)' },
  stepCardError: { borderLeftColor: token.colorError },
  stepCardTitle: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 4, fontSize: 13 },
  stepCardStatus: { color: token.colorTextSecondary, fontSize: 12, fontWeight: 600, textTransform: 'uppercase' as const },
  stepCardMessage: { color: token.colorText, fontSize: 13, lineHeight: 1.6, whiteSpace: 'pre-wrap' as const },
  stepCardTime: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },

  /* ── Tool output collapse (长输出折叠 + 滚动 + 模糊) ── */
  toolOutputCollapse: {
    marginTop: 4,
    borderRadius: 6,
    overflow: 'hidden',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
  },
  toolOutputContent: {
    padding: '8px 10px',
    fontSize: 12,
    color: token.colorTextSecondary,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
    fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace",
    background: token.colorFillQuaternary,
  },
  toolOutputFade: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: `linear-gradient(to bottom, transparent, ${token.colorFillQuaternary})`,
    pointerEvents: 'none' as const,
  },
  toolOutputToggle: {
    padding: '4px 10px',
    fontSize: 11,
    color: token.colorPrimary,
    cursor: 'pointer',
    borderTop: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
    background: token.colorFillQuaternary,
  },
  thinkingStepCard: {
    background: 'color-mix(in srgb, var(--earth-brown) 8%, var(--soft-white))',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 20%, transparent)',
  },
  thinkingStepHeader: { cursor: 'pointer', userSelect: 'none' as const },
  thinkingStepMessage: {
    fontStyle: 'italic',
    color: token.colorTextSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 60%, transparent)',
    borderRadius: 6,
    padding: '6px 8px',
  },
  assistantStatusMeta: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' as const, fontSize: 12 },
  assistantStatusTag: { fontSize: 12, borderRadius: 999, padding: '2px 8px', border: '1px solid', borderColor: token.colorBorderSecondary, background: token.colorFillSecondary, color: token.colorTextSecondary },
  errorBubble: { borderColor: token.colorError },
  messageActions: {
    opacity: 0, transform: 'translateY(3px)', pointerEvents: 'none' as const,
    transition: 'opacity 200ms ease-in-out, transform 200ms ease-in-out',
    '& .ant-btn-text': { color: 'var(--earth-brown)' },
    '& .ant-btn-text:hover': { color: 'var(--accent-purple)' },
    '& .ant-btn-dangerous': { color: 'var(--earth-brown)' },
    '& .ant-btn-dangerous:hover': { color: token.colorError },
  },
  messageMeta: { display: 'flex', alignItems: 'center', gap: 8, minHeight: 20 },
  timeText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  sendingText: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },
  timeDivider: { display: 'flex', alignItems: 'center', gap: 8, margin: '2px 0', color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12, '&::before, &::after': { content: '""', flex: 1, height: 1, background: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' } },
  inputPanel: { padding: '8px 0 0', display: 'flex', flexDirection: 'column', gap: 6, background: 'color-mix(in srgb, var(--soft-white) 80%, transparent)', backdropFilter: 'blur(16px)', borderTop: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)', borderRadius: '8px 8px 0 0', marginTop: 4 },
  tokenIndicator: { display: 'flex', alignItems: 'center', gap: 8, padding: '0 2px' },
  tokenProgress: { flex: 1 },
  // 工具栏（输入框上方一行）
  toolbar: { display: 'flex', alignItems: 'center', gap: 4, padding: '0 6px' },
  toolbarSpacer: { flex: 1 },
  // 状态栏（窄条 IDE 风格：紧贴底部，单行图标透传状态）──
  statusBar: { display: 'flex', alignItems: 'center', gap: 6, padding: '1px 8px 2px', fontSize: 10, color: 'var(--earth-brown)', opacity: 0.65, flexWrap: 'wrap' as const, minHeight: 20, background: 'color-mix(in srgb, var(--earth-brown) 4%, transparent)', borderTop: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)' },
  statusText: { whiteSpace: 'nowrap' as const },
  statusDivider: { userSelect: 'none' as const, opacity: 0.3 },
  // 状态栏图标通用
  statusIcon: { display: 'inline-flex', alignItems: 'center', width: 16, height: 16, justifyContent: 'center', flexShrink: 0 },
  statusIconGroup: { display: 'inline-flex', alignItems: 'center', gap: 3, cursor: 'default', flexShrink: 0 },
  statusIconLabel: { fontSize: 10, whiteSpace: 'nowrap' as const, lineHeight: '14px' },
  statusIconThunder: { transition: 'color 0.3s ease, opacity 0.3s ease' },
  statusPulse: { animation: 'statusPulseAnim 2s ease-in-out infinite' },
  '@keyframes statusPulseAnim': { '0%, 100%': { opacity: 0.35 }, '50%': { opacity: 0.85 } },
  // 潜意识 LLM 发光动画
  subconsciousGlow: { animation: 'subconsciousGlowAnim 3s ease-in-out infinite', filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))' },
  '@keyframes subconsciousGlowAnim': { '0%, 100%': { filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))' }, '50%': { filter: 'drop-shadow(0 0 8px rgba(167,139,250,0.9))' } },
  // ── 语音区域 ──────────────────────────────────────────
  voiceArea: { display: 'flex', alignItems: 'center', gap: 4, flexShrink: 0 },
  voiceBtn: { fontSize: 14, opacity: 0.5, transition: 'opacity 0.2s, color 0.2s', '&:hover': { opacity: 0.8 } },
  voiceBtnRecording: { fontSize: 14, color: '#ef4444', animation: 'voicePulse 1.2s ease-in-out infinite' },
  '@keyframes voicePulse': { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0.5 } },
  voiceWaveform: { display: 'flex', alignItems: 'flex-end', gap: 3, height: 18, paddingRight: 4 },
  voiceBarRecording: { width: 3, borderRadius: 2, background: '#ef4444', animation: 'voiceBarAnim 0.6s ease-in-out infinite alternate' },
  voiceBarPlaying: { width: 3, borderRadius: 2, background: '#22c55e', animation: 'voiceBarAnim 0.5s ease-in-out infinite alternate' },
  '@keyframes voiceBarAnim': { '0%': { height: 4 }, '100%': { height: 18 } },
  // ── Token 统计浮窗 ────────────────────────────────────
  tokenStatsPopup: {
    position: 'absolute' as const, bottom: 28, right: 0,
    width: 640, maxHeight: 420, overflowY: 'auto' as const,
    background: 'color-mix(in srgb, var(--soft-white) 98%, transparent)',
    backdropFilter: 'blur(20px)',
    border: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)',
    borderRadius: 10, padding: 12, boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    zIndex: 1050, fontSize: 11,
  },
  tokenStatsTitle: { fontWeight: 600, fontSize: 12, marginBottom: 6, color: 'var(--earth-brown)' },
  tokenStatsTable: {
    width: '100%', borderCollapse: 'collapse' as const,
    '& th': { padding: '3px 6px', textAlign: 'left' as const, fontSize: 10, color: 'var(--earth-brown)', opacity: 0.6, fontWeight: 500, borderBottom: '1px solid', borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)' },
    '& td': { padding: '3px 6px', fontSize: 10, fontVariantNumeric: 'tabular-nums' as const },
  },
  inputArea: { display: 'flex', gap: 8, alignItems: 'center' },
  input: { flex: 1 },
  emptyState: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: token.colorTextQuaternary, fontSize: 15 },
  /* ── 空状态（ChatEmptyState）── */
  emptyStateShell: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px 96px',
  },
  emptyStateInner: {
    width: '100%',
    maxWidth: 420,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center' as const,
    gap: 12,
    animation: 'emptyFadeIn 220ms ease-out',
  },
  emptyLogoFrame: {
    width: 112,
    height: 112,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 28,
    background: 'color-mix(in srgb, var(--accent-purple) 5%, transparent)',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 8%, transparent)',
  },
  emptyLogo: {
    width: 64,
    height: 64,
    objectFit: 'contain' as const,
    opacity: 0.92,
  },
  emptyTitle: {
    margin: '8px 0 0 !important',
    fontSize: '22px !important',
    fontWeight: '600 !important',
    color: 'var(--text-primary) !important',
  },
  emptySubtitle: {
    maxWidth: 360,
    fontSize: 14,
    lineHeight: 1.7,
    color: 'var(--text-muted)',
  },
  emptySuggestionRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    marginTop: 8,
  },
  emptySuggestionButton: {
    height: 34,
    padding: '0 14px',
    borderRadius: 17,
    border: '1px solid color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 86%, transparent)',
    color: 'var(--text-muted)',
    fontSize: 13,
    cursor: 'pointer' as const,
    transition: 'background 160ms ease, border-color 160ms ease, color 160ms ease',
    '&:hover': {
      background: 'color-mix(in srgb, var(--accent-purple) 7%, var(--soft-white))',
      borderColor: 'color-mix(in srgb, var(--accent-purple) 18%, transparent)',
      color: 'var(--text-primary)',
    },
  },
  '@keyframes emptyFadeIn': {
    '0%': { opacity: 0, transform: 'translateY(4px)' },
    '100%': { opacity: 1, transform: 'translateY(0)' },
  },
  errorAlert: { margin: '8px 0' },
  sidebarEmpty: { flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: token.colorTextQuaternary, fontSize: 13, padding: '0 16px', textAlign: 'center' as const },
  markdownBody: {
    whiteSpace: 'normal' as const,
    '& p': { margin: '0 0 8px' }, '& p:last-child': { marginBottom: 0 },
    '& ul, & ol': { paddingLeft: 22, margin: '6px 0' },
    '& blockquote': { margin: '8px 0', paddingLeft: 12, borderLeft: '2px solid var(--pale-yellow-sunlight)', color: 'var(--earth-brown)', opacity: 0.8 },
    '& a': { color: 'var(--sky-soft)', textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
    '& table': { borderCollapse: 'collapse' as const },
    '& th, & td': { border: `1px solid ${token.colorBorderSecondary}`, padding: '6px 10px', textAlign: 'left' as const },
    '& th': { background: token.colorFillQuaternary },
  },
  markdownTableScroll: { maxWidth: '100%', overflowX: 'auto' as const, margin: '8px 0' },
  inlineCode: { padding: '1px 5px', borderRadius: 4, background: 'color-mix(in srgb, var(--misty-blue) 30%, transparent)', fontSize: '0.92em', fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace" },
  codeBlockWrap: { position: 'relative' as const, margin: '10px 0', borderRadius: 8, overflow: 'hidden', background: 'color-mix(in srgb, var(--misty-blue) 30%, transparent)', '& pre': { margin: 0, padding: '14px 16px', overflowX: 'auto' as const, fontSize: 13, fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace" } },
  codeCopyButton: { position: 'absolute' as const, top: 8, right: 8, zIndex: 1 },
  streamingCursor: { display: 'inline-block', width: 8, marginLeft: 2, color: token.colorPrimary, animation: 'cursorBlink 1s steps(1) infinite' },
  '@keyframes cursorBlink': { '0%, 100%': { opacity: 1 }, '50%': { opacity: 0 } },
  // ── 动画系统 ──────────────────────────────────────────────
  latestTurn: { animation: 'messageIn 300ms ease-out' },
  stepCardAnimated: { animation: 'stepIn 200ms ease-out', opacity: 0, animationFillMode: 'forwards' as const },
  thinkingPulse: { animation: 'thinkingPulse 1500ms ease-in-out infinite' },
  stepCardCompleteIcon: { transition: 'color 300ms ease-in-out', color: 'var(--desaturated-green)' },
  inputCursor: { display: 'inline-block', width: 2, height: 18, background: 'var(--accent-purple)', marginLeft: 1, animation: 'cursorBlink 1s steps(1) infinite', verticalAlign: 'middle' as const },
  // ── 头像系统 ──────────────────────────────────────────────
  avatarGroup: { display: 'flex', gap: 12, width: '100%', alignItems: 'flex-start' },
  userAvatarGroup: { display: 'flex', gap: 12, width: '100%', alignItems: 'flex-start', flexDirection: 'row-reverse' as const },
  avatarCol: { width: 32, flexShrink: 0 },
  avatarImg: { width: 32, height: 32, borderRadius: '50%', objectFit: 'cover' as const, flexShrink: 0 },
  avatarPlaceholder: {
    width: 32, height: 32, borderRadius: '50%',
    color: '#fff',
    fontSize: 14, fontWeight: 500,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0, userSelect: 'none' as const,
  },
  avatarNameRow: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4, minHeight: 20 },
  avatarName: { fontSize: 14, color: 'var(--earth-brown)', fontWeight: 500, lineHeight: '20px' },
  avatarUserIcon: {
    width: 32, height: 32, borderRadius: '50%',
    background: 'var(--sky-soft)',
    color: 'var(--earth-brown)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flexShrink: 0,
    '& .anticon': { fontSize: 16 },
  },
  groupContent: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const },
  userGroupContent: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const, alignItems: 'flex-end' as const },
  systemRow: { justifyContent: 'center' },

  // ── 开发者模式面板 ───────────────────────────────────────────
  devPanel: {
    width: 400,
    minWidth: 360,
    maxWidth: 440,
    display: 'flex',
    flexDirection: 'column' as const,
    borderLeft: '1px solid',
    borderColor: token.colorBorderSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 78%, transparent)',
    backdropFilter: 'blur(12px)',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 12,
    marginBottom: 12,
  },
  devPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    borderBottom: '1px solid',
    borderColor: token.colorBorderSecondary,
    fontSize: 13,
    fontWeight: 600,
  },
  devPanelTabs: {
    flex: 1,
    minHeight: 0,
    padding: '8px 10px 10px',
    '& .ant-tabs-content-holder': {
      overflow: 'auto',
    },
  },
  devPanelSection: { display: 'flex', flexDirection: 'column' as const, gap: 8 },
  devPanelLoading: { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '16px 0' },
  devLine: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, fontSize: 12 },
  devLayerTitle: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' },
  devPreview: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '8px 10px',
    fontSize: 12,
    lineHeight: 1.5,
  },
  devList: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  devListItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    background: token.colorFillQuaternary,
    borderRadius: 6,
    padding: '6px 8px',
  },
  devErrorText: { margin: 0, color: token.colorError },
  devPanelHint: { margin: 0, fontSize: 12, color: token.colorTextSecondary },
  subconsciousTimeline: {
    padding: '4px 0 8px',
    '& .ant-timeline-item': { paddingBottom: 12 },
    '& .ant-timeline-item-content': { fontSize: 13 },
  },
  devEventList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    maxHeight: '56vh',
    overflowY: 'auto' as const,
  },
  devEventItem: {
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '6px 8px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  devEventTime: { fontSize: 11, color: token.colorTextSecondary },
  devEventPayload: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    fontSize: 12,
    lineHeight: 1.5,
  },
  /* ── Stateful Motion: thinking, searching, memory, tool, error, success ── */
  '@keyframes neuralPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.8, transform: 'scale(1.02)' },
  },
  '@keyframes particleFlow': {
    '0%': { backgroundPosition: '0% 50%' },
    '100%': { backgroundPosition: '200% 50%' },
  },
  '@keyframes tokenStream': {
    '0%': { opacity: 0, transform: 'translateY(4px)' },
    '100%': { opacity: 1, transform: 'translateY(0)' },
  },
  '@keyframes waveScan': {
    '0%': { backgroundPosition: '-200% 50%' },
    '100%': { backgroundPosition: '200% 50%' },
  },
  '@keyframes breathe': {
    '0%, 100%': { opacity: 0.6, transform: 'scale(0.98)' },
    '50%': { opacity: 1, transform: 'scale(1)' },
  },
  '@keyframes ambientFloat': {
    '0%, 100%': { transform: 'translateY(0)' },
    '50%': { transform: 'translateY(-6px)' },
  },
  '@keyframes glitchShake': {
    '0%, 100%': { transform: 'translateX(0)' },
    '10%': { transform: 'translateX(-2px)' },
    '30%': { transform: 'translateX(2px)' },
    '50%': { transform: 'translateX(-1px)' },
    '70%': { transform: 'translateX(1px)' },
  },
  '@keyframes softDiffuse': {
    '0%': { boxShadow: '0 0 0 0 rgba(124,58,237,0)' },
    '50%': { boxShadow: '0 0 20px 4px rgba(124,58,237,0.12)' },
    '100%': { boxShadow: '0 0 0 0 rgba(124,58,237,0)' },
  },

  /* ── Ambient particles background (disabled for visual calm) ── */
  ambientLayer: {
    display: 'none',
  },

  /* ── Thinking state (animations removed for visual calm; @keyframes preserved) ── */
  agentThinking: {
    position: 'relative' as const,
  },

  /* ── Token streaming ── */
  tokenStreaming: {
    animation: 'tokenStream 0.2s ease-out',
    opacity: 1,
  },

  /* ── Searching / Tool running (wave-scan animation removed for visual calm) ── */
  agentSearching: {
    position: 'relative' as const,
  },

  /* ── Memory recall (animation removed for visual calm; @keyframes preserved) ── */
  agentRecall: {
  },

  /* ── Error ── */
  agentError: {
    animation: 'glitchShake 0.4s ease-in-out',
    borderLeft: '3px solid #ff4d4f',
  },

  /* ── Success ── */
  agentSuccess: {
    animation: 'softDiffuse 1s ease-in-out 1',
  },

  /* ── Breathing message card (animation removed for visual calm; @keyframes preserved) ── */
  breathingCard: {
    transition: 'all 0.3s ease',
  },

  /* ── Progressive disclosure ── */
  progressiveReveal: {
    overflow: 'hidden' as const,
    animation: 'revealDown 0.4s ease-out',
  },
  '@keyframes revealDown': {
    '0%': { maxHeight: 0, opacity: 0 },
    '100%': { maxHeight: 2000, opacity: 1 },
  },

  /* ── Reasoning stream (agent thinking chain) ── */
  reasoningStream: {
    whiteSpace: 'pre-wrap' as const,
    color: 'color-mix(in srgb, var(--accent-purple) 60%, var(--text-secondary))',
    fontSize: 12, lineHeight: 1.5, padding: '8px 10px',
    maxHeight: 300, overflowY: 'auto' as const,
    fontStyle: 'italic',
    borderLeft: '2px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    marginTop: 4,
    animation: 'tokenStream 0.3s ease-out',
  },

  /* ── Timeline reasoning block (统一时间线中的思维链条目) ── */
  reasoningBlockTimeline: {
    marginBottom: 8,
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 30%, transparent)',
    borderLeft: '3px solid var(--accent-purple, #7c3aed)',
    borderRadius: 6,
    overflow: 'hidden',
  },
  reasoningBlockContentTimeline: {
    padding: '8px 12px',
    fontSize: 12,
    fontStyle: 'italic',
    color: 'color-mix(in srgb, var(--accent-purple) 60%, #5c4a3a)',
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
  },
  reasoningFadeTimeline: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: 'linear-gradient(to bottom, transparent, #fafaf7)',
    pointerEvents: 'none' as const,
  },
  reasoningToggleTimeline: {
    padding: '4px 12px',
    fontSize: 11,
    color: 'var(--accent-purple)',
    cursor: 'pointer',
    borderTop: '1px solid rgba(124, 58, 237, 0.15)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
  },

  /* ── ContextMemoryIndicator ── */
  indicatorWrapper: { position: 'relative' as const },
  indicatorRing: {
    cursor: 'pointer', width: 34, height: 34,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    borderRadius: '50%', transition: 'all 0.2s',
    '&:hover': { background: 'rgba(139,92,246,0.12)', boxShadow: '0 0 12px rgba(139,92,246,0.2)' },
  },
  indicatorPulse: { animation: 'indicatorPulse 2s ease-in-out infinite' },
  indicatorSpin: { animation: 'indicatorSpin 3s linear infinite' },
  '@keyframes indicatorPulse': {
    '0%, 100%': { opacity: 0.4, transform: 'scale(1)' },
    '50%': { opacity: 0.9, transform: 'scale(1.3)' },
  },
  '@keyframes indicatorSpin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  // 悬浮窗 — 向右弹出，确保在视口内
  indicatorPopup: {
    position: 'fixed',
    bottom: 100,
    right: 24,
    width: 270,
    background: 'rgba(30,30,40,0.96)',
    backdropFilter: 'blur(20px)',
    borderRadius: 12,
    padding: 16,
    color: '#e2e8f0',
    border: '1px solid rgba(139,92,246,0.3)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.5), 0 0 20px rgba(139,92,246,0.15)',
    zIndex: 1000,
    fontSize: 12,
    whiteSpace: 'nowrap',
  },
  popupHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  popupTitle: { fontWeight: 600, fontSize: 13 },
  popupStatus: { display: 'flex', alignItems: 'center', gap: 6, opacity: 0.8 },
  popupDot: { width: 6, height: 6, borderRadius: '50%' },
  popupBody: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  popupRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  popupValue: { fontFamily: 'monospace', fontSize: 11, opacity: 0.8 },
  popupProgress: { height: 3, borderRadius: 2, background: 'rgba(255,255,255,0.1)', margin: '4px 0' },
  popupProgressBar: { height: '100%', borderRadius: 2, transition: 'width 0.5s ease' },
  popupWarning: { color: '#f97316', fontSize: 11, marginTop: 4, padding: '6px 8px', background: 'rgba(249,115,22,0.1)', borderRadius: 6 },

  /* ── First-token loading (animation removed for visual calm; @keyframes preserved) ── */
  preAnswerThinkingPanel: {
    width: '100%',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 8,
    borderTopLeftRadius: 4,
    background: 'color-mix(in srgb, var(--soft-white) 92%, transparent)',
    padding: '4px 0 10px',
    contain: 'paint',
  },
  firstTokenLoading: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px',
  },
  pulseDot: {
    width: 8, height: 8, borderRadius: '50%',
    background: 'var(--accent-purple)',
  },
  pulseLabel: {
    fontSize: 13, color: 'color-mix(in srgb, var(--accent-purple) 50%, var(--text-secondary))',
    fontStyle: 'italic',
  },
  preAnswerThinkingText: {
    margin: '0 16px',
    padding: '8px 10px',
    borderLeft: '2px solid color-mix(in srgb, var(--accent-purple) 22%, transparent)',
    color: 'var(--text-muted)',
    background: 'color-mix(in srgb, var(--accent-purple) 3%, transparent)',
    borderRadius: 6,
    fontSize: 12,
    lineHeight: 1.55,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    maxHeight: 96,
    overflow: 'hidden',
  },

  // ── IM-style MessageStream ──────────────────────────────────
  messageStream: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    padding: '8px 0',
  },
  messageRow: {
    display: 'flex',
    width: '100%',
    marginBottom: 2,
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAgent: {
    justifyContent: 'flex-start',
  },
  messageRowGrouped: {
    marginTop: -4,
  },
  // ── Agent 头像 ──
  agentAvatarWrapper: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: 16,
    userSelect: 'none' as const,
    overflow: 'hidden',
    marginTop: 18,
    marginRight: 10,
  },
  agentAvatarImg: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    objectFit: 'cover' as const,
  },
  agentAvatarGrouped: {
    visibility: 'hidden' as const,
    marginRight: 10,
    width: 32,
    flexShrink: 0,
  },
  // ── Agent 消息容器 ──
  agentMessageContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-start',
    maxWidth: '82%',
    minWidth: 0,
  },
  // ── Agent 名称时间行 ──
  agentNameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
    paddingLeft: 4,
    minHeight: 20,
  },
  agentNameText: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--earth-brown)',
    lineHeight: '20px',
  },
  agentTimeText: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    lineHeight: '20px',
  },
  // ── Agent 气泡 ──
  agentBubbleNew: {
    background: 'var(--soft-white)',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 8,
    borderTopLeftRadius: 4,
    padding: '12px 16px',
    fontSize: 14,
    lineHeight: 1.7,
    color: 'var(--text-primary)',
    wordBreak: 'break-word' as const,
    width: '100%',
    transition: 'background 200ms ease, border-color 200ms ease',
    '&:hover': {
      background: 'color-mix(in srgb, var(--soft-white) 95%, transparent)',
      borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    },
  },
  agentBubbleGrouped: {
    borderTopLeftRadius: 8,
    borderTop: '1px solid',
    borderTopColor: 'color-mix(in srgb, var(--earth-brown) 4%, transparent)',
  },
  agentBubbleStreaming: {
    borderColor: 'color-mix(in srgb, var(--accent-purple) 20%, transparent)',
  },
  agentBubbleError: {
    borderColor: 'color-mix(in srgb, #ef4444 30%, transparent)',
    background: 'color-mix(in srgb, #ef4444 4%, var(--soft-white))',
  },
  // ── 用户消息（带头像、名称、右对齐气泡）──
  userMessageContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end',
    maxWidth: '70%',
    minWidth: 0,
  },
  userMetaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
    paddingRight: 40, // 为右侧头像留位，保持名称/时间与气泡对齐
    minHeight: 20,
  },
  userNameText: {
    fontSize: 13,
    color: 'var(--earth-brown)',
    opacity: 0.7,
    lineHeight: '20px',
  },
  userTimeText: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    lineHeight: '20px',
  },
  userBubbleRow: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 8,
    maxWidth: '100%',
  },
  userBubbleArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'flex-end',
    minWidth: 0,
    flex: '0 1 auto',
  },
  userBubbleNew: {
    background: 'color-mix(in srgb, var(--accent-purple) 8%, var(--soft-white))',
    border: '1.5px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 28%, transparent)',
    borderRadius: 10,
    borderBottomRightRadius: 4,
    padding: '10px 16px',
    fontSize: 14,
    lineHeight: 1.6,
    color: 'var(--text-primary)',
    wordBreak: 'break-word' as const,
    transition: 'background 200ms ease',
    '&:hover': {
      background: 'color-mix(in srgb, var(--accent-purple) 14%, var(--soft-white))',
    },
  },
  userBubbleSending: {
    opacity: 0.7,
  },
  userSendingIndicator: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    marginTop: 2,
    paddingRight: 4,
  },
  userAvatarShell: {
    flex: '0 0 auto',
  },
  userAvatarImg: {
    border: '2px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 20%, transparent)',
  },
  userAvatarFallback: {
    background: 'color-mix(in srgb, var(--accent-purple) 15%, var(--soft-white))',
    color: 'var(--accent-purple)',
    border: '2px solid',
    borderColor: 'color-mix(in srgb, var(--accent-purple) 20%, transparent)',
  },
  // ── 过程摘要（默认折叠）───────────────────────────────────
  processSummaryRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '4px 4px 0',
    cursor: 'pointer' as const,
    userSelect: 'none' as const,
    transition: 'opacity 200ms ease',
    '&:hover': {
      opacity: 0.8,
    },
  },
  processSummaryDot: {
    width: 4,
    height: 4,
    borderRadius: '50%',
    background: 'var(--earth-brown)',
    opacity: 0.3,
    flexShrink: 0,
  },
  processSummaryText: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    lineHeight: '16px',
  },
  processSummaryLink: {
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.6,
    cursor: 'pointer' as const,
    lineHeight: '16px',
    '&:hover': {
      opacity: 1,
      textDecoration: 'underline',
    },
  },
  processThinkingLabel: {
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.6,
    fontStyle: 'italic',
    lineHeight: '16px',
  },
  processRetryBtn: {
    fontSize: 11,
    color: '#ef4444',
    cursor: 'pointer' as const,
    opacity: 0.7,
    lineHeight: '16px',
    background: 'none',
    border: 'none',
    padding: 0,
    '&:hover': {
      opacity: 1,
      textDecoration: 'underline',
    },
  },
  // ── 过程展开区 ──
  processExpandedArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    marginTop: 4,
    paddingLeft: 12,
    borderLeft: '2px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
  },
  processCollapseLink: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.4,
    cursor: 'pointer' as const,
    padding: '2px 4px',
    userSelect: 'none' as const,
    '&:hover': {
      opacity: 0.7,
    },
  },
  processItem: {
    fontSize: 12,
    color: 'var(--earth-brown)',
    opacity: 0.6,
    lineHeight: 1.5,
    padding: '3px 4px',
  },
  processItemName: {
    fontWeight: 500,
    opacity: 0.8,
  },
  processItemStatus: {
    fontSize: 10,
    marginLeft: 6,
  },
  processItemStatusRunning: {
    color: 'var(--accent-purple)',
  },
  processItemStatusSuccess: {
    color: '#22c55e',
  },
  processItemStatusError: {
    color: '#ef4444',
  },
  processItemDetail: {
    fontSize: 11,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    marginTop: 2,
    padding: '4px 6px',
    background: 'color-mix(in srgb, var(--earth-brown) 4%, transparent)',
    borderRadius: 4,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    maxHeight: 200,
    overflowY: 'auto' as const,
  },
  processItemToggle: {
    fontSize: 11,
    color: 'var(--accent-purple)',
    opacity: 0.5,
    cursor: 'pointer' as const,
    padding: '2px 4px',
    '&:hover': {
      opacity: 0.8,
    },
  },
  // ── 消息操作按钮 ──
  messageActionsNew: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    padding: '2px 4px 0',
    opacity: 0,
    transition: 'opacity 180ms ease',
  },
  messageActionsVisible: {
    opacity: 0.6,
  },
  messageActionBtn: {
    width: 24,
    height: 24,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: 'transparent',
    borderRadius: 4,
    cursor: 'pointer' as const,
    color: 'var(--earth-brown)',
    opacity: 0.5,
    fontSize: 13,
    transition: 'opacity 120ms ease, background 120ms ease',
    '&:hover': {
      opacity: 1,
      background: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    },
  },
  messageActionBtnDanger: {
    '&:hover': {
      color: '#ef4444',
      opacity: 1,
    },
  },
  // ── Token 用量 ──
  tokenUsageLine: {
    fontSize: 10,
    color: 'var(--earth-brown)',
    opacity: 0.35,
    padding: '2px 4px 0',
  },

  // ── Composer Surface（安静单行输入区）────────────────────
  composerSurface: {
    position: 'sticky' as const,
    bottom: 0,
    background: 'var(--pudding-surface, #fffefa)',
    border: '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 14%, transparent)',
    borderRadius: 8,
    padding: '8px 10px 6px',
    boxShadow: 'none',
    zIndex: 10,
    margin: '0 0 4px',
    overflow: 'visible' as const,
    transition: 'border-color 180ms ease, box-shadow 180ms ease',
    /* ink-line */
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      bottom: -1,
      left: '20%',
      width: '36%',
      height: 2,
      borderRadius: 1,
      background: 'color-mix(in srgb, var(--accent-purple, #8b5cf6) 24%, transparent)',
      opacity: 0,
      transform: 'translateX(-10px)',
      transition: 'opacity 220ms ease, transform 220ms ease',
      pointerEvents: 'none' as const,
    },
    '&[data-active="true"]': {
      borderColor: 'color-mix(in srgb, var(--accent-purple, #8b5cf6) 20%, var(--earth-brown, #5c4a3a) 12%)',
      boxShadow: '0 2px 10px rgba(92, 64, 42, 0.05)',
    },
    '&[data-active="true"]::after': {
      opacity: 1,
      transform: 'translateX(0)',
    },
    '&[data-error="true"]': {
      borderColor: 'color-mix(in srgb, #c4944c 40%, transparent)',
      boxShadow: '0 2px 10px rgba(196, 148, 76, 0.06)',
    },
    '&[data-active="true"][data-error="true"]::after': {
      opacity: 0,
    },
    /* prefers-reduced-motion: 禁用 ink-line 动画，只保留颜色 */
    '@media (prefers-reduced-motion: reduce)': {
      '&::after': {
        transition: 'none',
        opacity: 0,
      },
    },
  },
  composerStatusLine: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    minHeight: 18,
    marginBottom: 4,
    fontSize: 11,
    color: 'var(--pudding-text-muted, #756b5f)',
  },
  composerStatusDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerRow: {
    display: 'grid',
    gridTemplateColumns: '124px minmax(0, 1fr) 36px',
    columnGap: 6,
    alignItems: 'end',
    minHeight: 32,
    overflow: 'visible' as const,
  },
  composerToolArea: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    alignSelf: 'end',
    width: 124,
    minWidth: 124,
    overflow: 'visible' as const,
  },
  composerActionArea: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
    alignSelf: 'end',
    width: 36,
    minWidth: 36,
    minHeight: 32,
    overflow: 'visible' as const,
  },
  composerIconButton: {
    width: 32,
    minWidth: 32,
    height: 32,
    minHeight: 32,
    padding: 0,
    opacity: 0.58,
    border: 'none',
    background: 'transparent',
    flexShrink: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
    borderRadius: 8,
  },
  composerTextarea: {
    display: 'block',
    width: '100%',
    border: 'none',
    background: 'transparent',
    boxShadow: 'none',
    resize: 'none' as const,
    fontSize: 14,
    lineHeight: 1.55,
    padding: '5px 8px',
    outline: 'none',
    minWidth: 0,
    minHeight: 32,
    maxHeight: 112,
    overflowY: 'auto' as const,
    '&:focus': {
      boxShadow: 'none',
    },
  },

  // ── Composer Action Menu（`+` Popover）─────────────────────
  composerMenu: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    padding: '4px 0',
    minWidth: 220,
  },
  composerMenuSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 1,
    padding: '4px 0',
  },
  composerMenuSectionTitle: {
    padding: '4px 12px 6px',
    fontSize: 11,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontWeight: 500,
    opacity: 0.6,
    userSelect: 'none' as const,
  },
  composerMenuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    height: 36,
    padding: '0 12px',
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--pudding-text, #1d1b24)',
    fontSize: 13,
    cursor: 'pointer' as const,
    transition: 'background 0.15s',
    textAlign: 'left' as const,
    '&:hover:not(:disabled)': {
      background: 'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: -2,
    },
    '& .anticon': {
      fontSize: 14,
      flexShrink: 0,
    },
  },
  composerMenuItemDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed' as const,
  },
  composerMenuComingSoon: {
    marginLeft: 'auto',
    fontSize: 10,
    color: 'var(--pudding-text-muted, #756b5f)',
    opacity: 0.5,
  },
  composerMenuValue: {
    marginLeft: 'auto',
    fontSize: 12,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontVariantNumeric: 'tabular-nums' as const,
  },

  // ── Composer Feedback Strip（轻反馈带）─────────────────────
  composerFeedbackStrip: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap' as const,
    gap: 2,
    minHeight: 18,
    padding: '2px 0 0',
    cursor: 'pointer' as const,
    userSelect: 'none' as const,
    '&:hover .composerFeedbackLabel': {
      opacity: 0.8,
    },
  },
  composerFeedbackSep: {
    color: 'var(--earth-brown, #5c4a3a)',
    opacity: 0.2,
    fontSize: 11,
    margin: '0 1px',
    userSelect: 'none' as const,
  },
  composerFeedbackItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '1px 4px',
    borderRadius: 3,
    transition: 'background 0.15s',
    '&:hover': {
      background: 'color-mix(in srgb, var(--earth-brown, #5c4a3a) 5%, transparent)',
    },
  },
  composerFeedbackDot: {
    width: 5,
    height: 5,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerFeedbackLabel: {
    fontSize: 11,
    color: 'var(--earth-brown, #5c4a3a)',
    opacity: 0.55,
    whiteSpace: 'nowrap' as const,
    transition: 'opacity 0.15s',
  },

  // ── Composer Status Pill（状态行胶囊）─────────────────────────
  composerStatusPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    cursor: 'pointer' as const,
    borderRadius: 4,
    padding: '2px 6px',
    transition: 'background 0.15s',
    '&:hover': {
      background: 'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: 1,
    },
  },

  // ── Composer Status Details Popover ─────────────────────────
  composerStatusDetails: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    padding: '4px 0',
    minWidth: 220,
    maxWidth: 280,
  },
  composerStatusDetailsHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '4px 12px 8px',
    borderBottom: '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 10%, transparent)',
    marginBottom: 4,
  },
  composerStatusDetailsDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    flexShrink: 0,
  },
  composerStatusDetailsTitle: {
    fontSize: 13,
    fontWeight: 500,
    color: 'var(--pudding-text, #1d1b24)',
  },
  composerStatusDetailsGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    padding: '0 12px',
  },
  composerStatusDetailsGroupTitle: {
    fontSize: 10,
    color: 'var(--pudding-text-muted, #756b5f)',
    fontWeight: 500,
    opacity: 0.5,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    marginBottom: 2,
  },
  composerStatusDetailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    minHeight: 22,
  },
  composerStatusDetailLabel: {
    fontSize: 12,
    color: 'var(--pudding-text-muted, #756b5f)',
    flexShrink: 0,
  },
  composerStatusDetailValue: {
    fontSize: 12,
    color: 'var(--pudding-text, #1d1b24)',
    fontVariantNumeric: 'tabular-nums' as const,
    textAlign: 'right' as const,
  },
  composerStatusDetailsDevEntry: {
    borderTop: '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 10%, transparent)',
    padding: '6px 12px 2px',
    marginTop: 4,
  },
  composerStatusDetailsDevButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    width: '100%',
    height: 32,
    padding: '0 8px',
    border: 'none',
    borderRadius: 6,
    background: 'transparent',
    color: 'var(--pudding-text-muted, #756b5f)',
    fontSize: 12,
    cursor: 'pointer' as const,
    transition: 'background 0.15s',
    textAlign: 'left' as const,
    '&:hover': {
      background: 'color-mix(in srgb, var(--earth-brown, #5c4a3a) 6%, transparent)',
      color: 'var(--pudding-text, #1d1b24)',
    },
    '&:focus-visible': {
      outline: '2px solid var(--pudding-accent, #8b5cf6)',
      outlineOffset: -2,
    },
    '& .anticon': {
      fontSize: 12,
    },
  },

  // ── Runtime Timeline 样式 ──────────────────────────────────
  timeline: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    position: 'relative' as const,
    paddingLeft: 16,
    animation: 'fadeIn 200ms ease-out',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 4,
      top: 0,
      bottom: 0,
      width: 2,
      background: 'var(--earth-brown, rgba(120,100,80,0.10))',
      borderRadius: 1,
    },
  },
  timelineUserMsg: {
    fontSize: 14,
    color: 'var(--text-primary)',
    padding: '4px 0 8px',
    position: 'relative' as const,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 6,
      height: 6,
      borderRadius: '50%',
      background: 'var(--accent-purple, #7c3aed)',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  timelineUserLabel: {
    display: 'inline-block',
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.6,
    marginBottom: 2,
    marginRight: 8,
  },
  timelineNode: {
    position: 'relative' as const,
    padding: '6px 0 6px 12px',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -14,
      top: 10,
      width: 8,
      height: 8,
      borderRadius: '50%',
      border: '2px solid var(--neural-line, rgba(124,58,237,0.18))',
      background: 'var(--warm-beige)',
      zIndex: 1,
    },
  },
  timelineNodeThinking: {
    opacity: 0.65,
    fontStyle: 'italic',
    fontSize: 12,
    borderLeft: '2px solid var(--memory-glow, #A78BFA)',
  },
  timelineNodeTool: {
    borderLeft: '2px solid var(--tool-signal, #22D3EE)',
  },
  timelineNodeToolRunning: {
    borderLeft: '2px solid var(--earth-brown)',
    '&::before': {
      animation: 'signalFlow 2s linear infinite',
      background: 'var(--earth-brown)',
      boxShadow: '0 0 6px color-mix(in srgb, var(--misty-blue) 40%, transparent)',
      backgroundSize: '200% 100%',
    },
  },
  timelineNodeToolDone: {
    borderLeftColor: 'var(--success-signal, #22C55E)',
  },
  timelineNodeToolFailed: {
    borderLeftColor: 'var(--error-signal, #EF4444)',
  },
  timelineNodeAnswer: {
    borderLeft: 'none',
    padding: '8px 0 8px 0',
    marginLeft: -12,
  },
  timelineAnswerBlock: {
    background: 'var(--soft-white)',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    borderRadius: 12,
    padding: '14px 18px',
    fontSize: 15,
    lineHeight: 1.7,
    color: 'var(--text-primary)',
  },
  /* ── 块级凝聚：新内容块 fade-in + 光晕扩散 ── */
  blockCondensing: {
    animation: 'blockCondense 360ms ease-out',
  },
  /* ── 单字符 fade-in（120ms opacity 0→1）── */
  charFadeIn: {
    animation: 'charFade 120ms ease-out',
  },
  '@keyframes charFade': {
    '0%': { opacity: 0 },
    '100%': { opacity: 1 },
  },
  /* ── Settle：流式结束后的收敛动画 ── */
  answerSettled: {
    animation: 'glowSettle 800ms ease-out',
  },
  /* ── 流式输出中段落间呼吸节奏 (animation removed for visual calm; @keyframes preserved) ── */
  streamingBreathe: {
  },
  '@keyframes streamBreathe': {
    '0%, 100%': { opacity: 1 },
    '50%': { opacity: 0.92 },
  },
  /* ── ADR-InkBloom: 纸感卡片（流式中）── */
  paperStreaming: {
    background: 'color-mix(in srgb, var(--soft-white) 92%, #fff7df)',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 8%, transparent)',
    boxShadow: '0 1px 8px rgba(92, 64, 42, 0.04)',
    transition: 'background 420ms ease, border-color 420ms ease, box-shadow 520ms ease',
    contain: 'paint',
  },
  /* ── ADR-InkBloom: 纸感卡片（已稳定）── */
  paperSettled: {
    background: 'var(--soft-white)',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    boxShadow: 'none',
    transition: 'background 520ms ease, border-color 520ms ease, box-shadow 520ms ease',
  },
  /* ── ADR-InkBloom: 墨迹 live text 容器 ── */
  typewriterLiveText: {
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  /* ── ADR-InkBloom: 墨迹 chunk 淡入动画 ── */
  inkChunk: {
    display: 'inline' as const,
    animation: 'inkBloom 180ms ease-out both',
  },
  '@keyframes inkBloom': {
    '0%': { opacity: 0.12, color: 'color-mix(in srgb, var(--text-primary) 35%, #d8c7a5)', transform: 'translateY(1px)' },
    '100%': { opacity: 1, color: 'var(--text-primary)', transform: 'translateY(0)' },
  },
  /* ── ADR-InkBloom: 墨迹光标 ── */
  inkCursor: {
    display: 'inline-block' as const,
    width: 2,
    height: '1em',
    marginLeft: 2,
    verticalAlign: '-0.12em',
    background: 'color-mix(in srgb, var(--earth-brown) 55%, transparent)',
    animation: 'inkCursorBreath 1.4s ease-in-out infinite',
  },
  '@keyframes inkCursorBreath': {
    '0%, 100%': { opacity: 0.28 },
    '50%': { opacity: 0.75 },
  },
  /* ── ADR-InkBloom: prefers-reduced-motion 禁用动画 ── */
  '@media (prefers-reduced-motion: reduce)': {
    inkChunk: { animation: 'none' as const },
    inkCursor: { animation: 'none' as const },
  },
  /* ── 操作按钮 settle 淡入 ── */
  actionButtonsSettled: {
    opacity: '1 !important' as unknown as number,
    transform: 'translateY(0) !important' as unknown as string,
    pointerEvents: 'auto !important' as unknown as React.CSSProperties['pointerEvents'],
    transition: 'opacity 400ms ease-out, transform 400ms ease-out',
  },

  /* ── Runtime 状态机视觉映射（P1-2）────────────────────── */
  runtimeStateThinking: {
    borderLeft: '2px solid var(--memory-glow, #A78BFA)',
    background: 'color-mix(in srgb, var(--memory-glow) 2%, transparent)',
  },
  runtimeStateMemory: {
    borderLeft: '2px solid var(--memory-glow, #A78BFA)',
    animation: 'softDiffuse 2s ease-in-out infinite',
  },
  runtimeStateTool: {
    borderLeft: '3px solid var(--tool-signal, #22D3EE)',
  },
  runtimeStateToolRunning: {
    borderLeft: '3px solid var(--tool-signal, #22D3EE)',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: -3,
      top: 0,
      bottom: 0,
      width: 3,
      background: 'linear-gradient(180deg, transparent, var(--tool-signal, #22D3EE), transparent)',
      backgroundSize: '100% 200%',
      animation: 'signalFlow 1.5s linear infinite',
    },
  },
  runtimeStateStreaming: {
    borderLeft: '3px solid var(--accent-purple, #7c3aed)',
  },
  runtimeStateSuccess: {
    borderLeftColor: 'var(--success-signal, #22C55E)',
    transition: 'border-left-color 400ms ease',
  },
  runtimeStateError: {
    borderLeftColor: 'var(--error-signal, #EF4444)',
  },
  /* ── 状态文案颜色映射 ── */
  statusTextThinking: { color: 'var(--earth-brown)' },
  statusTextMemory: { color: 'var(--earth-brown)' },
  statusTextTool: { color: 'var(--tool-signal, #22D3EE)' },
  statusTextStreaming: { color: 'var(--accent-purple, #7c3aed)' },
  statusTextSuccess: { color: 'var(--success-signal, #22C55E)' },
  statusTextError: { color: 'var(--error-signal, #EF4444)' },
  timelineNodeAppear: {
    animation: 'nodeAppear 300ms ease-out',
  },
  collapsedSummary: {
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.55,
    cursor: 'pointer',
    transition: 'opacity 150ms',
    '&:hover': { opacity: 0.85 },
  },
  thinkingSummaryText: {
    fontSize: 12,
    color: 'var(--text-muted)',
    fontStyle: 'italic',
    opacity: 0.65,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: '100%',
    cursor: 'pointer',
  },
  thinkingExpandedText: {
    fontSize: 12,
    color: 'var(--text-muted)',
    fontStyle: 'italic',
    lineHeight: 1.5,
    padding: '6px 8px',
    background: 'color-mix(in srgb, var(--memory-glow) 6%, transparent)',
    borderRadius: 6,
    marginTop: 4,
    maxHeight: 200,
    overflowY: 'auto' as const,
  },
  toolSummaryRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    fontSize: 12,
  },
  toolSummaryName: {
    fontWeight: 600,
    color: 'var(--tool-signal, #22D3EE)',
  },
  toolSummaryStatus: {
    fontSize: 11,
    opacity: 0.7,
  },
  toolSummaryDuration: {
    fontSize: 11,
    color: 'var(--text-muted)',
    opacity: 0.6,
    marginLeft: 'auto',
  },
  toolSummaryResult: {
    fontSize: 11,
    color: 'var(--success-signal, #22C55E)',
    opacity: 0.8,
  },
  toolRetryBtn: {
    fontSize: 11,
    color: 'var(--error-signal, #EF4444)',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    padding: 0,
    ':hover': { textDecoration: 'underline' },
  },

  /* ── P0：折叠状态下的单一主状态行 ── */
  mainStatusLine: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '6px 12px', fontSize: 13,
    color: 'var(--earth-brown)', opacity: 0.7,
  },
  mainStatusDot: {
    width: 6, height: 6, borderRadius: '50%',
    background: 'var(--accent-purple)', opacity: 0.5,
  },
  mainStatusDotActive: {
    animation: 'pulseDotActive 1.5s ease-in-out infinite',
  },
  '@keyframes pulseDotActive': {
    '0%, 100%': { opacity: 0.3 },
    '50%': { opacity: 0.8 },
  },
  /** 完成后摘要行 */
  completionSummary: {
    display: 'flex', alignItems: 'center', gap: 8,
    padding: '4px 12px', fontSize: 12,
    color: 'var(--earth-brown)', opacity: 0.5,
  },
  viewProcessLink: {
    cursor: 'pointer', color: 'var(--accent-purple)',
    fontSize: 12, userSelect: 'none' as const,
    '&:hover': { opacity: 0.8 },
  },
  collapseProcessLink: {
    cursor: 'pointer', color: 'var(--accent-purple)',
    fontSize: 12, userSelect: 'none' as const,
    padding: '0 0 4px 0',
    '&:hover': { opacity: 0.8 },
  },

  /* ── 无障碍：prefers-reduced-motion 支持 ── */
  '@media (prefers-reduced-motion: reduce)': {
    '*, *::before, *::after': {
      animationDuration: '0.01ms !important',
      animationIterationCount: '1 !important',
      transitionDuration: '0.01ms !important',
    } as unknown as React.CSSProperties,
  } as unknown as React.CSSProperties,
}));

