// ── 聊天页样式（antd-style createStyles — 组合模式）─────────────────────
import { createStyles } from 'antd-style';
import { useLayoutStyles } from './styles/layout.styles';
import { useMessageStyles } from './styles/message.styles';
import { useAgentStyles } from './styles/agent.styles';
import { useUserStyles } from './styles/user.styles';
import { useProcessStyles } from './styles/process.styles';
import { useReasoningStyles } from './styles/reasoning.styles';
import { useMarkdownStyles } from './styles/markdown.styles';
import { useComposerStyles } from './styles/composer.styles';
import { usePanelStyles } from './styles/panel.styles';
import { useVoiceStyles } from './styles/voice.styles';
import { useHeartbeatStyles } from './styles/heartbeat.styles';
import { useStatusStyles } from './styles/status.styles';
import { useDevpanelStyles } from './styles/devpanel.styles';
import { useAnimationStyles } from './styles/animations.styles';
import { useSidebarStyles } from './styles/sidebar.styles';

export const SIDEBAR_WIDTH = 260;

// Residual styles kept inline (sidebar, workspace studio, dev panel,
// heartbeat, animations, misc — not yet split into modules)
const useResidualStyles = createStyles(({ token }) => ({
  sidebar: {
    width: SIDEBAR_WIDTH,
    minWidth: SIDEBAR_WIDTH,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid',
    borderColor: 'var(--pudding-chat-border)',
    background: 'var(--pudding-chat-sidebar-bg)',
    backdropFilter: 'blur(12px)',
    transition:
      'width 0.2s ease, min-width 0.2s ease, border 0.2s ease, background 0.18s ease',
    overflow: 'hidden',
  },
  sidebarCollapsed: { width: 0, minWidth: 0, borderRight: 'none' },
  sidebarHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: '1px solid',
    borderColor: 'var(--pudding-chat-border)',
  },
  sidebarTitleBlock: { minWidth: 0, flex: 1 },
  sidebarTitle: {
    fontSize: 14,
    fontWeight: 650,
    lineHeight: '18px',
    color: 'var(--pudding-chat-text)',
  },
  sidebarSubtitle: {
    marginTop: 1,
    fontSize: 11,
    lineHeight: '14px',
    color: 'var(--pudding-chat-text-subtle)',
  },
  sidebarIconBtn: {
    width: 28,
    height: 28,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--pudding-chat-text)',
  },
  sidebarNewBtn: {
    flex: 1,
    justifyContent: 'flex-start',
    fontSize: 13,
    fontWeight: 500,
  },
  sidebarSearch: {
    padding: '8px 12px 4px',
    '& .ant-input': {
      background: 'var(--pudding-chat-surface)',
      color: 'var(--pudding-chat-text)',
      backdropFilter: 'blur(12px)',
      borderRadius: 8,
      border: '1px solid',
      borderColor: 'var(--pudding-chat-border)',
    },
  },
  agentContactList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    padding: '8px',
    borderBottom: '1px solid var(--pudding-chat-border)',
  },
  agentContactItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    minHeight: 54,
    padding: '8px',
    border: 0,
    borderRadius: 8,
    background: 'transparent',
    color: 'var(--pudding-chat-text)',
    cursor: 'pointer' as const,
    textAlign: 'left' as const,
    transition: 'background 0.15s, opacity 0.15s',
    '&:hover:not(:disabled)': {
      background: 'var(--pudding-chat-surface-muted)',
    },
    '&:disabled': { cursor: 'not-allowed' as const, opacity: 0.55 },
  },
  agentContactItemActive: {
    background: 'var(--pudding-chat-accent-soft)',
  },
  agentContactAvatar: {
    flexShrink: 0,
    color: 'var(--pudding-chat-surface)',
    fontWeight: 650,
  },
  agentContactBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    minWidth: 0,
    flex: 1,
  },
  agentContactName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 13,
    fontWeight: 560,
    lineHeight: '18px',
  },
  agentContactMeta: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 11,
    color: 'var(--pudding-chat-text-subtle)',
    lineHeight: '14px',
  },
  sidebarSecondaryLabel: {
    padding: '8px 4px 2px',
    fontSize: 11,
    lineHeight: '14px',
    fontWeight: 650,
    color: 'var(--pudding-chat-text-subtle)',
  },
  sidebarEmptyInline: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 32,
    padding: '6px 8px',
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
    lineHeight: '18px',
  },
  sessionDetailArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    flex: 1,
    minHeight: 0,
  },
  sessionDetailHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 16px 4px',
    color: 'var(--pudding-chat-text-subtle)',
    fontSize: 12,
    fontWeight: 600,
  },
  sessionList: { flex: 1, overflowY: 'auto' as const, padding: '4px 8px' },
  groupLabel: {
    padding: '16px 8px 4px',
    fontSize: 11,
    fontWeight: 600,
    color: 'var(--pudding-chat-text-subtle)',
    opacity: 0.8,
    textTransform: 'uppercase' as const,
  },
  sessionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 16px',
    borderRadius: token.borderRadius,
    cursor: 'pointer',
    fontSize: 13,
    color: token.colorTextSecondary,
    transition: 'background 0.15s',
    overflow: 'hidden',
    minHeight: 48,
    '&:hover': { background: token.colorFillQuaternary },
  },
  sessionItemActive: {
    background: 'var(--pudding-chat-accent-soft)',
    color: 'var(--pudding-chat-text)',
    fontWeight: 500,
    borderLeft: '3px solid var(--pudding-chat-accent)',
    paddingLeft: 13,
  },
  sessionItemArchived: { opacity: 0.5 },
  sessionTitle: {
    flex: 1,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
  },
  avatarRuntimeRail: {
    flex: '0 0 188px',
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingTop: 12,
    minHeight: 0,
    overflow: 'hidden',
    '@media (max-width: 1023px)': {
      display: 'none',
    },
  },
  workspaceStudioPanel: {
    flexShrink: 0,
    margin: '12px 0 0',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 14%, transparent)',
    borderRadius: 8,
    overflow: 'hidden',
    background: 'color-mix(in srgb, var(--soft-white) 78%, transparent)',
  },
  workspaceStudioPanelPage: {
    margin: 0,
    width: 'auto',
    maxWidth: '100%',
    height: 'min(calc(100vh - 79px), calc((100vw - 36px) * 0.625))',
    maxHeight: 'calc(100vh - 79px)',
    aspectRatio: '16 / 10',
    minHeight: 0,
    border: 0,
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
  },
  workspaceStudioHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: 34,
    padding: '7px 10px',
    borderBottom: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    flexWrap: 'wrap' as const,
  },
  workspaceStudioHeaderPage: {
    position: 'absolute' as const,
    left: 34,
    top: 24,
    zIndex: 5,
    maxWidth: 360,
    minHeight: 36,
    padding: '7px 10px',
    border: '1px solid rgba(89, 62, 39, 0.18)',
    borderRadius: 6,
    background: 'rgba(255, 246, 224, 0.76)',
    backdropFilter: 'blur(8px)',
    boxShadow: '0 8px 18px rgba(70, 45, 28, 0.12)',
    '@media (max-width: 1080px)': {
      position: 'relative' as const,
      left: 'auto',
      top: 'auto',
      maxWidth: 'none',
      marginBottom: 10,
    },
  },
  workspaceStudioHeaderCopy: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
    minWidth: 0,
  },
  workspaceStudioTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  workspaceStudioMeta: {
    fontSize: 12,
    color: 'var(--earth-brown)',
    opacity: 0.72,
    whiteSpace: 'nowrap' as const,
  },
  workspaceStudioStateSummary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    flexWrap: 'wrap' as const,
  },
  workspaceStudioStateChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 22,
    padding: '2px 7px',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    borderRadius: 6,
    background: 'color-mix(in srgb, var(--soft-white) 72%, transparent)',
    color: 'var(--text-secondary)',
    fontSize: 12,
    lineHeight: '16px',
    whiteSpace: 'nowrap' as const,
    '&[data-agent-state="working"]': {
      color: '#4f714e',
      background: 'rgba(125, 151, 105, 0.16)',
      borderColor: 'rgba(95, 127, 98, 0.22)',
    },
    '&[data-agent-state="sleeping"]': {
      color: '#71677f',
      background: 'rgba(132, 121, 154, 0.13)',
      borderColor: 'rgba(113, 103, 127, 0.18)',
    },
    '&[data-agent-state="playing"]': {
      color: '#8a6428',
      background: 'rgba(174, 132, 62, 0.13)',
      borderColor: 'rgba(164, 119, 50, 0.18)',
    },
  },
  workspaceStudioRoom: {
    position: 'relative' as const,
    minHeight: 154,
    overflow: 'hidden',
    background: '#2b1d15',
    isolation: 'isolate' as const,
    imageRendering: 'pixelated' as const,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      inset: 0,
      zIndex: 0,
      pointerEvents: 'none' as const,
      background:
        'linear-gradient(90deg, transparent 0 49%, rgba(255,244,216,.04) 49% 50%, transparent 50% 100%), linear-gradient(0deg, transparent 0 49%, rgba(83,51,31,.05) 49% 50%, transparent 50% 100%)',
      backgroundSize: '16px 16px',
      mixBlendMode: 'soft-light' as const,
      opacity: 0.4,
    },
    '@media (max-width: 767px)': { minHeight: 132 },
  },
  workspaceStudioGameRoom: {
    background: '#efe8dc',
    '&::before': {
      display: 'none',
    },
    '& canvas': {
      display: 'block',
      imageRendering: 'pixelated' as const,
    },
  },
  workspaceStudioRoomPage: {
    height: '100%',
    minHeight: 0,
    aspectRatio: '16 / 10',
    borderRadius: 0,
    boxShadow: 'inset 0 0 0 1px rgba(58,37,26,.12)',
    '& [data-studio-agent]': {
      transform: 'scale(1.26)',
    },
    '@media (max-width: 767px)': {
      minHeight: 520,
      '& [data-studio-agent]': {
        transform: 'scale(1.06)',
      },
    },
  },
  workspaceStudioTileLayer: {
    position: 'absolute' as const,
    inset: '18px',
    display: 'grid',
    gridTemplateColumns:
      'repeat(var(--workspace-studio-tile-columns), minmax(0, 1fr))',
    gridTemplateRows:
      'repeat(var(--workspace-studio-tile-rows), minmax(0, 1fr))',
    border: '6px solid #d88b52',
    borderRadius: 4,
    boxShadow:
      '0 7px 0 #8b5638, 0 0 0 4px #3a251a, 0 20px 38px rgba(112,70,39,.18), inset 0 0 0 2px rgba(92,53,30,.18)',
    overflow: 'hidden',
    zIndex: 0,
    '@media (max-width: 767px)': {
      inset: 8,
      borderWidth: 4,
      boxShadow:
        '0 5px 0 #8b5638, 0 0 0 3px #3a251a, inset 0 0 0 2px rgba(92,53,30,.18)',
    },
  },
  workspaceStudioTile: {
    position: 'relative' as const,
    minWidth: 0,
    minHeight: 0,
    background: '#c99f68',
    boxShadow:
      'inset 1px 0 rgba(255,255,255,.08), inset 0 1px rgba(255,255,255,.08)',
    '&[data-studio-tile="wall-corner"]': {
      background: '#d88b52',
      boxShadow:
        'inset -4px -4px 0 rgba(119,66,42,.24), inset 3px 3px 0 rgba(255,224,164,.34)',
    },
    '&[data-studio-tile="wall-top"]': {
      background:
        'linear-gradient(180deg, #f2aa62 0%, #d88b52 62%, #b36b43 100%)',
      boxShadow: 'inset 0 -4px 0 rgba(93,55,39,.24)',
    },
    '&[data-studio-tile="wall-paper"]': {
      background:
        'radial-gradient(circle at 35% 42%, rgba(204,139,75,.22) 0 2px, transparent 2px), linear-gradient(180deg, #ffe3b7 0%, #f5d39d 100%)',
      boxShadow:
        'inset 1px 0 rgba(154,113,81,.18), inset 0 1px rgba(255,255,255,.26)',
    },
    '&[data-studio-tile="wall-trim"]': {
      background: 'linear-gradient(180deg, #df9b5c 0%, #b87349 100%)',
      boxShadow:
        'inset 0 3px rgba(255,215,157,.22), inset 0 -3px rgba(92,55,39,.22)',
    },
    '&[data-studio-tile="wall-side"]': {
      background:
        'linear-gradient(90deg, #c3774a 0%, #df9155 52%, #b36b43 100%)',
      boxShadow:
        'inset 3px 0 rgba(255,215,157,.18), inset -3px 0 rgba(92,55,39,.18)',
    },
    '&[data-studio-tile="floor-wood"]': {
      background:
        'linear-gradient(90deg, rgba(91,61,40,.12) 0 1px, transparent 1px), linear-gradient(180deg, #d7a66a 0%, #c99458 100%)',
      boxShadow:
        'inset 0 1px rgba(255,231,187,.22), inset 0 -1px rgba(93,64,42,.12)',
    },
    '&[data-studio-tile="floor-wood-alt"]': {
      background:
        'linear-gradient(90deg, rgba(91,61,40,.11) 0 1px, transparent 1px), linear-gradient(180deg, #e0b174 0%, #d0a061 100%)',
      boxShadow:
        'inset 0 1px rgba(255,231,187,.2), inset 0 -1px rgba(93,64,42,.12)',
    },
    '&[data-studio-tile="floor-shadow"]': {
      background: 'linear-gradient(180deg, #c28d58 0%, #ad7849 100%)',
      boxShadow: 'inset 0 3px rgba(77,49,32,.18)',
    },
    '&[data-studio-tile="rug-green"]': {
      background:
        'linear-gradient(90deg, rgba(255,255,255,.09) 0 1px, transparent 1px), linear-gradient(180deg, #8ca56f 0%, #718f5d 100%)',
      boxShadow: 'inset 0 0 0 2px rgba(55,86,50,.25)',
    },
    '&[data-studio-tile="rug-blue"]': {
      background:
        'linear-gradient(90deg, rgba(255,255,255,.08) 0 1px, transparent 1px), linear-gradient(180deg, #b88b69 0%, #9f7154 100%)',
      boxShadow: 'inset 0 0 0 2px rgba(57,75,100,.22)',
    },
    '&[data-studio-tile="door-threshold"]': {
      background: 'linear-gradient(180deg, #6c4d36 0%, #4a3326 100%)',
      boxShadow: 'inset 0 3px rgba(255,224,173,.16)',
    },
  },
  workspaceStudioAmbientGlow: {
    position: 'absolute' as const,
    inset: '18px',
    zIndex: 1,
    pointerEvents: 'none' as const,
    background:
      'radial-gradient(circle at 18% 24%, rgba(255,218,142,.34) 0 7%, transparent 22%), radial-gradient(circle at 76% 28%, rgba(255,192,111,.24) 0 8%, transparent 24%), linear-gradient(180deg, rgba(255,238,193,.18), transparent 52%)',
    mixBlendMode: 'screen' as const,
    opacity: 0.78,
  },
  workspaceStudioWall: {
    position: 'absolute' as const,
    inset: '0 0 40%',
    background:
      'linear-gradient(180deg, #efe5d7 0%, #e8dac8 100%), repeating-linear-gradient(90deg, rgba(116,91,67,.07) 0 1px, transparent 1px 22px), repeating-linear-gradient(0deg, rgba(116,91,67,.045) 0 1px, transparent 1px 22px)',
    zIndex: 0,
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 0,
      right: 0,
      bottom: -1,
      height: 8,
      background: '#c8b69e',
      boxShadow: '0 2px 0 rgba(92,74,58,.12)',
    },
  },
  workspaceStudioFloor: {
    position: 'absolute' as const,
    inset: '41% 0 0',
    background:
      'linear-gradient(180deg, rgba(132,104,72,.14), rgba(132,104,72,.03)), repeating-linear-gradient(0deg, rgba(83,63,43,.13) 0 1px, transparent 1px 18px), repeating-linear-gradient(90deg, rgba(83,63,43,.10) 0 1px, transparent 1px 28px)',
    transform: 'skewY(-2deg)',
    transformOrigin: 'left top',
    zIndex: 0,
  },
  workspaceStudioWindow: {
    position: 'absolute' as const,
    left: '10%',
    top: '13%',
    width: 94,
    height: 54,
    border: '4px solid #b58d66',
    background:
      'linear-gradient(180deg, #f5dba8 0%, #f9edc9 58%, #d7e7dd 100%)',
    boxShadow:
      'inset 0 0 0 2px rgba(255,252,228,.72), 0 4px 0 rgba(92,74,58,.1), -10px 0 0 -4px #b7795a, 10px 0 0 -4px #b7795a',
    zIndex: 2,
    imageRendering: 'pixelated' as const,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: '50%',
      top: 0,
      bottom: 0,
      width: 3,
      background: '#b58d66',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 0,
      right: 0,
      top: '50%',
      height: 3,
      background: '#b58d66',
    },
  },
  workspaceStudioGalleryWall: {
    left: '18%',
    top: '12.6%',
    width: 132,
    height: 54,
    background: 'transparent',
    boxShadow: '0 0 0 0 transparent',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 0,
      top: 8,
      width: 30,
      height: 28,
      border: '4px solid #9a7151',
      background: '#f4d8a0',
      boxShadow:
        '43px -5px 0 -2px #9a7151, 43px -5px 0 2px #e7c68f, 88px 5px 0 -2px #9a7151, 88px 5px 0 2px #d6e5c2',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 10,
      top: 19,
      width: 8,
      height: 8,
      background: '#7a9a7e',
      boxShadow:
        '48px -5px 0 #c85b4d, 91px 4px 0 #8aa170, 101px 13px 0 #d7aa4f',
    },
  },
  workspaceStudioBookshelf: {
    left: '37%',
    top: '13.5%',
    width: 162,
    height: 50,
    background: '#8a5f43',
    boxShadow:
      '0 6px 0 #68442f, inset 0 18px 0 rgba(255,214,154,.1), inset 0 -5px 0 rgba(78,49,31,.18)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 12,
      top: 9,
      width: 12,
      height: 21,
      background: '#8aa170',
      boxShadow:
        '16px 0 0 #c99957, 32px 0 0 #b95d54, 52px 0 0 #f0d29b, 68px 0 0 #748ca0, 88px 0 0 #8aa170, 108px 0 0 #c99957, 126px 0 0 #b95d54',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      right: 8,
      top: 34,
      height: 5,
      background: '#6d4833',
      boxShadow: '0 -18px 0 #6d4833',
    },
  },
  workspaceStudioShelf: {
    position: 'absolute' as const,
    left: '39%',
    top: '23.5%',
    width: 122,
    height: 12,
    background: '#a5724d',
    boxShadow:
      '0 6px 0 #765038, 18px -13px 0 -8px #e7c68f, 46px -13px 0 -8px #8ca56f, 76px -13px 0 -8px #d79258, 104px -13px 0 -8px #c75f55',
    zIndex: 2,
  },
  workspaceStudioPlantShelf: {
    left: '47%',
    top: '14.4%',
    width: 122,
    height: 28,
    background: 'transparent',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 0,
      right: 0,
      bottom: 0,
      height: 9,
      background: '#9a7151',
      boxShadow: '0 5px 0 #704b35',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 12,
      bottom: 10,
      width: 18,
      height: 16,
      background: '#b7795a',
      boxShadow: '38px -2px 0 #8ca56f, 72px 0 0 #d7aa4f, 92px -4px 0 #9b7658',
    },
  },
  workspaceStudioBoard: {
    position: 'absolute' as const,
    right: '24%',
    top: '13%',
    width: 122,
    height: 68,
    border: '5px solid #8e7c67',
    background: '#fff3d7',
    boxShadow: '0 5px 0 rgba(92,74,58,.12)',
    zIndex: 1,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 14,
      top: 15,
      width: 58,
      height: 5,
      background: '#8aa170',
      boxShadow: '0 16px 0 #c99957, 36px 16px 0 #b88b69',
      opacity: 0.68,
    },
  },
  workspaceStudioBoardActive: {
    boxShadow: '0 5px 0 rgba(92,74,58,.12), 0 0 22px rgba(124,58,237,.2)',
    '&::before': {
      animation: 'softBreath 1400ms ease-in-out infinite',
    },
  },
  workspaceStudioTaskBoardHotspot: {
    right: '24%',
    top: '13%',
    width: 122,
    height: 68,
    background: 'transparent',
    zIndex: 4,
  },
  workspaceStudioNoticeBoard: {
    right: '22%',
    top: '14%',
    width: 86,
    height: 54,
    border: '4px solid #9a7151',
    background: '#d8aa68',
    boxShadow:
      '0 5px 0 rgba(92,74,58,.14), inset 0 0 0 3px rgba(255,230,180,.18)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 10,
      top: 9,
      width: 18,
      height: 14,
      background: '#f6e7bb',
      boxShadow:
        '26px 2px 0 #d6e5c2, 50px 0 0 #f3c1a5, 15px 24px 0 #c7d6e7, 43px 25px 0 #fff1d0',
    },
  },
  workspaceStudioHearth: {
    right: '17%',
    top: '33%',
    width: 54,
    height: 54,
    background: '#8d6b54',
    boxShadow:
      '0 8px 0 #654637, inset 0 8px 0 rgba(255,230,180,.14), inset 0 -8px 0 rgba(55,33,23,.22)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 12,
      right: 12,
      bottom: 7,
      height: 24,
      background: '#3c2a22',
      boxShadow: 'inset 0 -6px 0 #5b3527',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 21,
      bottom: 13,
      width: 8,
      height: 13,
      background: '#f8c15a',
      boxShadow:
        '-7px 6px 0 #d56a3f, 8px 5px 0 #ffdc78, 0 0 18px rgba(255,177,80,.34)',
    },
  },
  workspaceStudioKitchenCounter: {
    right: '29%',
    top: '31.5%',
    width: 118,
    height: 54,
    background: '#b88b69',
    boxShadow:
      '0 8px 0 #846349, inset 0 13px 0 rgba(255,241,208,.24), inset 40px 0 rgba(102,72,50,.12)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 10,
      top: -17,
      width: 32,
      height: 18,
      background: '#f2dfb8',
      boxShadow: '46px 2px 0 #8ca56f, 72px 0 0 #c85b4d',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 16,
      bottom: 12,
      width: 18,
      height: 8,
      background: '#6b4b35',
      boxShadow: '36px 0 0 #6b4b35, 72px 0 0 #6b4b35',
    },
  },
  workspaceStudioWallClock: {
    left: '24%',
    top: '15.4%',
    width: 34,
    height: 34,
    border: '4px solid #8e6b4d',
    borderRadius: '50%',
    background: '#f4e7c6',
    boxShadow:
      '0 4px 0 rgba(92,74,58,.14), inset 0 0 0 3px rgba(255,255,255,.45)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 14,
      top: 8,
      width: 3,
      height: 11,
      background: '#5f4938',
      boxShadow: '4px 8px 0 -1px #5f4938',
      transformOrigin: 'bottom center',
    },
  },
  workspaceStudioWallLampLeft: {
    left: '4.5%',
    top: '30%',
    width: 20,
    height: 28,
    background: '#d7aa4f',
    boxShadow: '0 4px 0 #8f6241, 0 0 26px rgba(254,217,117,.44)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 7,
      top: -9,
      width: 6,
      height: 10,
      background: '#7e4d35',
    },
  },
  workspaceStudioWallLampRight: {
    right: '4.5%',
    top: '30%',
    width: 20,
    height: 28,
    background: '#d7aa4f',
    boxShadow: '0 4px 0 #8f6241, 0 0 26px rgba(254,217,117,.44)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 7,
      top: -9,
      width: 6,
      height: 10,
      background: '#7e4d35',
    },
  },
  workspaceStudioZone: {
    position: 'absolute' as const,
    zIndex: 1,
    minWidth: 72,
    height: 24,
    border: '2px solid rgba(121,82,52,.22)',
    borderRadius: 3,
    background: 'rgba(250,240,220,.72)',
    color: 'rgba(83,57,39,.82)',
    fontSize: 11,
    fontWeight: 600,
    lineHeight: '20px',
    textAlign: 'center' as const,
    pointerEvents: 'none' as const,
    boxShadow: '0 3px 0 rgba(89,58,38,.14)',
    textShadow: '0 1px 0 rgba(255,255,255,.65)',
    '@media (max-width: 767px)': {
      display: 'none',
    },
  },
  workspaceStudioWorkZone: { left: '27%', top: '50%' },
  workspaceStudioRestZone: { left: '8%', top: '50%' },
  workspaceStudioSleepZone: { right: '8%', top: '51%' },
  workspaceStudioPlayZone: { left: '66%', top: '50%' },
  workspaceStudioFurniture: {
    position: 'absolute' as const,
    zIndex: 2,
    borderRadius: 2,
    imageRendering: 'pixelated' as const,
    '&[data-studio-object]': {
      border: 0,
      padding: 0,
      cursor: 'pointer',
    },
    '&[data-studio-object]:focus-visible': {
      outline: '2px solid var(--accent-purple)',
      outlineOffset: 3,
    },
    '&[data-studio-object]:hover': {
      filter: 'brightness(1.04)',
    },
  },
  workspaceStudioObjectSelected: {
    outline: '2px solid rgba(124,58,237,.66)',
    outlineOffset: 4,
    filter: 'brightness(1.04)',
  },
  workspaceStudioObjectBadge: {
    position: 'absolute' as const,
    left: '50%',
    top: -24,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 52,
    minHeight: 20,
    padding: '2px 7px',
    transform: 'translateX(-50%)',
    border: '2px solid rgba(83,57,39,.64)',
    borderRadius: 3,
    background: 'rgba(255, 241, 208, 0.92)',
    boxShadow: '0 3px 0 rgba(83,57,39,.2)',
    color: '#3a251a',
    fontSize: 10,
    fontWeight: 800,
    lineHeight: '13px',
    whiteSpace: 'nowrap' as const,
    pointerEvents: 'none' as const,
  },
  workspaceStudioObjectLabel: {
    position: 'absolute' as const,
    left: '50%',
    bottom: -24,
    zIndex: 4,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 44,
    minHeight: 18,
    padding: '2px 7px',
    transform: 'translateX(-50%)',
    border: '2px solid rgba(83,57,39,.5)',
    borderRadius: 3,
    background: 'rgba(255, 248, 232, 0.86)',
    boxShadow: '0 2px 0 rgba(83,57,39,.18)',
    color: '#4b3022',
    fontSize: 10,
    fontWeight: 800,
    lineHeight: '12px',
    whiteSpace: 'nowrap' as const,
    pointerEvents: 'none' as const,
    '&[data-label-placement="top"]': {
      top: -24,
      bottom: 'auto',
    },
  },
  workspaceStudioDesk: {
    left: '29%',
    top: '42%',
    width: 118,
    height: 26,
    background: '#9a7151',
    boxShadow:
      '0 6px 0 #704b35, inset 0 3px 0 rgba(255,217,166,.18), 8px 33px 0 -11px #6d4a36, 92px 33px 0 -11px #6d4a36',
  },
  workspaceStudioDeskActive: {
    '& [class*="workspaceStudioMonitor"]': {
      boxShadow:
        '10px 28px 0 -10px #6e6659, inset 0 0 0 4px rgba(88,130,145,.28), 0 0 24px rgba(34,211,238,.42)',
    },
    '& [class*="workspaceStudioDeskLamp"]': {
      boxShadow:
        '0 4px 0 #8f6241, -8px 22px 0 -7px #5b4a3d, 0 0 24px rgba(254,217,117,.42)',
    },
  },
  workspaceStudioToolCart: {
    left: '36.2%',
    top: '41.8%',
    width: 48,
    height: 44,
    background: '#8d7a62',
    boxShadow:
      '0 7px 0 #65513f, inset 0 12px 0 rgba(255,242,210,.2), 0 25px 0 -18px #3a251a, 32px 25px 0 -18px #3a251a',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      top: 9,
      width: 10,
      height: 5,
      background: '#d7aa4f',
      boxShadow: '18px 0 0 #7a9a7e, 0 13px 0 #f4e7c6, 18px 13px 0 #c85b4d',
    },
  },
  workspaceStudioMonitor: {
    position: 'absolute' as const,
    left: 36,
    top: -30,
    width: 43,
    height: 26,
    border: '3px solid #6e6659',
    background: '#d9e3de',
    boxShadow:
      '10px 28px 0 -10px #6e6659, inset 0 0 0 4px rgba(88,130,145,.22), 0 0 18px rgba(91,149,177,.22)',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      top: 7,
      width: 10,
      height: 3,
      background: '#7a9a7e',
      boxShadow: '15px 0 0 #7c3aed, 0 8px 0 #d7aa4f, 15px 8px 0 #22d3ee',
      opacity: 0.78,
    },
  },
  workspaceStudioKeyboard: {
    position: 'absolute' as const,
    left: 44,
    top: 5,
    width: 34,
    height: 7,
    background: '#f1e7d6',
    boxShadow: '0 2px 0 rgba(92,74,58,.28)',
  },
  workspaceStudioDeskLamp: {
    position: 'absolute' as const,
    right: 12,
    top: -19,
    width: 18,
    height: 16,
    background: '#d7aa4f',
    boxShadow:
      '0 4px 0 #8f6241, -8px 22px 0 -7px #5b4a3d, 0 0 15px rgba(254,217,117,.24)',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 6,
      top: 15,
      width: 5,
      height: 18,
      background: '#5b4a3d',
    },
  },
  workspaceStudioDeskNotes: {
    position: 'absolute' as const,
    left: 9,
    top: 6,
    width: 18,
    height: 11,
    background: '#f4e7c6',
    boxShadow: '22px 0 0 #e7d6b7, 44px 0 0 #f4e7c6',
  },
  workspaceStudioSofa: {
    left: '8%',
    top: '44%',
    width: 96,
    height: 29,
    background: '#8ca56f',
    boxShadow:
      '0 8px 0 #64794d, 8px -10px 0 -3px #b1bd86, -12px 5px 0 -5px #758d5c, 86px 5px 0 -5px #758d5c',
  },
  workspaceStudioFloorLamp: {
    left: '5.9%',
    top: '45.3%',
    width: 24,
    height: 84,
    background: 'transparent',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 7,
      top: 26,
      width: 7,
      height: 49,
      background: '#6b4b35',
      boxShadow: '-12px 49px 0 -3px #6b4b35, 12px 49px 0 -3px #6b4b35',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: -1,
      top: 0,
      width: 26,
      height: 27,
      background: '#f4d486',
      boxShadow: '0 5px 0 #b7795a, 0 0 34px rgba(255,215,120,.35)',
      clipPath: 'polygon(16% 0, 84% 0, 100% 100%, 0 100%)',
    },
  },
  workspaceStudioSideBooks: {
    left: '15.3%',
    top: '47.8%',
    width: 54,
    height: 48,
    background: '#8a5f43',
    boxShadow:
      '0 7px 0 #68442f, inset 0 16px 0 rgba(255,214,154,.1), inset 0 -5px 0 rgba(78,49,31,.18)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      top: 8,
      width: 6,
      height: 18,
      background: '#d7aa4f',
      boxShadow: '9px 0 0 #8ca56f, 18px 0 0 #c85b4d, 28px 0 0 #f4e7c6',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 6,
      right: 6,
      top: 31,
      height: 4,
      background: '#6d4833',
      boxShadow: '0 -17px 0 #6d4833',
    },
  },
  workspaceStudioBed: {
    right: '8%',
    top: '45%',
    width: 98,
    height: 30,
    background: '#c8aa7a',
    boxShadow:
      '0 8px 0 #9b7658, 9px -9px 0 -3px #fff1d0, 68px -8px 0 -5px #d8bd8b',
  },
  workspaceStudioBedsideTable: {
    right: '16.2%',
    top: '45.5%',
    width: 40,
    height: 36,
    background: '#9a7151',
    boxShadow: '0 7px 0 #704b35, inset 0 14px 0 rgba(255,217,166,.16)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 12,
      top: -14,
      width: 16,
      height: 16,
      background: '#f4d486',
      boxShadow: '0 0 24px rgba(255,215,120,.32)',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      top: 17,
      width: 24,
      height: 4,
      background: '#6b4b35',
    },
  },
  workspaceStudioStorageCabinet: {
    right: '4.2%',
    top: '40.8%',
    width: 56,
    height: 76,
    background: '#8d7a62',
    boxShadow:
      '0 8px 0 #65513f, inset 0 18px 0 rgba(255,242,210,.2), inset 0 39px 0 rgba(255,242,210,.12)',
    zIndex: 2,
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 11,
      top: 14,
      width: 7,
      height: 7,
      background: '#8aa170',
      boxShadow: '20px 0 0 #d99a5f, 0 23px 0 #c85b4d, 20px 23px 0 #8aa170',
    },
  },
  workspaceStudioArcade: {
    left: '66%',
    top: '43%',
    width: 46,
    height: 62,
    background: '#9f7154',
    boxShadow:
      '0 8px 0 #764f3b, inset 8px 10px 0 -4px #f2dfb8, inset 28px 10px 0 -4px #d99a5f',
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 14,
      top: 34,
      width: 7,
      height: 7,
      background: '#c85b4d',
      boxShadow: '14px 0 0 #8aa170',
    },
  },
  workspaceStudioPlant: {
    left: '55%',
    top: '46%',
    width: 30,
    height: 26,
    background: '#9b7658',
    boxShadow:
      '0 8px 0 #785740, -5px -12px 0 -5px #6f8d63, 8px -18px 0 -6px #7a9a7e, 18px -10px 0 -6px #5f7f62',
  },
  workspaceStudioTallPlantLeft: {
    left: '10.2%',
    top: '37.2%',
    width: 34,
    height: 72,
    background: '#9b7658',
    boxShadow:
      '0 9px 0 #785740, -12px -22px 0 -10px #6f8d63, 7px -34px 0 -11px #7a9a7e, 21px -22px 0 -10px #5f7f62, 2px -16px 0 -6px #8ca56f',
    zIndex: 2,
  },
  workspaceStudioTallPlantRight: {
    right: '19%',
    top: '37.5%',
    width: 34,
    height: 72,
    background: '#9b7658',
    boxShadow:
      '0 9px 0 #785740, -10px -21px 0 -10px #6f8d63, 6px -35px 0 -11px #7a9a7e, 22px -23px 0 -10px #5f7f62, 2px -15px 0 -6px #8ca56f',
    zIndex: 2,
  },
  workspaceStudioServer: {
    right: '23%',
    top: '43%',
    width: 42,
    height: 58,
    background: '#8d7a62',
    boxShadow:
      '0 7px 0 #65513f, inset 0 12px 0 rgba(255,242,210,.2), inset 0 30px 0 rgba(255,242,210,.12)',
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      top: 10,
      width: 6,
      height: 6,
      background: '#8aa170',
      boxShadow: '16px 0 0 #d99a5f, 0 18px 0 #c85b4d, 16px 18px 0 #8aa170',
      animation: 'softBreath 1800ms ease-in-out infinite',
    },
  },
  workspaceStudioRoundRug: {
    left: '39%',
    top: '54.2%',
    width: 166,
    height: 58,
    borderRadius: '50%',
    background: 'rgba(143, 105, 68, 0.34)',
    boxShadow:
      'inset 0 0 0 4px rgba(112,76,50,.16), inset 0 14px 0 rgba(255,226,166,.12)',
    zIndex: 0,
  },
  workspaceStudioDoor: {
    left: '47.6%',
    bottom: '1.9%',
    width: 88,
    height: 60,
    marginLeft: -44,
    background: '#5b3b2b',
    boxShadow:
      '0 -7px 0 #8f6241, inset 13px 0 #744c35, inset -13px 0 #744c35, inset 0 18px #3c2a22',
    borderRadius: '3px 3px 0 0',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 38,
      top: 30,
      width: 7,
      height: 7,
      borderRadius: '50%',
      background: '#d7aa4f',
      boxShadow: '0 1px 0 rgba(0,0,0,.2)',
    },
  },
  workspaceStudioMailbox: {
    left: '58%',
    bottom: '10%',
    width: 48,
    height: 38,
    background: '#f0ddbb',
    boxShadow:
      '0 7px 0 #b79268, inset -8px 0 rgba(128,86,49,.16), 18px 34px 0 -15px #6b4b35',
    borderRadius: '12px 12px 3px 3px',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 8,
      right: 8,
      top: 13,
      height: 4,
      background: '#a5724d',
      boxShadow: '0 8px 0 rgba(165,114,77,.7)',
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: 16,
      bottom: -24,
      width: 8,
      height: 24,
      background: '#7a5439',
    },
  },
  workspaceStudioMailboxLetters: {
    position: 'absolute' as const,
    left: -10,
    top: 22,
    width: 13,
    height: 9,
    background: '#f7f1e6',
    boxShadow: '-7px 8px 0 #e8d6b8, 4px 9px 0 #f7f1e6',
    transform: 'rotate(-8deg)',
  },
  workspaceStudioMailboxFlag: {
    position: 'absolute' as const,
    right: -13,
    top: 7,
    width: 13,
    height: 22,
    background: '#c85b4d',
    boxShadow: '-3px 0 0 #7f493c',
    transformOrigin: 'left bottom',
    animation: 'softBreath 2200ms ease-in-out infinite',
  },
  workspaceStudioComputerHotspot: {
    left: '30.8%',
    top: '35.6%',
    width: 92,
    height: 76,
    background: 'transparent',
    zIndex: 4,
    '&[data-object-state="active"]::after': {
      content: '""',
      position: 'absolute' as const,
      left: '50%',
      top: '20%',
      width: 8,
      height: 8,
      marginLeft: -4,
      borderRadius: '50%',
      background: '#22d3ee',
      boxShadow:
        '0 0 16px rgba(34,211,238,.68), 0 0 0 5px rgba(34,211,238,.12)',
      animation: 'softBreath 1200ms ease-in-out infinite',
    },
  },
  workspaceStudioRug: {
    left: '12%',
    top: '61%',
    width: 220,
    height: 68,
    borderRadius: 4,
    background: 'rgba(153, 112, 73, .13)',
    boxShadow:
      'inset 0 0 0 3px rgba(107,83,54,.22), inset 0 18px 0 rgba(200,91,77,.12), inset 0 36px 0 rgba(255,223,159,.16), 0 4px 0 rgba(77,49,32,.12)',
    zIndex: 0,
  },
  workspaceStudioCoffeeTable: {
    left: '17%',
    top: '58%',
    width: 56,
    height: 18,
    background: '#b28a67',
    boxShadow:
      '0 6px 0 #846349, 10px 21px 0 -9px #6d4a36, 38px 21px 0 -9px #6d4a36',
  },
  workspaceStudioFloorCushion: {
    left: '24%',
    top: '66%',
    width: 40,
    height: 20,
    background: '#d8bd8b',
    boxShadow:
      '0 5px 0 #ad8054, 53px -4px 0 -2px #c85b4d, 100px 0 0 -1px #8aa170',
    zIndex: 1,
  },
  workspaceStudioTeaTray: {
    left: '20%',
    top: '57%',
    width: 58,
    height: 18,
    background: '#c99957',
    boxShadow:
      '0 5px 0 #8b5d3c, 15px -8px 0 -5px #fff1d0, 33px -8px 0 -5px #fff1d0',
    zIndex: 2,
  },
  workspaceStudioCable: {
    left: '38%',
    top: '55%',
    width: 180,
    height: 4,
    background: '#76543e',
    boxShadow:
      '26px 18px 0 -1px rgba(118,84,62,.7), 94px 18px 0 -1px rgba(118,84,62,.7)',
    opacity: 0.82,
  },
  workspaceStudioDoorMat: {
    left: '45.7%',
    bottom: '9.3%',
    width: 118,
    height: 26,
    background: '#7a9a7e',
    boxShadow:
      'inset 0 0 0 3px rgba(48,82,50,.24), inset 0 9px 0 rgba(255,255,255,.08)',
    zIndex: 1,
  },
  workspaceStudioFloorCrate: {
    right: '10%',
    bottom: '16%',
    width: 52,
    height: 42,
    background: '#a97049',
    boxShadow:
      '0 6px 0 #754d36, inset 14px 0 rgba(86,54,37,.16), inset -14px 0 rgba(255,213,139,.12)',
    '&::before': {
      content: '""',
      position: 'absolute' as const,
      left: 6,
      right: 6,
      top: 12,
      height: 4,
      background: '#754d36',
      boxShadow: '0 12px 0 #754d36',
    },
  },
  workspaceStudioAgentHudList: {
    position: 'absolute' as const,
    left: '50%',
    top: 18,
    zIndex: 6,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    maxWidth: 'calc(100% - 220px)',
    transform: 'translateX(-50%)',
    overflowX: 'auto' as const,
    overflowY: 'hidden' as const,
    padding: '0 4px 8px',
    scrollbarWidth: 'none' as const,
    '&::-webkit-scrollbar': {
      display: 'none',
    },
    '@media (max-width: 1080px)': {
      left: 22,
      right: 22,
      maxWidth: 'calc(100% - 44px)',
      justifyContent: 'flex-start',
      transform: 'none',
    },
  },
  workspaceStudioAgentHud: {
    position: 'relative' as const,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 70,
    height: 70,
    padding: 5,
    flex: '0 0 auto',
    border: 0,
    borderRadius: 0,
    background: 'transparent',
    boxShadow: 'none',
    cursor: 'pointer',
    imageRendering: 'pixelated' as const,
    transition: 'transform 140ms ease, filter 140ms ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      filter: 'drop-shadow(0 5px 0 rgba(58,37,26,.24))',
    },
    '&:active': {
      transform: 'translateY(1px)',
      filter: 'drop-shadow(0 2px 0 rgba(58,37,26,.22))',
    },
    '&[data-selected="true"]': {
      filter: 'drop-shadow(0 0 0 rgba(0,0,0,0))',
      '& [data-studio-hud-portrait]': {
        borderColor: '#7c3aed',
        boxShadow:
          '0 3px 0 #3a251a, 0 0 0 4px rgba(124,58,237,.24), 0 8px 18px rgba(58,37,26,.2), inset 0 0 0 2px rgba(255,255,255,.28)',
      },
    },
    '&:focus-visible': {
      outline: '2px solid var(--accent-purple)',
      outlineOffset: 3,
    },
  },
  workspaceStudioAgentHudPortrait: {
    position: 'relative' as const,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 56,
    height: 56,
    boxSizing: 'content-box' as const,
    overflow: 'hidden',
    border: '3px solid #4f3425',
    borderRadius: '50%',
    background: 'linear-gradient(180deg, #fff0c6, #e0b06d)',
    boxShadow:
      '0 3px 0 #3a251a, 0 8px 18px rgba(58,37,26,.2), inset 0 0 0 2px rgba(255,255,255,.28)',
  },
  workspaceStudioAgentHudPortraitImg: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
    imageRendering: 'auto' as const,
  },
  workspaceStudioAgentHudPortraitFallback: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    color: '#3a251a',
    fontSize: 22,
    fontWeight: 900,
    lineHeight: '56px',
    textAlign: 'center' as const,
    background: 'linear-gradient(180deg, #ffe6a8, #d39a59)',
    boxShadow: 'inset 0 0 0 2px rgba(255,255,255,.24)',
  },
  workspaceStudioAgentHudCopy: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    minWidth: 0,
  },
  workspaceStudioAgentHudName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 13,
    lineHeight: '16px',
    fontWeight: 800,
    color: '#3a251a',
  },
  workspaceStudioAgentHudMeta: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 11,
    lineHeight: '14px',
    color: '#6f513d',
  },
  workspaceStudioAgentHudActions: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
    '@media (max-width: 1080px)': {
      gridColumn: '1 / -1',
      justifyContent: 'flex-start',
    },
  },
  workspaceStudioPixelButton: {
    minWidth: 54,
    height: 28,
    padding: '0 9px',
    border: '2px solid #4f3425',
    borderRadius: 3,
    background: '#fff2c6',
    boxShadow: '0 3px 0 #8a5a36, inset 0 2px rgba(255,255,255,.35)',
    color: '#3a251a',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 800,
    lineHeight: '20px',
    whiteSpace: 'nowrap' as const,
    transition:
      'transform 120ms ease, box-shadow 120ms ease, background-color 120ms ease',
    '&:hover:not(:disabled)': {
      background: '#ffe6a6',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 0 #8a5a36, inset 0 2px rgba(255,255,255,.38)',
    },
    '&:active:not(:disabled)': {
      transform: 'translateY(2px)',
      boxShadow: '0 1px 0 #8a5a36, inset 0 2px rgba(255,255,255,.28)',
    },
    '&:disabled': {
      cursor: 'default',
      opacity: 0.58,
    },
    '&:focus-visible': {
      outline: '2px solid var(--accent-purple)',
      outlineOffset: 2,
    },
  },
  workspaceStudioCharacterPanel: {
    position: 'absolute' as const,
    zIndex: 7,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    width: 172,
    minHeight: 92,
    marginLeft: -86,
    marginTop: -104,
    padding: '9px 10px',
    border: '3px solid #4f3425',
    borderRadius: 4,
    background: 'linear-gradient(180deg, #fff1c8 0%, #e8bf82 100%)',
    boxShadow:
      '0 4px 0 #2f2118, 0 12px 22px rgba(58,37,26,.2), inset 0 0 0 2px rgba(255,255,255,.28)',
    color: '#3a251a',
    pointerEvents: 'auto' as const,
    imageRendering: 'pixelated' as const,
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: '50%',
      bottom: -12,
      width: 14,
      height: 14,
      marginLeft: -7,
      background: '#e8bf82',
      borderRight: '3px solid #4f3425',
      borderBottom: '3px solid #4f3425',
      transform: 'rotate(45deg)',
    },
    '@media (max-width: 767px)': {
      display: 'none',
    },
  },
  workspaceStudioCharacterPanelTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 800,
  },
  workspaceStudioCharacterPanelMeta: {
    display: '-webkit-box',
    overflow: 'hidden',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical' as const,
    minHeight: 28,
    fontSize: 11,
    lineHeight: '14px',
    color: '#6f513d',
  },
  workspaceStudioCharacterPanelActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  workspaceStudioInteractionLayer: {
    position: 'absolute' as const,
    inset: 0,
    zIndex: 3,
    pointerEvents: 'none' as const,
  },
  workspaceStudioInteractionLine: {
    position: 'absolute' as const,
    height: 4,
    minWidth: 34,
    borderRadius: 2,
    background:
      'linear-gradient(90deg, rgba(124,58,237,.18), rgba(34,211,238,.52), rgba(124,58,237,.18))',
    boxShadow: '0 0 14px rgba(34,211,238,.22)',
    transform: 'translateY(-50%)',
    animation: 'signalFlow 1800ms linear infinite',
    backgroundSize: '200% 100%',
  },
  workspaceStudioSpeechBubble: {
    position: 'absolute' as const,
    display: 'inline-flex',
    alignItems: 'center',
    maxWidth: 150,
    minHeight: 28,
    padding: '4px 8px',
    transform: 'translate(-50%, -100%)',
    border: '3px solid #4f3425',
    borderRadius: 4,
    background: '#fff1c8',
    boxShadow: '0 4px 0 #2f2118, 0 10px 18px rgba(58,37,26,.18)',
    color: '#3a251a',
    fontSize: 11,
    fontWeight: 800,
    lineHeight: '14px',
    textAlign: 'center' as const,
    wordBreak: 'break-word' as const,
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: '50%',
      bottom: -10,
      width: 10,
      height: 10,
      marginLeft: -5,
      background: '#fff1c8',
      borderRight: '3px solid #4f3425',
      borderBottom: '3px solid #4f3425',
      transform: 'rotate(45deg)',
    },
  },
  workspaceStudioAgent: {
    position: 'absolute' as const,
    zIndex: 2,
    width: 98,
    height: 104,
    marginLeft: -49,
    marginTop: -52,
    border: 0,
    padding: 0,
    background: 'transparent',
    cursor: 'pointer',
    color: 'var(--text-primary)',
    font: 'inherit',
    transition:
      'left 820ms steps(8), top 820ms steps(8), transform 180ms ease, filter 180ms ease',
    '&:disabled': { cursor: 'default', opacity: 0.66 },
    '&:focus-visible': {
      outline: '2px solid var(--accent-purple)',
      outlineOffset: 2,
      borderRadius: 6,
    },
  },
  workspaceStudioAgentSelected: {
    '& [data-studio-sprite]': {
      filter: 'drop-shadow(0 0 0 rgba(0,0,0,0))',
    },
    '& [data-studio-name]': {
      color: 'var(--accent-purple)',
      fontWeight: 700,
    },
  },
  workspaceStudioAgentresting: {},
  workspaceStudioAgentworking: {
    '& [data-studio-sprite]': { transform: 'translateY(-2px)' },
    '& [data-studio-status]': { color: '#5f7f62' },
    '& [data-studio-sprite]::after': {
      content: '""',
      position: 'absolute' as const,
      right: 0,
      top: 4,
      width: 6,
      height: 6,
      borderRadius: '50%',
      background: '#22d3ee',
      boxShadow: '0 0 10px rgba(34,211,238,.7)',
      animation: 'softBreath 1200ms ease-in-out infinite',
    },
  },
  workspaceStudioAgentplaying: {
    '& [data-studio-status]': { color: '#a47732' },
  },
  workspaceStudioAgentsleeping: {
    '& [data-studio-sprite]': { transform: 'translateY(3px)' },
    '& [data-studio-status]': { color: '#796f86' },
  },
  workspaceStudioAgentInteracting: {
    zIndex: 5,
    '& [data-studio-sprite]': {
      filter: 'drop-shadow(0 0 10px rgba(34,211,238,.32))',
    },
  },
  workspaceStudioAgentListening: {
    zIndex: 4,
    '& [data-studio-sprite]': {
      filter: 'drop-shadow(0 0 10px rgba(124,58,237,.28))',
    },
  },
  workspaceStudioAgentShadow: {
    position: 'absolute' as const,
    left: '50%',
    top: 68,
    width: 54,
    height: 12,
    marginLeft: -27,
    background: 'rgba(69, 52, 36, 0.16)',
    borderRadius: '50%',
  },
  workspaceStudioSprite: {
    position: 'absolute' as const,
    left: '50%',
    top: -4,
    width: 66,
    height: 72,
    marginLeft: -33,
    transition: 'transform 160ms ease, filter 160ms ease',
  },
  workspaceStudioSpriteSheet: {
    display: 'block',
    width: '100%',
    height: '100%',
    overflow: 'hidden',
    imageRendering: 'pixelated' as const,
    filter: 'drop-shadow(0 1px 0 rgba(79,70,60,.26))',
  },
  workspaceStudioSpriteSheetImg: {
    display: 'block',
    width: '800%',
    height: '900%',
    maxWidth: 'none',
    transform:
      'translate3d(0, calc(var(--workspace-studio-sprite-row) * var(--workspace-studio-sprite-frame-height, -57px)), 0)',
    transformOrigin: 'left top',
    imageRendering: 'pixelated' as const,
    animation:
      'workspaceStudioFrameLoop 880ms steps(var(--workspace-studio-frame-last)) infinite',
    animationDuration: '880ms !important',
    animationIterationCount: 'infinite !important',
  },
  workspaceStudioAvatarFace: {
    position: 'absolute' as const,
    left: 6,
    top: 0,
    width: 28,
    height: 28,
    overflow: 'hidden',
    border: '2px solid #4f463c',
    borderRadius: 2,
    background: '#f8f0e3',
    boxShadow: '0 2px 0 rgba(79,70,60,.35)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 700,
    '& img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover' as const,
      imageRendering: 'pixelated' as const,
      filter: 'saturate(.9) contrast(1.05)',
    },
  },
  workspaceStudioSpriteBody: {
    position: 'absolute' as const,
    left: 9,
    top: 30,
    width: 20,
    height: 20,
    background: '#f7f4ed',
    border: '2px solid #4f463c',
    borderRadius: 2,
    boxShadow:
      '-8px 3px 0 -5px #4f463c, 8px 3px 0 -5px #4f463c, -4px 15px 0 -5px #4f463c, 4px 15px 0 -5px #4f463c',
  },
  workspaceStudioAgentName: {
    position: 'absolute' as const,
    left: -12,
    right: -12,
    top: 77,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
    fontSize: 12,
    lineHeight: '15px',
    textAlign: 'center' as const,
    color: 'var(--text-primary)',
  },
  workspaceStudioAgentStatus: {
    position: 'absolute' as const,
    left: 8,
    right: 8,
    top: 93,
    overflow: 'hidden',
    whiteSpace: 'nowrap' as const,
    textOverflow: 'ellipsis',
    fontSize: 11,
    lineHeight: '13px',
    textAlign: 'center' as const,
    color: 'var(--earth-brown)',
    opacity: 0.82,
  },
  historyLoading: {
    display: 'flex',
    justifyContent: 'center',
    padding: '8px 0',
  },
  bubble: {
    width: 'fit-content' as const,
    maxWidth: 'min(76%, 820px)',
    padding: '12px 16px',
    borderRadius: 8,
    lineHeight: 1.6,
    wordBreak: 'break-word' as const,
    whiteSpace: 'pre-wrap' as const,
    border: '1px solid transparent',
    background: 'transparent',
    transition: 'background 200ms ease-in-out, box-shadow 200ms ease-in-out',
    '&:hover': {
      background: 'color-mix(in srgb, var(--soft-white) 50%, transparent)',
      boxShadow: '0 1px 6px rgba(0,0,0,0.04)',
    },
  },
  stepCardList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
    position: 'relative' as const,
    paddingLeft: 12,
  },
  stepCardLine: {
    position: 'absolute' as const,
    left: 5,
    top: 4,
    bottom: 4,
    width: 2,
    borderRadius: 2,
    background: token.colorBorderSecondary,
  },
  stepCard: {
    position: 'relative' as const,
    background: token.colorFillQuaternary,
    borderRadius: token.borderRadius,
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)',
    borderLeftWidth: 4,
    padding: '8px 10px',
  },
  stepCardDot: {
    position: 'absolute' as const,
    left: -11,
    top: 14,
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: token.colorBorder,
    border: `1px solid ${token.colorBgContainer}`,
  },
  stepCardExecuting: { borderLeftColor: 'var(--earth-brown)' },
  stepCardSuccess: {
    borderLeftColor: 'color-mix(in srgb, var(--earth-brown) 40%, transparent)',
  },
  stepCardError: { borderLeftColor: token.colorError },
  stepCardTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
    fontSize: 13,
  },
  stepCardStatus: {
    color: token.colorTextSecondary,
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  stepCardMessage: {
    color: token.colorText,
    fontSize: 13,
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap' as const,
  },
  stepCardTime: { color: 'var(--earth-brown)', opacity: 0.7, fontSize: 12 },

  /* ── Tool output collapse (长输出折叠 + 滚动 + 模糊) ── */
  toolOutputCollapse: {
    marginTop: 4,
    borderRadius: 6,
    overflow: 'hidden',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
  },
  toolOutputContent: {
    padding: '8px 10px',
    fontSize: 12,
    color: token.colorTextSecondary,
    lineHeight: 1.5,
    whiteSpace: 'pre-wrap' as const,
    overflow: 'hidden',
    position: 'relative' as const,
    transition: 'max-height 0.3s ease',
    fontFamily: "'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace",
    background: token.colorFillQuaternary,
  },
  toolOutputFade: {
    position: 'absolute' as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 40,
    background: `linear-gradient(to bottom, transparent, ${token.colorFillQuaternary})`,
    pointerEvents: 'none' as const,
  },
  toolOutputToggle: {
    padding: '4px 10px',
    fontSize: 11,
    color: token.colorPrimary,
    cursor: 'pointer',
    borderTop: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    textAlign: 'center' as const,
    userSelect: 'none' as const,
    background: token.colorFillQuaternary,
  },
  errorBubble: { borderColor: token.colorError },
  inputPanel: {
    padding: '8px 0 0',
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    background: 'color-mix(in srgb, var(--soft-white) 80%, transparent)',
    backdropFilter: 'blur(16px)',
    borderTop: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    borderRadius: '8px 8px 0 0',
    marginTop: 4,
  },
  tokenIndicator: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '0 2px',
  },
  tokenProgress: { flex: 1 },
  // 工具栏（输入框上方一行）
  toolbar: { display: 'flex', alignItems: 'center', gap: 4, padding: '0 6px' },
  toolbarSpacer: { flex: 1 },
  // 状态栏（窄条 IDE 风格：紧贴底部，单行图标透传状态）──
  statusBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '1px 8px 2px',
    fontSize: 10,
    color: 'var(--earth-brown)',
    opacity: 0.65,
    flexWrap: 'wrap' as const,
    minHeight: 20,
    background: 'color-mix(in srgb, var(--earth-brown) 4%, transparent)',
    borderTop: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
  },
  statusText: { whiteSpace: 'nowrap' as const },
  statusDivider: { userSelect: 'none' as const, opacity: 0.3 },
  // 状态栏图标通用
  statusIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    width: 16,
    height: 16,
    justifyContent: 'center',
    flexShrink: 0,
  },
  statusIconGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 3,
    cursor: 'default',
    flexShrink: 0,
  },
  statusIconLabel: {
    fontSize: 10,
    whiteSpace: 'nowrap' as const,
    lineHeight: '14px',
  },
  statusIconThunder: { transition: 'color 0.3s ease, opacity 0.3s ease' },
  statusPulse: { animation: 'statusPulseAnim 2s ease-in-out infinite' },
  '@keyframes statusPulseAnim': {
    '0%, 100%': { opacity: 0.35 },
    '50%': { opacity: 0.85 },
  },
  subconsciousGlow: {
    animation: 'subconsciousGlowAnim 3s ease-in-out infinite',
    filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))',
  },
  '@keyframes subconsciousGlowAnim': {
    '0%, 100%': { filter: 'drop-shadow(0 0 3px rgba(167,139,250,0.5))' },
    '50%': { filter: 'drop-shadow(0 0 8px rgba(167,139,250,0.9))' },
  },
  tokenStatsPopup: {
    position: 'absolute' as const,
    bottom: 28,
    right: 0,
    width: 640,
    maxHeight: 420,
    overflowY: 'auto' as const,
    background: 'color-mix(in srgb, var(--soft-white) 98%, transparent)',
    backdropFilter: 'blur(20px)',
    border: '1px solid',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 15%, transparent)',
    borderRadius: 10,
    padding: 12,
    boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    zIndex: 1050,
    fontSize: 11,
  },
  tokenStatsTitle: {
    fontWeight: 600,
    fontSize: 12,
    marginBottom: 6,
    color: 'var(--earth-brown)',
  },
  tokenStatsTable: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    '& th': {
      padding: '3px 6px',
      textAlign: 'left' as const,
      fontSize: 10,
      color: 'var(--earth-brown)',
      opacity: 0.6,
      fontWeight: 500,
      borderBottom: '1px solid',
      borderColor: 'color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    },
    '& td': {
      padding: '3px 6px',
      fontSize: 10,
      fontVariantNumeric: 'tabular-nums' as const,
    },
  },
  inputArea: { display: 'flex', gap: 8, alignItems: 'center' },
  input: { flex: 1 },
  emptyState: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: token.colorTextQuaternary,
    fontSize: 15,
  },
  emptyStateShell: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px 96px',
  },
  emptyStateInner: {
    width: '100%',
    maxWidth: 420,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center' as const,
    gap: 12,
    animation: 'emptyFadeIn 220ms ease-out',
  },
  emptyLogoFrame: {
    width: 112,
    height: 112,
    display: 'grid',
    placeItems: 'center',
    borderRadius: 28,
    background: 'color-mix(in srgb, var(--accent-purple) 5%, transparent)',
    border: '1px solid color-mix(in srgb, var(--earth-brown) 8%, transparent)',
  },
  emptyLogo: {
    width: 64,
    height: 64,
    objectFit: 'contain' as const,
    opacity: 0.92,
  },
  emptyTitle: {
    margin: '8px 0 0 !important',
    fontSize: '22px !important',
    fontWeight: '600 !important',
    color: 'var(--text-primary) !important',
  },
  emptySubtitle: {
    maxWidth: 360,
    fontSize: 14,
    lineHeight: 1.7,
    color: 'var(--text-muted)',
  },
  emptySuggestionRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap' as const,
    justifyContent: 'center',
    marginTop: 8,
  },
  emptySuggestionButton: {
    height: 34,
    padding: '0 14px',
    borderRadius: 17,
    border: '1px solid color-mix(in srgb, var(--earth-brown) 10%, transparent)',
    background: 'color-mix(in srgb, var(--soft-white) 86%, transparent)',
    color: 'var(--text-muted)',
    fontSize: 13,
    cursor: 'pointer' as const,
    transition:
      'background 160ms ease, border-color 160ms ease, color 160ms ease',
    '&:hover': {
      background:
        'color-mix(in srgb, var(--accent-purple) 7%, var(--soft-white))',
      borderColor: 'color-mix(in srgb, var(--accent-purple) 18%, transparent)',
      color: 'var(--text-primary)',
    },
  },
    errorAlert: { margin: '8px 0' },
  sidebarEmpty: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: token.colorTextQuaternary,
    fontSize: 13,
    padding: '0 16px',
    textAlign: 'center' as const,
  },
  
  stepCardCompleteIcon: {
    transition: 'color 300ms ease-in-out',
    color: 'var(--desaturated-green)',
  },
  inputCursor: {
    display: 'inline-block',
    width: 2,
    height: 18,
    background: 'var(--accent-purple)',
    marginLeft: 1,
    animation: 'cursorBlink 1s steps(1) infinite',
    verticalAlign: 'middle' as const,
  },
  avatarGroup: {
    display: 'flex',
    gap: 12,
    width: '100%',
    alignItems: 'flex-start',
  },
  avatarCol: { width: 32, flexShrink: 0 },
  avatarImg: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    objectFit: 'cover' as const,
    flexShrink: 0,
  },
  avatarPlaceholder: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    color: '#fff',
    fontSize: 14,
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    userSelect: 'none' as const,
  },
  avatarNameRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
    minHeight: 20,
  },
  avatarName: {
    fontSize: 14,
    color: 'var(--earth-brown)',
    fontWeight: 500,
    lineHeight: '20px',
  },
  avatarUserIcon: {
    width: 32,
    height: 32,
    borderRadius: '50%',
    background: 'var(--sky-soft)',
    color: 'var(--earth-brown)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    '& .anticon': { fontSize: 16 },
  },
  devPanel: {
    width: 400,
    minWidth: 360,
    maxWidth: 440,
    display: 'flex',
    flexDirection: 'column' as const,
    borderLeft: '1px solid',
    borderColor: token.colorBorderSecondary,
    background: 'color-mix(in srgb, var(--soft-white) 78%, transparent)',
    backdropFilter: 'blur(12px)',
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 12,
    marginBottom: 12,
  },
  devPanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    borderBottom: '1px solid',
    borderColor: token.colorBorderSecondary,
    fontSize: 13,
    fontWeight: 600,
  },
  devPanelTabs: {
    flex: 1,
    minHeight: 0,
    padding: '8px 10px 10px',
    '& .ant-tabs-content-holder': {
      overflow: 'auto',
    },
  },
  devPanelSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
  },
  devPanelLoading: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '16px 0',
  },
  devLine: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    fontSize: 12,
  },
  devLayerTitle: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  devPreview: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '8px 10px',
    fontSize: 12,
    lineHeight: 1.5,
  },
  devList: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
  devListItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    background: token.colorFillQuaternary,
    borderRadius: 6,
    padding: '6px 8px',
  },
  devErrorText: { margin: 0, color: token.colorError },
  devPanelHint: { margin: 0, fontSize: 12, color: token.colorTextSecondary },
  devPerfToolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  devPerfToolbarActions: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    flexShrink: 0,
  },
  devPerfDiagnosisList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  devPerfDiagnosisItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '7px 8px',
    background: token.colorFillQuaternary,
    fontSize: 12,
    '&[data-severity="warn"]': {
      borderColor:
        'color-mix(in srgb, var(--warning-signal, #F97316) 34%, transparent)',
      background:
        'color-mix(in srgb, var(--warning-signal, #F97316) 8%, transparent)',
    },
    '&[data-severity="critical"]': {
      borderColor:
        'color-mix(in srgb, var(--error-signal, #EF4444) 34%, transparent)',
      background:
        'color-mix(in srgb, var(--error-signal, #EF4444) 8%, transparent)',
    },
  },
  devPerfGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
  },
  devPerfMetric: {
    minWidth: 0,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '7px 8px',
    background: token.colorFillQuaternary,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 2,
    '&[data-tone="ok"]': {
      borderColor:
        'color-mix(in srgb, var(--desaturated-green) 34%, transparent)',
      background:
        'color-mix(in srgb, var(--desaturated-green) 8%, transparent)',
    },
    '&[data-tone="warn"]': {
      borderColor:
        'color-mix(in srgb, var(--warning-signal, #F97316) 34%, transparent)',
      background:
        'color-mix(in srgb, var(--warning-signal, #F97316) 8%, transparent)',
    },
  },
  devPerfMetricLabel: {
    fontSize: 11,
    lineHeight: '14px',
  },
  devPerfMetricValue: {
    fontSize: 15,
    lineHeight: '20px',
    fontWeight: 650,
    fontVariantNumeric: 'tabular-nums' as const,
  },
  devPerfCounts: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 6,
  },
  devPerfEventItem: {
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    background: token.colorFillQuaternary,
    borderRadius: 6,
    padding: '6px 8px',
  },
  devPerfEventHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  subconsciousTimeline: {
    padding: '4px 0 8px',
    '& .ant-timeline-item': { paddingBottom: 12 },
    '& .ant-timeline-item-content': { fontSize: 13 },
  },
  devEventList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
    maxHeight: '56vh',
    overflowY: 'auto' as const,
  },
  devEventItem: {
    background: token.colorFillQuaternary,
    border: '1px solid',
    borderColor: token.colorBorderSecondary,
    borderRadius: 6,
    padding: '6px 8px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
  },
  devEventTime: { fontSize: 11, color: token.colorTextSecondary },
  devEventPayload: {
    margin: 0,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    fontSize: 12,
    lineHeight: 1.5,
  },
  
  tokenUsageLine: {
    fontSize: 10,
    color: 'var(--earth-brown)',
    opacity: 0.35,
    padding: '2px 4px 0',
  },
  cameraInputModalBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 12,
  },
  cameraInputStatusRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 22,
    fontSize: 12,
    color: 'var(--pudding-text-muted, #756b5f)',
  },
  cameraInputStatusDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: 'var(--pudding-accent, #8b5cf6)',
    flexShrink: 0,
  },
  cameraInputResolution: {
    marginLeft: 'auto',
    fontVariantNumeric: 'tabular-nums' as const,
    color: 'var(--pudding-text-muted, #756b5f)',
    opacity: 0.72,
  },
  cameraInputPreviewFrame: {
    position: 'relative' as const,
    width: '100%',
    aspectRatio: '16 / 9',
    overflow: 'hidden' as const,
    borderRadius: 8,
    border:
      '1px solid color-mix(in srgb, var(--earth-brown, #5c4a3a) 12%, transparent)',
    background:
      'color-mix(in srgb, var(--pudding-surface-soft, #f3eee7) 76%, #000 4%)',
  },
  cameraInputPreviewMedia: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  cameraInputActionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  activeRunOutput: {
    margin: '0 0 4px 0',
  },
  
  paperStreaming: {
    background: 'color-mix(in srgb, var(--soft-white) 92%, #fff7df)',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 8%, transparent)',
    boxShadow: '0 1px 8px rgba(92, 64, 42, 0.04)',
    transition:
      'background 420ms ease, border-color 420ms ease, box-shadow 520ms ease',
    contain: 'paint',
  },
  paperSettled: {
    background: 'var(--soft-white)',
    borderColor: 'color-mix(in srgb, var(--earth-brown) 6%, transparent)',
    boxShadow: 'none',
    transition:
      'background 520ms ease, border-color 520ms ease, box-shadow 520ms ease',
  },
  actionButtonsSettled: {
    opacity: '1 !important' as unknown as number,
    transform: 'translateY(0) !important' as unknown as string,
    pointerEvents:
      'auto !important' as unknown as React.CSSProperties['pointerEvents'],
    transition: 'opacity 400ms ease-out, transform 400ms ease-out',
  },
  
}));

export const useChatStyles = () => {
  const { styles: layout, cx, theme } = useLayoutStyles();
  const { styles: message } = useMessageStyles();
  const { styles: agent } = useAgentStyles();
  const { styles: user } = useUserStyles();
  const { styles: process } = useProcessStyles();
  const { styles: reasoning } = useReasoningStyles();
  const { styles: markdown } = useMarkdownStyles();
  const { styles: composer } = useComposerStyles();
  const { styles: panel } = usePanelStyles();
    const { styles: voice } = useVoiceStyles();
    const { styles: heartbeat } = useHeartbeatStyles();
  const { styles: status } = useStatusStyles();
  const { styles: devpanel } = useDevpanelStyles();
  const { styles: animation } = useAnimationStyles();
  const { styles: sidebar } = useSidebarStyles();
  const { styles: residual } = useResidualStyles();

  return {
    styles: {
      ...layout,
      ...message,
      ...agent,
      ...user,
      ...process,
      ...reasoning,
      ...markdown,
      ...composer,
      ...panel,
            ...voice,
            ...heartbeat,
      ...status,
      ...devpanel,
      ...animation,
      ...sidebar,
      ...residual,
    },
    cx,
    theme,
  };
};
