using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;
using PuddingCode.Abstractions;
using PuddingCode.Platform;

namespace PuddingMemoryEngine.Services;

public static class SkillAdmissionActions
{
    public const string Create = "create";
    public const string Merge = "merge";
    public const string Skip = "skip";
    public const string Defer = "defer";
}

public sealed record SkillAdmissionResult
{
    public required string Action { get; init; }
    public string? TargetSkillId { get; init; }
    public double Confidence { get; init; }
    public string? Reason { get; init; }
}

public sealed record SkillConsolidationResult
{
    public int Consolidated { get; init; }
    public IReadOnlyList<string> UpdatedSkillIds { get; init; } = [];
    public IReadOnlyList<string> DisabledSkillIds { get; init; } = [];
}

/// <summary>
/// Autonomous, fail-closed semantic admission and consolidation for self-evolved Skills.
/// LLM proposals are never sufficient on their own: target identity, confidence,
/// tool fingerprints and evidence/text overlap are validated deterministically.
/// Duplicate Skills are disabled, not deleted, so every action is recoverable.
/// </summary>
public sealed partial class SkillEvolutionDeduplicationService(
    IAgentSkillEvolutionStore skillStore,
    IMemoryLlmClient memoryLlmClient,
    ILogger<SkillEvolutionDeduplicationService> logger)
{
    private const double CreateConfidence = 0.80;
    private const double ExistingDecisionConfidence = 0.90;
    private const double ConsolidationConfidence = 0.92;
    private const double MinimumTextSimilarity = 0.35;
    private const string DedupReviewMarkerPrefix = "dedup-reviewed:";
    private const string EvaluationMarkerPrefix = "self-evaluated:";

    private static readonly HashSet<string> StopWords = new(StringComparer.OrdinalIgnoreCase)
    {
        "and", "the", "for", "from", "with", "into", "this", "that", "current",
        "using", "use", "one", "each", "then", "your", "agent", "skill",
    };

    public async Task<SkillAdmissionResult> EvaluateAdmissionAsync(
        PatternCandidate candidate,
        MemoryLlmConfig? config,
        CancellationToken ct = default)
    {
        var existing = (await skillStore.ListAutoGeneratedAsync(candidate.AgentInstanceId, ct))
            .Where(skill => skill.Enabled)
            .Take(50)
            .ToArray();
        if (existing.Length == 0)
        {
            return new SkillAdmissionResult
            {
                Action = SkillAdmissionActions.Create,
                Confidence = 1,
                Reason = "No existing auto-generated Skill.",
            };
        }

        var prompt = JsonSerializer.Serialize(new
        {
            candidate = new
            {
                candidate.Title,
                candidate.Goal,
                candidate.ToolSequence,
                candidate.SessionId,
                candidate.TurnId,
                candidate.Evidence,
            },
            existingSkills = existing.Select(ToComparisonSnapshot),
        });

        const string systemPrompt = """
            You are the autonomous admission gate for Pudding self-evolved Skills.
            Compare the candidate with existing Skills by user intent and reusable procedure.
            Sharing tools is not enough: reference-image editing, styled generation, plain text-to-image,
            terminal polling and git commit preparation are materially different intents.
            Output JSON only:
            {"action":"create|merge|skip|defer","targetSkillId":string|null,"confidence":0.0-1.0,"reason":"..."}
            create: materially distinct capability.
            merge: same intent/procedure but candidate adds verified evidence or useful keywords.
            skip: an existing Skill already fully covers it.
            defer: uncertain. Never guess.
            """;

        try
        {
            var response = await memoryLlmClient.ChatWithConfigAsync(
                systemPrompt,
                prompt,
                WithStage(config, "skill-admission"),
                tools: null,
                ct: ct);
            var root = ParseJson(response);
            if (root is null)
                return Deferred("Admission response did not contain valid JSON.");

            var action = ReadString(root.Value, "action")?.Trim().ToLowerInvariant();
            var targetSkillId = ReadString(root.Value, "targetSkillId");
            var confidence = ReadDouble(root.Value, "confidence");
            var reason = ReadString(root.Value, "reason");

            if (action == SkillAdmissionActions.Create && confidence >= CreateConfidence)
            {
                return new SkillAdmissionResult
                {
                    Action = action,
                    Confidence = confidence,
                    Reason = reason,
                };
            }

            if ((string.Equals(action, SkillAdmissionActions.Merge, StringComparison.Ordinal)
                 || string.Equals(action, SkillAdmissionActions.Skip, StringComparison.Ordinal))
                && confidence >= ExistingDecisionConfidence
                && existing.Any(skill => string.Equals(
                    skill.SkillId,
                    targetSkillId,
                    StringComparison.OrdinalIgnoreCase)))
            {
                return new SkillAdmissionResult
                {
                    Action = action!,
                    TargetSkillId = targetSkillId!,
                    Confidence = confidence,
                    Reason = reason,
                };
            }

            return Deferred(reason ?? "Admission confidence or target validation failed.", confidence);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "[SkillDedup] Admission failed candidate={Candidate}", candidate.Title);
            return Deferred("Admission call failed.");
        }
    }

    public async Task<AgentSkillEvolutionDocument?> MergeCandidateAsync(
        PatternCandidate candidate,
        string targetSkillId,
        CancellationToken ct = default)
    {
        var target = await skillStore.GetAsync(candidate.AgentInstanceId, targetSkillId, ct);
        if (target is null || !target.Enabled)
            return null;

        if (ExtractSourceTurns(target).Contains(candidate.TurnId, StringComparer.Ordinal))
            return target;

        var newVersion = BumpVersion(target.Version);
        var evidence = new StringBuilder(RewriteMarkdownVersion(target.Markdown, newVersion).TrimEnd())
            .AppendLine()
            .AppendLine()
            .AppendLine("## 自动合并的验证证据")
            .AppendLine($"- 会话: {candidate.SessionId}")
            .AppendLine($"- Turn: {candidate.TurnId}")
            .AppendLine($"- 工具序列: {string.Join(" → ", candidate.ToolSequence)}")
            .AppendLine($"- 置信度: {candidate.Confidence:P0}");
        if (!string.IsNullOrWhiteSpace(candidate.Evidence))
            evidence.AppendLine($"- 证据: {candidate.Evidence.Trim()}");

        return await skillStore.UpdateAsync(candidate.AgentInstanceId, target.SkillId, new AgentSkillEvolutionWriteRequest
        {
            SkillId = target.SkillId,
            Name = target.Name,
            Version = newVersion,
            Description = target.Description,
            Tags = RemoveVersionMarker(Union(target.Tags,
            [
                "auto-generated",
                "self-evolution",
                "deduplicated",
                $"source-turn:{candidate.TurnId}",
                $"source-session:{candidate.SessionId}",
            ]), DedupReviewMarkerPrefix),
            Keywords = Union(target.Keywords, candidate.ToolSequence.Append(candidate.Title)),
            Markdown = evidence.ToString().TrimEnd() + Environment.NewLine,
        }, ct);
    }

    public async Task<SkillConsolidationResult> ConsolidateExistingAsync(
        string agentInstanceId,
        MemoryLlmConfig? config,
        CancellationToken ct = default)
    {
        var skills = (await skillStore.ListAutoGeneratedAsync(agentInstanceId, ct))
            .Where(skill => skill.Enabled)
            .Take(50)
            .ToArray();
        if (skills.All(HasCurrentDedupReview))
            return new SkillConsolidationResult();
        if (skills.Length < 2)
        {
            await MarkCurrentDedupReviewsAsync(
                agentInstanceId,
                skills.Select(skill => skill.SkillId).ToHashSet(StringComparer.OrdinalIgnoreCase),
                ct);
            return new SkillConsolidationResult();
        }

        var prompt = JsonSerializer.Serialize(new
        {
            skills = skills.Select(ToComparisonSnapshot),
        });
        const string systemPrompt = """
            You consolidate duplicate Pudding Skills without human review.
            Group Skills only when they solve the same user intent with an interchangeable procedure.
            Same tools alone are not enough. Keep narrower, materially distinct workflows separate.
            Choose the clearest and most complete Skill as canonical.
            Output JSON only:
            {"groups":[{"canonicalSkillId":"...","duplicateSkillIds":["..."],"confidence":0.0-1.0,"reason":"..."}],"distinctSkillIds":["..."]}
            distinctSkillIds contains only Skills you are confident are not duplicates of any other supplied Skill.
            Never list a Skill in both groups and distinctSkillIds. Omit uncertain Skills from both so they can be retried later.
            """;

        JsonElement? root;
        try
        {
            var response = await memoryLlmClient.ChatWithConfigAsync(
                systemPrompt,
                prompt,
                WithStage(config, "skill-consolidation"),
                tools: null,
                ct: ct);
            root = ParseJson(response);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "[SkillDedup] Existing Skill consolidation failed agent={Agent}", agentInstanceId);
            return new SkillConsolidationResult();
        }

        if (root is null
            || !root.Value.TryGetProperty("groups", out var groups)
            || groups.ValueKind != JsonValueKind.Array)
        {
            return new SkillConsolidationResult();
        }

        var byId = skills.ToDictionary(skill => skill.SkillId, StringComparer.OrdinalIgnoreCase);
        var consumed = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var updated = new List<string>();
        var disabled = new List<string>();
        var consolidated = 0;
        var reviewed = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var proposedGroupIds = groups
            .EnumerateArray()
            .SelectMany(group => EnumerateProposedGroupIds(group))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        if (root.Value.TryGetProperty("distinctSkillIds", out var distinctArray)
            && distinctArray.ValueKind == JsonValueKind.Array)
        {
            foreach (var distinctId in distinctArray
                         .EnumerateArray()
                         .Where(item => item.ValueKind == JsonValueKind.String)
                         .Select(item => item.GetString())
                         .Where(id => !string.IsNullOrWhiteSpace(id)
                                      && byId.ContainsKey(id!)
                                      && !proposedGroupIds.Contains(id!)))
            {
                reviewed.Add(distinctId!);
            }
        }

        foreach (var group in groups.EnumerateArray())
        {
            ct.ThrowIfCancellationRequested();
            var canonicalId = ReadString(group, "canonicalSkillId");
            var confidence = ReadDouble(group, "confidence");
            if (confidence < ConsolidationConfidence
                || string.IsNullOrWhiteSpace(canonicalId)
                || !byId.TryGetValue(canonicalId, out var canonical)
                || consumed.Contains(canonicalId)
                || !group.TryGetProperty("duplicateSkillIds", out var duplicateArray)
                || duplicateArray.ValueKind != JsonValueKind.Array)
            {
                continue;
            }

            var duplicates = duplicateArray
                .EnumerateArray()
                .Where(item => item.ValueKind == JsonValueKind.String)
                .Select(item => item.GetString())
                .Where(id => !string.IsNullOrWhiteSpace(id)
                             && !string.Equals(id, canonicalId, StringComparison.OrdinalIgnoreCase)
                             && byId.ContainsKey(id!))
                .Select(id => byId[id!])
                .Where(skill => !consumed.Contains(skill.SkillId))
                .Where(skill => IsDeterministicallyEligible(canonical, skill))
                .ToArray();
            if (duplicates.Length == 0)
                continue;

            var newVersion = BumpVersion(canonical.Version);
            var mergedMarkdown = BuildConsolidatedMarkdown(canonical, duplicates, newVersion);
            var mergedTags = Union(
                canonical.Tags,
                duplicates.SelectMany(skill => skill.Tags).Append("deduplicated"));
            var mergedKeywords = Union(
                canonical.Keywords,
                duplicates.SelectMany(skill => skill.Keywords));
            canonical = await skillStore.UpdateAsync(agentInstanceId, canonical.SkillId, new AgentSkillEvolutionWriteRequest
            {
                SkillId = canonical.SkillId,
                Name = canonical.Name,
                Version = newVersion,
                Description = canonical.Description,
                Tags = mergedTags,
                Keywords = mergedKeywords,
                Markdown = mergedMarkdown,
            }, ct);
            updated.Add(canonical.SkillId);
            consumed.Add(canonical.SkillId);
            reviewed.Add(canonical.SkillId);

            foreach (var duplicate in duplicates)
            {
                await skillStore.UpdateAsync(agentInstanceId, duplicate.SkillId, new AgentSkillEvolutionWriteRequest
                {
                    SkillId = duplicate.SkillId,
                    Name = duplicate.Name,
                    Version = duplicate.Version,
                    Description = duplicate.Description,
                    Tags = Union(
                        duplicate.Tags,
                        ["superseded", $"superseded-by:{canonical.SkillId}"]),
                    Keywords = duplicate.Keywords,
                    Markdown = duplicate.Markdown,
                }, ct);
                await skillStore.SetEnabledAsync(agentInstanceId, duplicate.SkillId, enabled: false, ct);
                disabled.Add(duplicate.SkillId);
                consumed.Add(duplicate.SkillId);
                reviewed.Add(duplicate.SkillId);
                consolidated++;
            }

            logger.LogInformation(
                "[SkillDedup] Consolidated canonical={Canonical} disabled={Disabled} confidence={Confidence:F2}",
                canonical.SkillId,
                string.Join(",", duplicates.Select(skill => skill.SkillId)),
                confidence);
        }

        await MarkCurrentDedupReviewsAsync(agentInstanceId, reviewed, ct);
        return new SkillConsolidationResult
        {
            Consolidated = consolidated,
            UpdatedSkillIds = updated,
            DisabledSkillIds = disabled,
        };
    }

    public static IReadOnlySet<string> ExtractProcessedTurnIds(
        IEnumerable<AgentSkillEvolutionDocument> skills)
    {
        return skills
            .SelectMany(ExtractSourceTurns)
            .Where(turnId => !string.IsNullOrWhiteSpace(turnId))
            .ToHashSet(StringComparer.Ordinal);
    }

    public static bool HasCurrentEvaluation(AgentSkillEvolutionDocument skill)
        => HasVersionMarker(skill, EvaluationMarkerPrefix);

    public async Task<AgentSkillEvolutionDocument> MarkEvaluatedAsync(
        string agentInstanceId,
        AgentSkillEvolutionDocument skill,
        CancellationToken ct = default)
    {
        if (HasCurrentEvaluation(skill))
            return skill;
        return await skillStore.UpdateAsync(agentInstanceId, skill.SkillId, new AgentSkillEvolutionWriteRequest
        {
            SkillId = skill.SkillId,
            Name = skill.Name,
            Version = skill.Version,
            Description = skill.Description,
            Tags = ReplaceVersionMarker(skill.Tags, EvaluationMarkerPrefix, skill.Version),
            Keywords = skill.Keywords,
            Markdown = skill.Markdown,
        }, ct);
    }

    public static IReadOnlyList<string> WithEvaluationMarker(
        IEnumerable<string> tags,
        string version)
        => ReplaceVersionMarker(tags, EvaluationMarkerPrefix, version);

    private static object ToComparisonSnapshot(AgentSkillEvolutionDocument skill) => new
    {
        skill.SkillId,
        skill.Name,
        skill.Description,
        skill.Keywords,
        toolSequence = ExtractToolKeywords(skill),
        sourceTurnIds = ExtractSourceTurns(skill),
    };

    private static bool IsDeterministicallyEligible(
        AgentSkillEvolutionDocument canonical,
        AgentSkillEvolutionDocument duplicate)
    {
        var canonicalTools = ExtractToolKeywords(canonical);
        var duplicateTools = ExtractToolKeywords(duplicate);
        if (canonicalTools.Count == 0 || !canonicalTools.SetEquals(duplicateTools))
            return false;

        var textSimilarity = CalculateTextSimilarity(canonical, duplicate);
        if (textSimilarity < 0.20)
            return false;

        var sharedTurn = ExtractSourceTurns(canonical)
            .Intersect(ExtractSourceTurns(duplicate), StringComparer.Ordinal)
            .Any();
        return sharedTurn || textSimilarity >= MinimumTextSimilarity;
    }

    private static HashSet<string> ExtractToolKeywords(AgentSkillEvolutionDocument skill)
    {
        return skill.Keywords
            .Where(keyword => ToolKeywordRegex().IsMatch(keyword))
            .Select(keyword => keyword.ToLowerInvariant())
            .ToHashSet(StringComparer.Ordinal);
    }

    private static IReadOnlyList<string> ExtractSourceTurns(AgentSkillEvolutionDocument skill)
    {
        var structured = skill.Tags
            .Where(tag => tag.StartsWith("source-turn:", StringComparison.OrdinalIgnoreCase))
            .Select(tag => tag["source-turn:".Length..].Trim());
        var legacy = SourceTurnRegex()
            .Matches(skill.Markdown ?? string.Empty)
            .Cast<Match>()
            .Select(match => match.Groups[1].Value.Trim());
        return structured
            .Concat(legacy)
            .Where(value => value.Length > 0)
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    private static double CalculateTextSimilarity(
        AgentSkillEvolutionDocument left,
        AgentSkillEvolutionDocument right)
    {
        var leftTokens = Tokenize($"{left.Name} {left.Description}");
        var rightTokens = Tokenize($"{right.Name} {right.Description}");
        if (leftTokens.Count == 0 || rightTokens.Count == 0)
            return 0;
        var intersection = leftTokens.Intersect(rightTokens, StringComparer.OrdinalIgnoreCase).Count();
        var union = leftTokens.Union(rightTokens, StringComparer.OrdinalIgnoreCase).Count();
        return union == 0 ? 0 : (double)intersection / union;
    }

    private static HashSet<string> Tokenize(string text)
    {
        return WordRegex()
            .Matches(text.ToLowerInvariant())
            .Cast<Match>()
            .Select(match => match.Value)
            .Where(token => token.Length > 2 && !StopWords.Contains(token))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static string BuildConsolidatedMarkdown(
        AgentSkillEvolutionDocument canonical,
        IReadOnlyList<AgentSkillEvolutionDocument> duplicates,
        string newVersion)
    {
        var builder = new StringBuilder(RewriteMarkdownVersion(canonical.Markdown, newVersion).TrimEnd())
            .AppendLine()
            .AppendLine()
            .AppendLine("## 自动去重记录")
            .AppendLine($"- 合并时间: {DateTimeOffset.UtcNow:O}");
        foreach (var duplicate in duplicates)
        {
            builder.AppendLine($"- 已吸收并禁用: `{duplicate.SkillId}`");
            foreach (var turnId in ExtractSourceTurns(duplicate))
                builder.AppendLine($"  - 来源 Turn: {turnId}");
        }
        return builder.ToString().TrimEnd() + Environment.NewLine;
    }

    private static IReadOnlyList<string> Union(
        IEnumerable<string> first,
        IEnumerable<string> second)
    {
        return first
            .Concat(second)
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(value => value, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    private async Task MarkCurrentDedupReviewsAsync(
        string agentInstanceId,
        IReadOnlySet<string> reviewedSkillIds,
        CancellationToken ct)
    {
        if (reviewedSkillIds.Count == 0)
            return;
        var currentSkills = (await skillStore.ListAutoGeneratedAsync(agentInstanceId, ct))
            .Where(skill => skill.Enabled)
            .Take(50)
            .Where(skill => reviewedSkillIds.Contains(skill.SkillId))
            .Where(skill => !HasCurrentDedupReview(skill))
            .ToArray();
        foreach (var skill in currentSkills)
        {
            await skillStore.UpdateAsync(agentInstanceId, skill.SkillId, new AgentSkillEvolutionWriteRequest
            {
                SkillId = skill.SkillId,
                Name = skill.Name,
                Version = skill.Version,
                Description = skill.Description,
                Tags = ReplaceVersionMarker(skill.Tags, DedupReviewMarkerPrefix, skill.Version),
                Keywords = skill.Keywords,
                Markdown = skill.Markdown,
            }, ct);
        }
    }

    private static bool HasCurrentDedupReview(AgentSkillEvolutionDocument skill)
        => HasVersionMarker(skill, DedupReviewMarkerPrefix);

    private static bool HasVersionMarker(
        AgentSkillEvolutionDocument skill,
        string prefix)
        => skill.Tags.Any(tag => string.Equals(
            tag,
            $"{prefix}{skill.Version}",
            StringComparison.OrdinalIgnoreCase));

    private static IReadOnlyList<string> RemoveVersionMarker(
        IEnumerable<string> tags,
        string prefix)
        => tags
            .Where(tag => !tag.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            .ToArray();

    private static IReadOnlyList<string> ReplaceVersionMarker(
        IEnumerable<string> tags,
        string prefix,
        string version)
        => Union(RemoveVersionMarker(tags, prefix), [$"{prefix}{version}"]);

    private static IEnumerable<string> EnumerateProposedGroupIds(JsonElement group)
    {
        var canonicalId = ReadString(group, "canonicalSkillId");
        if (!string.IsNullOrWhiteSpace(canonicalId))
            yield return canonicalId;
        if (!group.TryGetProperty("duplicateSkillIds", out var duplicateArray)
            || duplicateArray.ValueKind != JsonValueKind.Array)
        {
            yield break;
        }
        foreach (var duplicateId in duplicateArray
                     .EnumerateArray()
                     .Where(item => item.ValueKind == JsonValueKind.String)
                     .Select(item => item.GetString())
                     .Where(id => !string.IsNullOrWhiteSpace(id)))
        {
            yield return duplicateId!;
        }
    }

    private static string BumpVersion(string version)
    {
        var parts = (version ?? string.Empty).TrimStart('v').Split('.');
        if (parts.Length == 3 && int.TryParse(parts[2], out var patch))
        {
            parts[2] = (patch + 1).ToString();
            return string.Join('.', parts);
        }
        return string.IsNullOrWhiteSpace(version) ? "1.0.1" : version + ".1";
    }

    private static string RewriteMarkdownVersion(string markdown, string version)
        => MarkdownVersionRegex().Replace(markdown, $"${{1}}{version}", count: 1);

    private static MemoryLlmConfig? WithStage(MemoryLlmConfig? config, string stage)
        => config is null ? null : config with { Stage = stage };

    private static SkillAdmissionResult Deferred(string reason, double confidence = 0)
        => new()
        {
            Action = SkillAdmissionActions.Defer,
            Confidence = confidence,
            Reason = reason,
        };

    private static JsonElement? ParseJson(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return null;
        var start = raw.IndexOf('{');
        var end = raw.LastIndexOf('}');
        if (start < 0 || end <= start)
            return null;
        try
        {
            using var document = JsonDocument.Parse(raw[start..(end + 1)]);
            return document.RootElement.Clone();
        }
        catch (JsonException)
        {
            return null;
        }
    }

    private static string? ReadString(JsonElement element, string property)
        => element.TryGetProperty(property, out var value) && value.ValueKind == JsonValueKind.String
            ? value.GetString()
            : null;

    private static double ReadDouble(JsonElement element, string property)
        => element.TryGetProperty(property, out var value)
           && value.ValueKind == JsonValueKind.Number
           && value.TryGetDouble(out var result)
            ? result
            : 0;

    [GeneratedRegex(@"(?im)^\s*-\s*Turn:\s*([^\r\n]+)")]
    private static partial Regex SourceTurnRegex();

    [GeneratedRegex(@"^[a-z][a-z0-9]*(?:_[a-z0-9]+)+$", RegexOptions.IgnoreCase)]
    private static partial Regex ToolKeywordRegex();

    [GeneratedRegex(@"[a-z0-9]+", RegexOptions.IgnoreCase)]
    private static partial Regex WordRegex();

    [GeneratedRegex(@"(?im)^(\s*version:\s*)[^\r\n]+$")]
    private static partial Regex MarkdownVersionRegex();
}
