// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuddingController.Data;

#nullable disable

namespace PuddingController.Migrations
{
    [DbContext(typeof(ControllerDbContext))]
    partial class ControllerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ctrl")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuddingController.Data.Entities.AuditEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("AgentTemplateId")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalId")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("AuditEvents", "ctrl");
                });

            modelBuilder.Entity("PuddingController.Data.Entities.RouteDecisionEntity", b =>
                {
                    b.Property<string>("RouteDecisionId")
                        .HasColumnType("text");

                    b.Property<string>("AgentTemplateId")
                        .HasColumnType("text");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceId")
                        .HasColumnType("text");

                    b.HasKey("RouteDecisionId");

                    b.HasIndex("MessageId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("RouteDecisions", "ctrl");
                });

            modelBuilder.Entity("PuddingController.Data.Entities.WorkspaceDefinitionEntity", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasColumnType("text");

                    b.Property<string>("AgentTemplateIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AuditAgentTemplateIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ChannelBindingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExtrasJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionPolicyJson")
                        .HasColumnType("jsonb");

                    b.HasKey("WorkspaceId");

                    b.ToTable("WorkspaceDefinitions", "ctrl");
                });
#pragma warning restore 612, 618
        }
    }
}
